### ISSUE TITLE
[TH] Reactions > Attempted to convert NULL to serialized array [first_react_users]

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#104]
I am getting server log about Attempted to convert NULL to serialized array [first_react_users], does its bug from Reactions?

````
InvalidArgumentException: Attempted to convert NULL to serialized array [first_react_users] src/XF/Mvc/Entity/Entity.php:685

Generated by: prinanad Jan 5, 2018 at 3:01 PM

Stack trace

#0 src/XF/Mvc/Entity/Entity.php(572): XF\Mvc\Entity\Entity->_castValueToType(NULL, 'first_react_use...', 65544, Array)
#1 src/XF/Mvc/Entity/Entity.php(671): XF\Mvc\Entity\Entity->set('first_react_use...', NULL, Array)
#2 src/XF/Repository/ThreadRedirect.php(24): XF\Mvc\Entity\Entity->bulkSet(Array)
#3 src/XF/Service/Thread/Mover.php(106): XF\Repository\ThreadRedirect->createThreadRedirectionDouble(Object(Tapatalk\XF\Entity\Thread), Object(XenConcept\UserActivity\XF\Entity\Forum), 86400)
#4 src/XF/Pub/Controller/Thread.php(999): XF\Service\Thread\Mover->move(Object(XenConcept\UserActivity\XF\Entity\Forum))
#5 src/XF/Mvc/Dispatcher.php(249): XF\Pub\Controller\Thread->actionMove(Object(XF\Mvc\ParameterBag))
#6 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('XF:Thread', 'Move', 'json', Object(XF\Mvc\ParameterBag), 'forums', Object(NF\TrashCan\XF\Pub\Controller\Thread), NULL)
#7 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#8 src/XF/App.php(1880): XF\Mvc\Dispatcher->run()
#9 src/XF.php(328): XF\App->run()
#10 index.php(13): XF::runApp('XF\\Pub\\App')
#11 {main}

-------------

Previous InvalidArgumentException: Attempted to convert NULL to serialized array - src/XF/Mvc/Entity/ValueFormatter.php:142
#0 src/XF/Mvc/Entity/Entity.php(681): XF\Mvc\Entity\ValueFormatter->castValueToType(NULL, 65544, Array)
#1 src/XF/Mvc/Entity/Entity.php(572): XF\Mvc\Entity\Entity->_castValueToType(NULL, 'first_react_use...', 65544, Array)
#2 src/XF/Mvc/Entity/Entity.php(671): XF\Mvc\Entity\Entity->set('first_react_use...', NULL, Array)
#3 src/XF/Repository/ThreadRedirect.php(24): XF\Mvc\Entity\Entity->bulkSet(Array)
#4 src/XF/Service/Thread/Mover.php(106): XF\Repository\ThreadRedirect->createThreadRedirectionDouble(Object(Tapatalk\XF\Entity\Thread), Object(XenConcept\UserActivity\XF\Entity\Forum), 86400)
#5 src/XF/Pub/Controller/Thread.php(999): XF\Service\Thread\Mover->move(Object(XenConcept\UserActivity\XF\Entity\Forum))
#6 src/XF/Mvc/Dispatcher.php(249): XF\Pub\Controller\Thread->actionMove(Object(XF\Mvc\ParameterBag))
#7 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('XF:Thread', 'Move', 'json', Object(XF\Mvc\ParameterBag), 'forums', Object(NF\TrashCan\XF\Pub\Controller\Thread), NULL)
#8 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#9 src/XF/App.php(1880): XF\Mvc\Dispatcher->run()
#10 src/XF.php(328): XF\App->run()
#11 index.php(13): XF::runApp('XF\\Pub\\App')
#12 {main}

Request state

array(4) {
  ["url"] => string(64) "/threads/exclusive-threesome-pair-face-clips-6-videos.78395/move"
  ["referrer"] => string(86) "/threads/exclusive-threesome-pair-face-clips-6-videos.78395/"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(12) {
    ["prefix_id"] => string(1) "0"
    ["title"] => string(45) "Exclusive Threesome Pair- Face Clips 6 Videos"
    ["target_node_id"] => string(2) "51"
    ["redirect_type"] => string(9) "temporary"
    ["redirect_length"] => array(2) {
      ["amount"] => string(1) "1"
      ["unit"] => string(4) "days"
    }
    ["notify_watchers"] => string(1) "1"
    ["starter_alert"] => string(1) "1"
    ["starter_alert_reason"] => string(0) ""
    ["_xfToken"] => string(8) "********"
    ["_xfRequestUri"] => string(60) "/threads/exclusive-threesome-pair-face-clips-6-videos.78395/"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}
````

More info here: https://xenforo.com/community/threads/attempted-to-convert-null-to-serialized-array-first_react_users.140478/#post-1209642

**Comment by ellisonpatterson** [comment]
Created a forceful check to see if the value is null and set to an array. Not exactly sure how this is happening since it's set by default to use an array so it's odd.
