### ISSUE TITLE
[TH] Reactions > MySQL query error [1062]: Duplicate entry 'post-1125727-20231' for key 'content_type_id_like_user_id'

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#105]
I am also getting this error log.

````
XF\Db\DuplicateKeyException: MySQL query error [1062]: Duplicate entry 'post-1125727-20231' for key 'content_type_id_like_user_id' src/XF/Db/AbstractStatement.php:212

Generated by: Jajm Jan 2, 2018 at 7:18 PM

Stack trace

INSERT  INTO `xf_liked_content` (`content_type`, `content_id`, `like_user_id`, `content_user_id`, `is_counted`, `like_id`, `like_date`) VALUES (?, ?, ?, ?, ?, ?, ?)
------------

#0 src/XF/Db/Mysqli/Statement.php(174): XF\Db\AbstractStatement->getException('MySQL query err...', 1062, '23000')
#1 src/XF/Db/Mysqli/Statement.php(69): XF\Db\Mysqli\Statement->getException('MySQL query err...', 1062, '23000')
#2 src/XF/Db/AbstractAdapter.php(74): XF\Db\Mysqli\Statement->execute()
#3 src/XF/Db/AbstractAdapter.php(150): XF\Db\AbstractAdapter->query('INSERT  INTO `x...', Array)
#4 src/XF/Mvc/Entity/Entity.php(1381): XF\Db\AbstractAdapter->insert('xf_liked_conten...', Array)
#5 src/XF/Mvc/Entity/Entity.php(1113): XF\Mvc\Entity\Entity->_saveToSource()
#6 src/XF/Repository/LikedContent.php(94): XF\Mvc\Entity\Entity->save()
#7 src/addons/ThemeHouse/Reactions/Entity/ReactedContent.php(143): XF\Repository\LikedContent->insertLike('post', 1125727, Object(Datio\AllowedEmails\XF\Entity\User), false)
#8 src/addons/ThemeHouse/Reactions/Entity/ReactedContent.php(93): ThemeHouse\Reactions\Entity\ReactedContent->toggleLike()
#9 src/XF/Mvc/Entity/Entity.php(1137): ThemeHouse\Reactions\Entity\ReactedContent->_postSave()
#10 src/addons/ThemeHouse/Reactions/Repository/ReactedContent.php(101): XF\Mvc\Entity\Entity->save()
#11 src/addons/ThemeHouse/Reactions/ControllerPlugin/React.php(22): ThemeHouse\Reactions\Repository\ReactedContent->insertReact(Object(haydric\toRights\XF\Entity\Post), Object(ThemeHouse\Reactions\Entity\ReactedContent))
#12 src/addons/ThemeHouse/Reactions/Pub/Controller/React.php(27): ThemeHouse\Reactions\ControllerPlugin\React->actionToggleReact(Object(haydric\toRights\XF\Entity\Post), Object(ThemeHouse\Reactions\Entity\ReactedContent), 'insert')
#13 src/XF/Mvc/Dispatcher.php(249): ThemeHouse\Reactions\Pub\Controller\React->actionReact(Object(XF\Mvc\ParameterBag))
#14 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Reac...', 'React', 'json', Object(XF\Mvc\ParameterBag), 'reactions', Object(ThemeHouse\Reactions\Pub\Controller\React), NULL)
#15 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#16 src/XF/App.php(1880): XF\Mvc\Dispatcher->run()
#17 src/XF.php(328): XF\App->run()
#18 index.php(13): XF::runApp('XF\\Pub\\App')
#19 {main}

Request state

array(4) {
  ["url"] => string(31) "/reactions/react/post/1125727/2"
  ["referrer"] => string(47) "/threads/28684/page-8"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(4) {
    ["_xfRequestUri"] => string(21) "/threads/28684/page-8"
    ["_xfWithData"] => string(1) "1"
    ["_xfToken"] => string(8) "********"
    ["_xfResponseType"] => string(4) "json"
  }
} 
````

**Comment by ellisonpatterson** [comment]
@Nirjonadda I think this is some type of conflict with another add-on. Reactions has always checked for existing likes before inserting one and the fact that the add-on sets the default of that column to an empty array is telling me something is causing other add-ons to not fire properly.

**Comment by Nirjonadda** [comment]
@ellisonpatterson @JakeBooher What add-on conflict. Lot of log happened and does not found any other add-on name in error log.

````
XF\Db\DuplicateKeyException: MySQL query error [1062]: Duplicate entry 'post-1238216-17931' for key 'content_type_id_like_user_id' src/XF/Db/AbstractStatement.php:212 

Generated by: HasanRahan Jan 9, 2018 at 9:47 PM 

Stack trace

INSERT  INTO `xf_liked_content` (`content_type`, `content_id`, `like_user_id`, `content_user_id`, `is_counted`, `like_id`, `like_date`) VALUES (?, ?, ?, ?, ?, ?, ?)
------------

#0 src/XF/Db/Mysqli/Statement.php(174): XF\Db\AbstractStatement->getException('MySQL query err...', 1062, '23000')
#1 src/XF/Db/Mysqli/Statement.php(69): XF\Db\Mysqli\Statement->getException('MySQL query err...', 1062, '23000')
#2 src/XF/Db/AbstractAdapter.php(74): XF\Db\Mysqli\Statement->execute()
#3 src/XF/Db/AbstractAdapter.php(150): XF\Db\AbstractAdapter->query('INSERT  INTO `x...', Array)
#4 src/XF/Mvc/Entity/Entity.php(1381): XF\Db\AbstractAdapter->insert('xf_liked_conten...', Array)
#5 src/XF/Mvc/Entity/Entity.php(1113): XF\Mvc\Entity\Entity->_saveToSource()
#6 src/XF/Repository/LikedContent.php(94): XF\Mvc\Entity\Entity->save()
#7 src/addons/ThemeHouse/Reactions/Entity/ReactedContent.php(143): XF\Repository\LikedContent->insertLike('post', 1238216, Object(Datio\AllowedEmails\XF\Entity\User), false)
#8 src/addons/ThemeHouse/Reactions/Entity/ReactedContent.php(93): ThemeHouse\Reactions\Entity\ReactedContent->toggleLike()
#9 src/XF/Mvc/Entity/Entity.php(1137): ThemeHouse\Reactions\Entity\ReactedContent->_postSave()
#10 src/addons/ThemeHouse/Reactions/Repository/ReactedContent.php(101): XF\Mvc\Entity\Entity->save()
#11 src/addons/ThemeHouse/Reactions/ControllerPlugin/React.php(22): ThemeHouse\Reactions\Repository\ReactedContent->insertReact(Object(haydric\toRights\XF\Entity\Post), Object(ThemeHouse\Reactions\Entity\ReactedContent))
#12 src/addons/ThemeHouse/Reactions/Pub/Controller/React.php(27): ThemeHouse\Reactions\ControllerPlugin\React->actionToggleReact(Object(haydric\toRights\XF\Entity\Post), Object(ThemeHouse\Reactions\Entity\ReactedContent), 'insert')
#13 src/XF/Mvc/Dispatcher.php(249): ThemeHouse\Reactions\Pub\Controller\React->actionReact(Object(XF\Mvc\ParameterBag))
#14 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Reac...', 'React', 'json', Object(XF\Mvc\ParameterBag), 'reactions', Object(ThemeHouse\Reactions\Pub\Controller\React), NULL)
#15 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#16 src/XF/App.php(1880): XF\Mvc\Dispatcher->run()
#17 src/XF.php(328): XF\App->run()
#18 index.php(13): XF::runApp('XF\\Pub\\App')
#19 {main}

Request state

array(4) {
  ["url"] => string(31) "/reactions/react/post/1238216/2"
  ["referrer"] => string(47) "/threads/39926/page-2"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(4) {
    ["_xfRequestUri"] => string(21) "/threads/39926/page-2"
    ["_xfWithData"] => string(1) "1"
    ["_xfToken"] => string(8) "********"
    ["_xfResponseType"] => string(4) "json"
  }
}
````

**Comment by ellisonpatterson** [comment]
@nikkiradloff well how are you creating this error, or is it happening constantly as it is always checking so I'm not sure how to recreate it.

**Comment by afree-ir** [comment]
hi 
i have this error please help me 
array(4) {
["url"] => string(26) "/profile-posts/1987/delete"
["referrer"] => string(51) "https://afree.ir/"
["_GET"] => array(0) {
}
["_POST"] => array(7) {
["reason"] => string(0) ""
["hard_delete"] => string(1) "0"
["_xfRedirect"] => string(51) "https://afree.ir/"
["_xfToken"] => string(8) "********"
["_xfRequestUri"] => string(19) "/members/ahorah.36/"
["_xfWithData"] => string(1) "1"
["_xfResponseType"] => string(4) "json"
}
}
