### ISSUE TITLE
Install and upgrade - Cant export themes

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#1058]
```ErrorException: [E_WARNING] array_merge(): Argument #2 is not an array in src/addons/ThemeHouse/InstallAndUpgrade/XF/Service/Style/Export.php at line 25
XF::handlePhpError()
array_merge() in src/addons/ThemeHouse/InstallAndUpgrade/XF/Service/Style/Export.php at line 25
ThemeHouse\InstallAndUpgrade\XF\Service\Style\Export->getStyleNode() in src/XF/Service/Style/Export.php at line 63
XF\Service\Style\Export->exportToXml() in src/XF/Admin/Controller/Style.php at line 428
XF\Admin\Controller\Style->actionExport() in src/XF/Mvc/Dispatcher.php at line 249
XF\Mvc\Dispatcher->dispatchClass() in src/XF/Mvc/Dispatcher.php at line 88
XF\Mvc\Dispatcher->dispatchLoop() in src/XF/Mvc/Dispatcher.php at line 41
XF\Mvc\Dispatcher->run() in src/XF/App.php at line 1931
XF\App->run() in src/XF.php at line 329
XF::runApp() in admin.php at line 13```

**Comment by joyfreak** [comment]
Server error log
ErrorException: [E_NOTICE] Trying to get property of non-object src/addons/ThemeHouse/InstallAndUpgrade/XF/Service/Style/Export.php:25
Generated by: Savage Oct 26, 2018 at 9:34 PM
Stack trace
#0 src/addons/ThemeHouse/InstallAndUpgrade/XF/Service/Style/Export.php(25): XF::handlePhpError(8, 'Trying to get p...', '/home/gnonline/...', 25, Array)
#1 src/XF/Service/Style/Export.php(63): ThemeHouse\InstallAndUpgrade\XF\Service\Style\Export->getStyleNode(Object(DOMDocument))
#2 src/XF/Admin/Controller/Style.php(428): XF\Service\Style\Export->exportToXml()
#3 src/XF/Mvc/Dispatcher.php(249): XF\Admin\Controller\Style->actionExport(Object(XF\Mvc\ParameterBag))
#4 src/XF/Mvc/Dispatcher.php(89): XF\Mvc\Dispatcher->dispatchClass('XF:Style', 'export', 'html', Object(XF\Mvc\ParameterBag), 'styles', Object(ThemeHouse\UIX\XF\Admin\Controller\Style), NULL)
#5 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#6 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#7 src/XF.php(329): XF\App->run()
#8 admin.php(13): XF::runApp('XF\\Admin\\App')
#9 {main}
Request state
array(4) {
  ["url"] => string(31) "/admin.php?styles/gno.58/export"
  ["referrer"] => string(42) "https://www.joyfreak.com/admin.php?styles/"
  ["_GET"] => array(1) {
    ["styles/gno_58/export"] => string(0) ""
  }
  ["_POST"] => array(2) {
    ["addon_id"] => string(0) ""
    ["_xfToken"] => string(8) "********"
  }
}

**Comment by joyfreak** [comment]
Server error log
ErrorException: [E_WARNING] array_merge(): Argument #2 is not an array src/addons/ThemeHouse/InstallAndUpgrade/XF/Service/Style/Export.php:25
Generated by: Savage Oct 26, 2018 at 9:34 PM
Stack trace
#0 [internal function]: XF::handlePhpError(2, 'array_merge(): ...', '/home/gnonline/...', 25, Array)
#1 src/addons/ThemeHouse/InstallAndUpgrade/XF/Service/Style/Export.php(25): array_merge(Array, NULL)
#2 src/XF/Service/Style/Export.php(63): ThemeHouse\InstallAndUpgrade\XF\Service\Style\Export->getStyleNode(Object(DOMDocument))
#3 src/XF/Admin/Controller/Style.php(428): XF\Service\Style\Export->exportToXml()
#4 src/XF/Mvc/Dispatcher.php(249): XF\Admin\Controller\Style->actionExport(Object(XF\Mvc\ParameterBag))
#5 src/XF/Mvc/Dispatcher.php(89): XF\Mvc\Dispatcher->dispatchClass('XF:Style', 'export', 'html', Object(XF\Mvc\ParameterBag), 'styles', Object(ThemeHouse\UIX\XF\Admin\Controller\Style), NULL)
#6 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#7 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#8 src/XF.php(329): XF\App->run()
#9 admin.php(13): XF::runApp('XF\\Admin\\App')
#10 {main}
Request state
array(4) {
  ["url"] => string(31) "/admin.php?styles/gno.58/export"
  ["referrer"] => string(42) "https://www.joyfreak.com/admin.php?styles/"
  ["_GET"] => array(1) {
    ["styles/gno_58/export"] => string(0) ""
  }
  ["_POST"] => array(2) {
    ["addon_id"] => string(0) ""
    ["_xfToken"] => string(8) "********"
  }
}
