### ISSUE TITLE
donations_recur already exists, but cannot change length

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#1079]
Affects people that upgraded from the XF1 version of donate and try to update to latest 1.0.4

```
LogicException: donations_recur already exists in table, but cannot change length src/XF/Db/Schema/Column.php:361

Stack trace

#0 src/XF/Db/Schema/Alter.php(238): XF\Db\Schema\Column->getDefinition()
#1 src/XF/Db/Schema/AbstractDdl.php(147): XF\Db\Schema\Alter->getQueries()
#2 src/XF/Db/SchemaManager.php(143): XF\Db\Schema\AbstractDdl->apply()
#3 src/addons/ThemeHouse/Donate/Setup.php(347): XF\Db\SchemaManager->alterTable('xf_thdonate_cam...', Object(Closure))
#4 src/XF/AddOn/StepRunnerUpgradeTrait.php(122): ThemeHouse\Donate\Setup->upgrade901000470Step1(Array)
#5 src/XF/AddOn/StepRunnerUpgradeTrait.php(71): ThemeHouse\Donate\Setup->upgradeStepRunner(901000470, 1, Array, NULL)
#6 src/XF/Cli/Command/AddOnActionTrait.php(107): ThemeHouse\Donate\Setup->upgrade(Array)
#7 src/XF/Cli/Command/AddOnSubAction.php(81): XF\Cli\Command\AddOnSubAction->performAddOnAction(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(XF\AddOn\AddOn), Object(XF\Phrase), 'upgrade')
#8 src/vendor/symfony/console/Command/Command.php(241): XF\Cli\Command\AddOnSubAction->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 src/vendor/symfony/console/Application.php(843): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 src/vendor/symfony/console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(XF\Cli\Command\AddOnSubAction), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 src/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 src/XF/Cli/Runner.php(63): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 cmd.php(15): XF\Cli\Runner->run()
#14 {main}
```

**Comment by LukasWieditz** [comment]
Apparently also crashing on `$table->addColumn('recurring', 'bool')->setDefault(0);` in the `upgrade901000470Step2()`.
