### ISSUE TITLE
[TH] Install & Upgrade -      InvalidArgumentException: First argument should be a string src/vendor/league/flysystem/src/MountManager.php:134

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1088]
Server error log.

````
InvalidArgumentException: First argument should be a string src/vendor/league/flysystem/src/MountManager.php:134 

Generated by: Nirjonadda Oct 30, 2018 at 10:32 PM 

Stack trace

#0 src/vendor/league/flysystem/src/MountManager.php(177): League\Flysystem\MountManager->filterPrefix(Array)
#1 src/XF/Util/File.php(141): League\Flysystem\MountManager->__call('has', Array)
#2 src/addons/ThemeHouse/InstallAndUpgrade/InstallAndUpgrade/AbstractHandler.php(251): XF\Util\File::abstractedPathExists(NULL)
#3 src/addons/ThemeHouse/InstallAndUpgrade/InstallAndUpgrade/AbstractHandler.php(527): ThemeHouse\InstallAndUpgrade\InstallAndUpgrade\AbstractHandler->extractZip(NULL)
#4 src/addons/ThemeHouse/InstallAndUpgrade/Admin/Controller/InstallUpgrade.php(267): ThemeHouse\InstallAndUpgrade\InstallAndUpgrade\AbstractHandler->upgradeAddOn(Object(ThemeHouse\InstallAndUpgrade\Entity\AddOn))
#5 src/XF/Mvc/Dispatcher.php(249): ThemeHouse\InstallAndUpgrade\Admin\Controller\InstallUpgrade->actionUpdate(Object(XF\Mvc\ParameterBag))
#6 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Inst...', 'Update', 'json', Object(XF\Mvc\ParameterBag), '', Object(ThemeHouse\InstallAndUpgrade\Admin\Controller\InstallUpgrade), NULL)
#7 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#8 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#9 src/XF.php(329): XF\App->run()
#10 admin.php(13): XF::runApp('XF\\Admin\\App')
#11 {main}

Request state

array(4) {
  ["url"] => string(187) "/admin.php?install-upgrade/addOn/ThemeHouse-Donate/update&_xfRequestUri=%2Fadmin.php%3Fadd-ons%2F&_xfWithData=1&_xfToken=1540917130%2Cb641241db759ad8218680616c558b528&_xfResponseType=json"
  ["referrer"] => string(42) "/admin.php?add-ons/"
  ["_GET"] => array(5) {
    ["install-upgrade/addOn/ThemeHouse-Donate/update"] => string(0) ""
    ["_xfRequestUri"] => string(19) "/admin.php?add-ons/"
    ["_xfWithData"] => string(1) "1"
    ["_xfToken"] => string(43) "1540917130,b641241db759ad8218680616c558b528"
    ["_xfResponseType"] => string(4) "json"
  }
  ["_POST"] => array(0) {
  }
}
````

**Comment by joyfreak** [comment]
In the add-on list > Donate > Upgrade > Error

**Comment by LukasWieditz** [comment]
I think this is from the same source as #1089
