### ISSUE TITLE
Unable to download zip from ThemeHouse. src/addons/ThemeHouse/InstallAndUpgrade/InstallAndUpgrade/ThemeHouse.php:191

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1089]
Server error log

````
Exception: Unable to download zip from ThemeHouse. src/addons/ThemeHouse/InstallAndUpgrade/InstallAndUpgrade/ThemeHouse.php:191 

Generated by: Nirjonadda Oct 30, 2018 at 10:32 PM 

Stack trace

#0 src/addons/ThemeHouse/InstallAndUpgrade/InstallAndUpgrade/ThemeHouse.php(233): ThemeHouse\InstallAndUpgrade\InstallAndUpgrade\ThemeHouse->downloadFile('/home/nminfo/pu...', 228, '1.0.4 Patch Lev...')
#1 src/addons/ThemeHouse/InstallAndUpgrade/InstallAndUpgrade/AbstractHandler.php(526): ThemeHouse\InstallAndUpgrade\InstallAndUpgrade\ThemeHouse->downloadAddOn(Object(ThemeHouse\InstallAndUpgrade\Entity\AddOn))
#2 src/addons/ThemeHouse/InstallAndUpgrade/Admin/Controller/InstallUpgrade.php(267): ThemeHouse\InstallAndUpgrade\InstallAndUpgrade\AbstractHandler->upgradeAddOn(Object(ThemeHouse\InstallAndUpgrade\Entity\AddOn))
#3 src/XF/Mvc/Dispatcher.php(249): ThemeHouse\InstallAndUpgrade\Admin\Controller\InstallUpgrade->actionUpdate(Object(XF\Mvc\ParameterBag))
#4 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Inst...', 'Update', 'json', Object(XF\Mvc\ParameterBag), '', Object(ThemeHouse\InstallAndUpgrade\Admin\Controller\InstallUpgrade), NULL)
#5 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#6 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#7 src/XF.php(329): XF\App->run()
#8 admin.php(13): XF::runApp('XF\\Admin\\App')
#9 {main}

Request state

array(4) {
  ["url"] => string(187) "/admin.php?install-upgrade/addOn/ThemeHouse-Donate/update&_xfRequestUri=%2Fadmin.php%3Fadd-ons%2F&_xfWithData=1&_xfToken=1540917130%2Cb641241db759ad8218680616c558b528&_xfResponseType=json"
  ["referrer"] => string(42) "/admin.php?add-ons/"
  ["_GET"] => array(5) {
    ["install-upgrade/addOn/ThemeHouse-Donate/update"] => string(0) ""
    ["_xfRequestUri"] => string(19) "/admin.php?add-ons/"
    ["_xfWithData"] => string(1) "1"
    ["_xfToken"] => string(43) "1540917130,b641241db759ad8218680616c558b528"
    ["_xfResponseType"] => string(4) "json"
  }
  ["_POST"] => array(0) {
  }
}
````

**Comment by LukasWieditz** [comment]
We had a broken/empty download up for a bit on ThemeHouse. Our educated guess is, that the error was triggered from that, so it should probably have sorted itself out when we reuploaded the file properly.
