### ISSUE TITLE
[TH] Install & Upgrade - Call to undefined method XF\Mvc\Reply\Error::setParam()

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1115]
Server error log.

````
Error: Call to undefined method XF\Mvc\Reply\Error::setParam() src/addons/ThemeHouse/InstallAndUpgrade/XF/Admin/Controller/AddOn.php:113 

Generated by: Nirjonmela Nov 2, 2018 at 11:32 PM 

Stack trace

#0 src/XF/Mvc/Dispatcher.php(249): ThemeHouse\InstallAndUpgrade\XF\Admin\Controller\AddOn->actionInstall(Object(XF\Mvc\ParameterBag))
#1 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('XF:AddOn', 'Install', 'json', Object(XF\Mvc\ParameterBag), 'listAddOns', Object(ThemeHouse\InstallAndUpgrade\XF\Admin\Controller\AddOn), NULL)
#2 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#3 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#4 src/XF.php(329): XF\App->run()
#5 admin.php(13): XF::runApp('XF\\Admin\\App')
#6 {main}

Request state

array(4) {
  ["url"] => string(200) "/admin.php?add-ons/ThemeHouse-UIXPro/install&_xfRequestUri=%2Fadmin.php%3Finstall-upgrade-products%2Favailable&_xfWithData=1&_xfToken=1541179940%2C328fb727ae88e1d887a01aa6d1ecee6f&_xfResponseType=json"
  ["referrer"] => string(67) "/admin.php?install-upgrade-products/available"
  ["_GET"] => array(5) {
    ["add-ons/ThemeHouse-UIXPro/install"] => string(0) ""
    ["_xfRequestUri"] => string(45) "/admin.php?install-upgrade-products/available"
    ["_xfWithData"] => string(1) "1"
    ["_xfToken"] => string(43) "1541179940,328fb727ae88e1d887a01aa6d1ecee6f"
    ["_xfResponseType"] => string(4) "json"
  }
  ["_POST"] => array(0) {
  }
}
````

**Comment by LukasWieditz** [comment]
Fixed
