### ISSUE TITLE
[Donate] [E_NOTICE] Trying to get property 'amount' of non-object

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1151]
Server error log.

````
ErrorException: [E_NOTICE] Trying to get property 'amount' of non-object src/addons/ThemeHouse/Donate/Purchasable/Campaign.php:236 

Generated by: Unknown account Nov 20, 2018 at 11:00 AM 

Stack trace

#0 src/addons/ThemeHouse/Donate/Purchasable/Campaign.php(236): XF::handlePhpError(8, '[E_NOTICE] Tryi...', '/home/nadda/pub...', 236, Array)
#1 src/XF/Payment/AbstractProvider.php(176): ThemeHouse\Donate\Purchasable\Campaign->completePurchase(Object(XF\Payment\CallbackState))
#2 payment_callback.php(62): XF\Payment\AbstractProvider->completeTransaction(Object(XF\Payment\CallbackState))
#3 {main}

Request state

array(4) {
  ["url"] => string(40) "/payment_callback.php?_xfProvider=paypal"
  ["referrer"] => bool(false)
  ["_GET"] => array(1) {
    ["_xfProvider"] => string(6) "paypal"
  }
  ["_POST"] => array(35) {
    ["mc_gross"] => string(4) "4.48"
    ["protection_eligibility"] => string(8) "Eligible"
    ["payer_id"] => string(13) "XXXXXXXXXXXXX"
    ["address_street"] => string(17) "XXXXXXXXXXXXXXXXX"
    ["payment_date"] => string(25) "06:40:00 Nov 18, 2018 PST"
    ["payment_status"] => string(17) "Canceled_Reversal"
    ["charset"] => string(12) "windows-1252"
    ["address_zip"] => string(6) "XXXXXXX"
    ["first_name"] => string(3) "XXX"
    ["mc_fee"] => string(4) "0.52"
    ["address_country_code"] => string(2) "XX"
    ["address_name"] => string(12) "XXXXXXXXXXXXX"
    ["notify_version"] => string(3) "3.9"
    ["reason_code"] => string(15) "buyer_complaint"
    ["subscr_id"] => string(14) "I-3ADEEPMTS67W"
    ["custom"] => string(32) "LtPCe79y451qvNr-gpOw-suT8mxrx7Dp"
    ["business"] => string(20) "XXXXXXXXXXXXXXXXXXXX"
    ["address_country"] => string(14) "XXXXXXXXXXXXXX"
    ["address_city"] => string(6) "XXXXXX"
    ["verify_sign"] => string(56) "ArTI4vPIfhK97TpVnRzunxLjnZiQAKCWm1IOkMqEj83WK5-ikzclOlz7"
    ["payer_email"] => string(18) "XXXXXXXXXXXXXXXXXXX"
    ["parent_txn_id"] => string(17) "8T659445B59292419"
    ["txn_id"] => string(17) "6HA383649X5932203"
    ["payment_type"] => string(7) "instant"
    ["last_name"] => string(6) "XXXXXXX"
    ["address_state"] => string(0) ""
    ["receiver_email"] => string(20) "XXXXXXXXXXXXXXXXXXXX"
    ["payment_fee"] => string(0) ""
    ["receiver_id"] => string(13) "SD8A5UCFXMGJS"
    ["item_name"] => string(51) "Donation Campaign: Donate to Nirjonmela! (XXXXXXXX)"
    ["mc_currency"] => string(3) "XXX"
    ["residence_country"] => string(2) "XX"
    ["transaction_subject"] => string(51) "Donation Campaign: Donate to Nirjonmela! (XXXXXXXX)"
    ["payment_gross"] => string(0) ""
    ["ipn_track_id"] => string(13) "68f600847d641"
  }
}
````

**Comment by jonw316** [comment]
Please be careful about posting users' sensitive data. I see you took the time to remove your own personal information but left in your user's data.

**Comment by Nirjonadda** [comment]
Sorry, I have seen this after the post. Edit history still can see this, so not edited get.

**Comment by jonw316** [comment]
I deleted the history.
