### ISSUE TITLE
[TH] Donate and Reaction error

### ISSUE THREAD

**Issue by teamracing** [Audentio/xf2addon-issues#1209]
Error: Call to undefined method ThemeHouse\Donate\Entity\Campaign::canView() src/addons/ThemeHouse/Reactions/React/AbstractHandler.php:368
Generated by: Unknown account Nov 29, 2018 at 8:41 PM
Stack trace
#0 src/addons/ThemeHouse/Reactions/Entity/ReactedContent.php(140): ThemeHouse\Reactions\React\AbstractHandler->render(Object(ThemeHouse\Reactions\Entity\ReactedContent))
#1 [internal function]: ThemeHouse\Reactions\Entity\ReactedContent->render()
#2 src/XF/Template/Templater.php(940): call_user_func_array(Array, Array)
#3 internal_data/code_cache/templates/l1/s7/public/threact_member_reactions.php(59): XF\Template\Templater->method(Object(ThemeHouse\Reactions\Entity\ReactedContent), 'render', Array)
#4 src/XF/Template/Templater.php(1250): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array)
#5 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('threact_member_...', Array)
#6 src/XF/Mvc/Renderer/Html.php(48): XF\Template\Template->render()
#7 src/XF/Mvc/Dispatcher.php(332): XF\Mvc\Renderer\Html->renderView('ThemeHouse\\Reac...', 'public:threact_...', Array)
#8 src/XF/Mvc/Dispatcher.php(303): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#9 src/XF/Mvc/Dispatcher.php(44): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#10 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#11 src/XF.php(329): XF\App->run()
#12 index.php(13): XF::runApp('XF\\Pub\\App')
#13 {main}

array(4) {
  ["url"] => string(57) "/members/nik.1/reactions?reaction_id=2&type=given&page=31"
  ["referrer"] => bool(false)
  ["_GET"] => array(4) {
    ["/members/nik_1/reactions"] => string(0) ""
    ["reaction_id"] => string(1) "2"
    ["type"] => string(5) "given"
    ["page"] => string(2) "31"
  }
  ["_POST"] => array(0) {
  }
}

**Comment by teamracing** [comment]
Donate 1.0.4 Patch Level 1
Reactions 1.0.13 Patch Level 4

@jonw316
