### ISSUE TITLE
[TH] Spotify - cURL error 7: Failed to connect to api.spotify.com

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1272]
Getting lot of Server error log.

````
GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to api.spotify.com port 443: Connection timed out src/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:49 

Generated by: Nirjonmela Dec 18, 2018 at 3:48 PM 

Stack trace

#0 src/vendor/guzzlehttp/guzzle/src/RequestFsm.php(103): GuzzleHttp\Exception\RequestException::wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\ConnectException))
#1 src/vendor/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#2 src/vendor/react/promise/src/FulfilledPromise.php(25): GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
#3 src/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#4 src/vendor/guzzlehttp/guzzle/src/Message/FutureResponse.php(43): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#5 src/vendor/guzzlehttp/guzzle/src/RequestFsm.php(134): GuzzleHttp\Message\FutureResponse::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#6 src/vendor/guzzlehttp/guzzle/src/Client.php(165): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#7 src/addons/ThemeHouse/Spotify/Util/Spotify/AbstractSpotify.php(120): GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
#8 src/addons/ThemeHouse/Spotify/Util/Spotify/Player.php(9): ThemeHouse\Spotify\Util\Spotify\AbstractSpotify->request('me/player')
#9 src/addons/ThemeHouse/Spotify/Service/Player/UpdatePlayback.php(36): ThemeHouse\Spotify\Util\Spotify\Player->getCurrentPlayback()
#10 src/addons/ThemeHouse/Spotify/Pub/Controller/Spotify.php(41): ThemeHouse\Spotify\Service\Player\UpdatePlayback->updateCurrentPlayback()
#11 src/XF/Mvc/Dispatcher.php(249): ThemeHouse\Spotify\Pub\Controller\Spotify->actionUpdateCurrentPlayback(Object(XF\Mvc\ParameterBag))
#12 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Spot...', 'UpdateCurrentPl...', 'json', Object(XF\Mvc\ParameterBag), '', Object(ThemeHouse\Spotify\Pub\Controller\Spotify), NULL)
#13 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#14 src/XF/App.php(1934): XF\Mvc\Dispatcher->run()
#15 src/XF.php(333): XF\App->run()
#16 index.php(13): XF::runApp('XF\\Pub\\App')
#17 {main}

-------------

Previous GuzzleHttp\Ring\Exception\ConnectException: cURL error 7: Failed to connect to api.spotify.com port 443: Connection timed out - src/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php:126
#0 src/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php(91): GuzzleHttp\Ring\Client\CurlFactory::createErrorResponse(Array, Array, Array)
#1 src/vendor/guzzlehttp/ringphp/src/Client/CurlHandler.php(96): GuzzleHttp\Ring\Client\CurlFactory::createResponse(Array, Array, Array, Array, Resource id #275)
#2 src/vendor/guzzlehttp/ringphp/src/Client/CurlHandler.php(68): GuzzleHttp\Ring\Client\CurlHandler->_invokeAsArray(Array)
#3 src/vendor/guzzlehttp/ringphp/src/Client/Middleware.php(54): GuzzleHttp\Ring\Client\CurlHandler->__invoke(Array)
#4 src/vendor/guzzlehttp/ringphp/src/Client/Middleware.php(30): GuzzleHttp\Ring\Client\Middleware::GuzzleHttp\Ring\Client\{closure}(Array)
#5 src/vendor/guzzlehttp/guzzle/src/RequestFsm.php(129): GuzzleHttp\Ring\Client\Middleware::GuzzleHttp\Ring\Client\{closure}(Array)
#6 src/vendor/guzzlehttp/guzzle/src/Client.php(165): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#7 src/addons/ThemeHouse/Spotify/Util/Spotify/AbstractSpotify.php(120): GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
#8 src/addons/ThemeHouse/Spotify/Util/Spotify/Player.php(9): ThemeHouse\Spotify\Util\Spotify\AbstractSpotify->request('me/player')
#9 src/addons/ThemeHouse/Spotify/Service/Player/UpdatePlayback.php(36): ThemeHouse\Spotify\Util\Spotify\Player->getCurrentPlayback()
#10 src/addons/ThemeHouse/Spotify/Pub/Controller/Spotify.php(41): ThemeHouse\Spotify\Service\Player\UpdatePlayback->updateCurrentPlayback()
#11 src/XF/Mvc/Dispatcher.php(249): ThemeHouse\Spotify\Pub\Controller\Spotify->actionUpdateCurrentPlayback(Object(XF\Mvc\ParameterBag))
#12 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Spot...', 'UpdateCurrentPl...', 'json', Object(XF\Mvc\ParameterBag), '', Object(ThemeHouse\Spotify\Pub\Controller\Spotify), NULL)
#13 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#14 src/XF/App.php(1934): XF\Mvc\Dispatcher->run()
#15 src/XF.php(333): XF\App->run()
#16 index.php(13): XF::runApp('XF\\Pub\\App')
#17 {main}

Request state

array(4) {
  ["url"] => string(150) "/index.php?spotify/update-current-playback&_xfRequestUri=%2F&_xfWithData=1&_xfToken=1545125641%2Cb33c1e755dc57868a16fa82c91ea83ae&_xfResponseType=json"
  ["referrer"] => string(23) "/"
  ["_GET"] => array(5) {
    ["spotify/update-current-playback"] => string(0) ""
    ["_xfRequestUri"] => string(1) "/"
    ["_xfWithData"] => string(1) "1"
    ["_xfToken"] => string(43) "1545125641,b33c1e755dc57868a16fa82c91ea83ae"
    ["_xfResponseType"] => string(4) "json"
  }
  ["_POST"] => array(0) {
  }
}
````

**Comment by jonw316** [comment]
This is either a problem with their API or a problem with your server.

When XenForo is unable to connect to it's servers to check for updates, for example, or when it tries to connect to Google to send sitemap data, and it is unable to, it also adds to the server error log, so this treatment is correct.
