### ISSUE TITLE
 [TH] Topics - Error: Call to undefined method ThemeHouse\Topics\ThemeHouse\Trending\Trending\Thread::options()

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1287]
Lot of Server error log happened after updated to 1.0.2 bata 1

````
Error: Call to undefined method ThemeHouse\Topics\ThemeHouse\Trending\Trending\Thread::options() src/addons/ThemeHouse/Topics/ThemeHouse/Trending/Trending/Thread.php:11 

Generated by: sumon Dec 21, 2018 at 4:37 PM 

Stack trace

#0 src/addons/ThemeHouse/Trending/Trending/Thread.php(147): ThemeHouse\Topics\ThemeHouse\Trending\Trending\Thread->applyFinderFilters(Object(SV\RedisCache\XF\Finder\Thread))
#1 src/addons/ThemeHouse/Trending/Trending/AbstractHandler.php(118): ThemeHouse\Trending\Trending\Thread->_renderTrendingContent(Object(ThemeHouse\Trending\Entity\Trending))
#2 src/addons/ThemeHouse/Trending/Entity/Trending.php(84): ThemeHouse\Trending\Trending\AbstractHandler->renderTrendingContent(Object(ThemeHouse\Trending\Entity\Trending))
#3 [internal function]: ThemeHouse\Trending\Entity\Trending->renderTrendingContent()
#4 src/XF/Template/Templater.php(940): call_user_func_array(Array, Array)
#5 internal_data/code_cache/templates/l1/s10/public/thtrending_trending_view.php(77): XF\Template\Templater->method(Object(ThemeHouse\Trending\Entity\Trending), 'renderTrendingC...', Array)
#6 src/XF/Template/Templater.php(1250): XF\Template\Templater->{closure}(Object(xenMade\LAU\XF\Template\Templater), Array)
#7 src/addons/AddonsLab/LinkChecker/XF/Template/Templater.php(89): XF\Template\Templater->renderTemplate('thtrending_tren...', Array, true)
#8 src/XF/Template/Template.php(24): AddonsLab\LinkChecker\XF\Template\Templater->renderTemplate('public:thtrendi...', Array)
#9 src/XF/Mvc/Renderer/Html.php(48): XF\Template\Template->render()
#10 src/XF/Mvc/Dispatcher.php(332): XF\Mvc\Renderer\Html->renderView('ThemeHouse\\Tren...', 'public:thtrendi...', Array)
#11 src/XF/Mvc/Dispatcher.php(303): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#12 src/XF/Mvc/Dispatcher.php(44): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#13 src/XF/App.php(1934): XF\Mvc\Dispatcher->run()
#14 src/XF.php(333): XF\App->run()
#15 index.php(13): XF::runApp('XF\\Pub\\App')
#16 {main}

Request state

array(4) {
  ["url"] => string(20) "/trending/threads.1/"
  ["referrer"] => string(23) "/"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}
````

**Comment by Nirjonadda** [comment]
Oh /trending page no more working, Please can be upload hot fix beta 2?

![screenshot00850](https://user-images.githubusercontent.com/6899856/50341159-1ae6c580-051e-11e9-9eb8-98a5417aebac.png)

**Comment by jonw316** [comment]
On its way...
