### ISSUE TITLE
[TH] Spotify - Error: Class 'ThemeHouse\Core\Http\HttpClient' not found

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1294]
Server error log and can not use forum. Need fix this asap because from are broken.

![screenshot00853](https://user-images.githubusercontent.com/6899856/50352950-01a63f00-0547-11e9-8415-ac5dba7020a6.png)

````
Error: Class 'ThemeHouse\Core\Http\HttpClient' not found src/addons/ThemeHouse/Spotify/Util/Spotify/AbstractSpotify.php:110 

Generated by: Nirjonmela Dec 21, 2018 at 10:34 PM 

Stack trace

#0 src/addons/ThemeHouse/Spotify/Util/Spotify/Player.php(9): ThemeHouse\Spotify\Util\Spotify\AbstractSpotify->request('me/player')
#1 src/addons/ThemeHouse/Spotify/Service/Player/UpdatePlayback.php(36): ThemeHouse\Spotify\Util\Spotify\Player->getCurrentPlayback()
#2 src/addons/ThemeHouse/Spotify/Pub/Controller/Spotify.php(41): ThemeHouse\Spotify\Service\Player\UpdatePlayback->updateCurrentPlayback()
#3 src/XF/Mvc/Dispatcher.php(249): ThemeHouse\Spotify\Pub\Controller\Spotify->actionUpdateCurrentPlayback(Object(XF\Mvc\ParameterBag))
#4 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Spot...', 'UpdateCurrentPl...', 'json', Object(XF\Mvc\ParameterBag), '', Object(ThemeHouse\Spotify\Pub\Controller\Spotify), NULL)
#5 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#6 src/XF/App.php(1934): XF\Mvc\Dispatcher->run()
#7 src/XF.php(333): XF\App->run()
#8 index.php(13): XF::runApp('XF\\Pub\\App')
#9 {main}

Request state

array(4) {
  ["url"] => string(159) "/index.php?spotify/update-current-playback&_xfRequestUri=%2Fadmin.php&_xfWithData=1&_xfToken=1545410079%2C74f56b7ed4fa5bae834bc4d3b8a72abd&_xfResponseType=json"
  ["referrer"] => string(32) "/admin.php"
  ["_GET"] => array(5) {
    ["spotify/update-current-playback"] => string(0) ""
    ["_xfRequestUri"] => string(10) "/admin.php"
    ["_xfWithData"] => string(1) "1"
    ["_xfToken"] => string(43) "1545410079,74f56b7ed4fa5bae834bc4d3b8a72abd"
    ["_xfResponseType"] => string(4) "json"
  }
  ["_POST"] => array(0) {
  }
}
````

**Comment by JakeBooher** [comment]
If you already ran the upgrade process when you initially uploaded the new version there isn't anything extra for you to do after those missing files have been uploaded
