### ISSUE TITLE
[TH] Reactions - MySQL query error [1213]: Deadlock found when trying to get lock

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1308]
Getting Server error log.

````
XF\Db\DeadlockException: MySQL query error [1213]: Deadlock found when trying to get lock; try restarting transaction src/XF/Db/AbstractStatement.php:212 

Generated by: youknow007 Dec 26, 2018 at 7:38 PM 

Stack trace

			UPDATE xf_user
			SET react_count = ?
			WHERE user_id = ?
		
------------

#0 src/XF/Db/Mysqli/Statement.php(196): XF\Db\AbstractStatement->getException('MySQL query err...', 1213, '40001')
#1 src/XF/Db/Mysqli/Statement.php(77): XF\Db\Mysqli\Statement->getException('MySQL query err...', 1213, '40001')
#2 src/XF/Db/AbstractAdapter.php(79): XF\Db\Mysqli\Statement->execute()
#3 src/addons/ThemeHouse/Reactions/Entity/ReactedContent.php(286): XF\Db\AbstractAdapter->query('
			UPDATE xf_u...', Array)
#4 src/addons/ThemeHouse/Reactions/Entity/ReactedContent.php(233): ThemeHouse\Reactions\Entity\ReactedContent->adjustUserReactCount(2, 1)
#5 src/addons/ThemeHouse/Reactions/Entity/ReactedContent.php(147): ThemeHouse\Reactions\Entity\ReactedContent->adjustReactCount(3580, 332, 2, 5049, 'post', 1)
#6 src/XF/Mvc/Entity/Entity.php(1165): ThemeHouse\Reactions\Entity\ReactedContent->_postSave()
#7 src/addons/ThemeHouse/Reactions/Repository/ReactedContent.php(104): XF\Mvc\Entity\Entity->save()
#8 src/addons/ThemeHouse/Reactions/ControllerPlugin/React.php(29): ThemeHouse\Reactions\Repository\ReactedContent->insertReact(Object(SV\ChangePostDate\XF\Entity\Post), Object(ThemeHouse\Reactions\Entity\ReactedContent))
#9 src/addons/ThemeHouse/Reactions/Pub/Controller/React.php(61): ThemeHouse\Reactions\ControllerPlugin\React->actionToggleReact(Object(SV\ChangePostDate\XF\Entity\Post), Object(ThemeHouse\Reactions\Entity\ReactedContent), 'insert')
#10 src/XF/Mvc/Dispatcher.php(249): ThemeHouse\Reactions\Pub\Controller\React->actionReact(Object(XF\Mvc\ParameterBag))
#11 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Reac...', 'React', 'json', Object(XF\Mvc\ParameterBag), 'reactions', Object(ThemeHouse\Reactions\Pub\Controller\React), NULL)
#12 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#13 src/XF/App.php(1934): XF\Mvc\Dispatcher->run()
#14 src/XF.php(333): XF\App->run()
#15 index.php(13): XF::runApp('XF\\Pub\\App')
#16 {main}

Request state

array(4) {
  ["url"] => string(28) "/reactions/react/post/5049/2"
  ["referrer"] => string(41) "/threads/314/page-2"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(4) {
    ["_xfRequestUri"] => string(19) "/threads/314/page-2"
    ["_xfWithData"] => string(1) "1"
    ["_xfToken"] => string(8) "********"
    ["_xfResponseType"] => string(4) "json"
  }
}
````

**Comment by JakeBooher** [comment]
Did this only happen once, or has it been a recurring thing?

**Comment by Nirjonadda** [comment]
This happen some time, not once.

**Comment by LukasWieditz** [comment]
No longer relevant, as the system is now native
