### ISSUE TITLE
[TH] Image Optimizer - Rebuild caches Optimize images

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1339]
Rebuild caches > Optimize images > Content type > ALL - Server error logs

````
InvalidArgumentException: Attempted to convert NULL to string/binary [file_mime] src/XF/Mvc/Entity/Entity.php:740 

Generated by: Nirjonadda Jan 8, 2019 at 11:54 PM 

Stack trace

#0 src/XF/Mvc/Entity/Entity.php(694): XF\Mvc\Entity\Entity->_castValueToType(NULL, 'file_mime', 5, Array)
#1 src/XF/Mvc/Entity/Entity.php(1285): XF\Mvc\Entity\Entity->setAsSaved('file_mime', NULL)
#2 src/addons/ThemeHouse/ImageOptimizer/Service/ImageOptimizer/Optimize.php(84): XF\Mvc\Entity\Entity->fastUpdate('file_mime', NULL)
#3 src/addons/ThemeHouse/ImageOptimizer/Service/ImageOptimizer/Optimize.php(31): ThemeHouse\ImageOptimizer\Service\ImageOptimizer\Optimize->updateStatusFileType()
#4 src/addons/ThemeHouse/ImageOptimizer/ContentHandler/AbstractHandler.php(51): ThemeHouse\ImageOptimizer\Service\ImageOptimizer\Optimize->run()
#5 src/addons/ThemeHouse/ImageOptimizer/ContentHandler/AbstractHandler.php(143): ThemeHouse\ImageOptimizer\ContentHandler\AbstractHandler->optimize(Object(ThemeHouse\ImageOptimizer\Entity\Status))
#6 src/addons/ThemeHouse/ImageOptimizer/ImageOptimizer.php(103): ThemeHouse\ImageOptimizer\ContentHandler\AbstractHandler->createStatusAndOptimize(Object(ThemeHouse\ImageOptimizer\XF\Entity\AttachmentData))
#7 src/addons/ThemeHouse/ImageOptimizer/ImageOptimizer.php(96): ThemeHouse\ImageOptimizer\ImageOptimizer->optimizeEntity('attachment', Object(ThemeHouse\ImageOptimizer\XF\Entity\AttachmentData))
#8 src/addons/ThemeHouse/ImageOptimizer/ImageOptimizer.php(86): ThemeHouse\ImageOptimizer\ImageOptimizer->optimizeEntities('attachment', Object(XF\Mvc\Entity\ArrayCollection))
#9 src/addons/ThemeHouse/ImageOptimizer/Job/ImageOptimizer.php(48): ThemeHouse\ImageOptimizer\ImageOptimizer->optimizeRange('attachment', 0, '1')
#10 src/XF/Job/Manager.php(253): ThemeHouse\ImageOptimizer\Job\ImageOptimizer->run(G)
#11 src/XF/Job/Manager.php(195): XF\Job\Manager->runJobInternal(Array, G)
#12 src/XF/Job/Manager.php(111): XF\Job\Manager->runJobEntry(Array, G)
#13 src/XF/Admin/Controller/Tools.php(120): XF\Job\Manager->runByIds(Array, 8)
#14 src/XF/Mvc/Dispatcher.php(321): XF\Admin\Controller\Tools->actionRunJob(Object(XF\Mvc\ParameterBag))
#15 src/XF/Mvc/Dispatcher.php(248): XF\Mvc\Dispatcher->dispatchClass('XF:Tools', 'RunJob', Object(XF\Mvc\RouteMatch), Object(XF\Admin\Controller\Tools), NULL)
#16 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(XF\Admin\Controller\Tools), NULL)
#17 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#18 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#19 src/XF.php(392): XF\App->run()
#20 admin.php(13): XF::runApp('XF\\Admin\\App')
#21 {main}

-------------

Previous InvalidArgumentException: Attempted to convert NULL to string/binary - src/XF/Mvc/Entity/ValueFormatter.php:130
#0 src/XF/Mvc/Entity/Entity.php(736): XF\Mvc\Entity\ValueFormatter->castValueToType(NULL, 5, Array)
#1 src/XF/Mvc/Entity/Entity.php(694): XF\Mvc\Entity\Entity->_castValueToType(NULL, 'file_mime', 5, Array)
#2 src/XF/Mvc/Entity/Entity.php(1285): XF\Mvc\Entity\Entity->setAsSaved('file_mime', NULL)
#3 src/addons/ThemeHouse/ImageOptimizer/Service/ImageOptimizer/Optimize.php(84): XF\Mvc\Entity\Entity->fastUpdate('file_mime', NULL)
#4 src/addons/ThemeHouse/ImageOptimizer/Service/ImageOptimizer/Optimize.php(31): ThemeHouse\ImageOptimizer\Service\ImageOptimizer\Optimize->updateStatusFileType()
#5 src/addons/ThemeHouse/ImageOptimizer/ContentHandler/AbstractHandler.php(51): ThemeHouse\ImageOptimizer\Service\ImageOptimizer\Optimize->run()
#6 src/addons/ThemeHouse/ImageOptimizer/ContentHandler/AbstractHandler.php(143): ThemeHouse\ImageOptimizer\ContentHandler\AbstractHandler->optimize(Object(ThemeHouse\ImageOptimizer\Entity\Status))
#7 src/addons/ThemeHouse/ImageOptimizer/ImageOptimizer.php(103): ThemeHouse\ImageOptimizer\ContentHandler\AbstractHandler->createStatusAndOptimize(Object(ThemeHouse\ImageOptimizer\XF\Entity\AttachmentData))
#8 src/addons/ThemeHouse/ImageOptimizer/ImageOptimizer.php(96): ThemeHouse\ImageOptimizer\ImageOptimizer->optimizeEntity('attachment', Object(ThemeHouse\ImageOptimizer\XF\Entity\AttachmentData))
#9 src/addons/ThemeHouse/ImageOptimizer/ImageOptimizer.php(86): ThemeHouse\ImageOptimizer\ImageOptimizer->optimizeEntities('attachment', Object(XF\Mvc\Entity\ArrayCollection))
#10 src/addons/ThemeHouse/ImageOptimizer/Job/ImageOptimizer.php(48): ThemeHouse\ImageOptimizer\ImageOptimizer->optimizeRange('attachment', 0, '1')
#11 src/XF/Job/Manager.php(253): ThemeHouse\ImageOptimizer\Job\ImageOptimizer->run(G)
#12 src/XF/Job/Manager.php(195): XF\Job\Manager->runJobInternal(Array, G)
#13 src/XF/Job/Manager.php(111): XF\Job\Manager->runJobEntry(Array, G)
#14 src/XF/Admin/Controller/Tools.php(120): XF\Job\Manager->runByIds(Array, 8)
#15 src/XF/Mvc/Dispatcher.php(321): XF\Admin\Controller\Tools->actionRunJob(Object(XF\Mvc\ParameterBag))
#16 src/XF/Mvc/Dispatcher.php(248): XF\Mvc\Dispatcher->dispatchClass('XF:Tools', 'RunJob', Object(XF\Mvc\RouteMatch), Object(XF\Admin\Controller\Tools), NULL)
#17 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(XF\Admin\Controller\Tools), NULL)
#18 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#19 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#20 src/XF.php(392): XF\App->run()
#21 admin.php(13): XF::runApp('XF\\Admin\\App')
#22 {main}

Request state

array(4) {
  ["url"] => string(24) "/admin.php?tools/run-job"
  ["referrer"] => string(116) "/admin.php?tools/run-job&only_id=221&_xfRedirect=%2Fadmin.php%3Ftools%2Frebuild%26success%3D1"
  ["_GET"] => array(1) {
    ["tools/run-job"] => string(0) ""
  }
  ["_POST"] => array(3) {
    ["_xfRedirect"] => string(57) "/admin.php?tools/rebuild&success=1"
    ["_xfToken"] => string(8) "********"
    ["only_ids"] => string(3) "221"
  }
}
````

**Comment by Nirjonadda** [comment]
@JakeBooher This does not Install & Upgrade add-on issue?
