### ISSUE TITLE
 [TH] Image Optimizer - Unable to determine file MIME type for status ID

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1366]
Server error logs.

````
ErrorException: Unable to determine file MIME type for status ID 3 src/XF/Error.php:75 

Generated by: Black Knight Jan 16, 2019 at 2:51 AM 

Stack trace

#0 src/XF.php(166): XF\Error->logError('Unable to deter...', false)
#1 src/addons/ThemeHouse/ImageOptimizer/Service/ImageOptimizer/Optimize.php(32): XF::logError('Unable to deter...')
#2 src/addons/ThemeHouse/ImageOptimizer/ContentHandler/AbstractHandler.php(57): ThemeHouse\ImageOptimizer\Service\ImageOptimizer\Optimize->run()
#3 src/addons/ThemeHouse/ImageOptimizer/ContentHandler/AbstractHandler.php(156): ThemeHouse\ImageOptimizer\ContentHandler\AbstractHandler->optimize(Object(ThemeHouse\ImageOptimizer\Entity\Status))
#4 src/addons/ThemeHouse/ImageOptimizer/ImageOptimizer.php(103): ThemeHouse\ImageOptimizer\ContentHandler\AbstractHandler->createStatusAndOptimize(Object(Datio\AllowedEmails\XF\Entity\User))
#5 src/addons/ThemeHouse/ImageOptimizer/ImageOptimizer.php(34): ThemeHouse\ImageOptimizer\ImageOptimizer->optimizeEntity('th_imageoptimiz...', Object(Datio\AllowedEmails\XF\Entity\User))
#6 src/addons/ThemeHouse/ImageOptimizer/XF/Service/User/Avatar.php(21): ThemeHouse\ImageOptimizer\ImageOptimizer::optimize('th_imageoptimiz...', Object(Datio\AllowedEmails\XF\Entity\User))
#7 src/XF/Pub/Controller/Account.php(456): ThemeHouse\ImageOptimizer\XF\Service\User\Avatar->updateAvatar()
#8 src/XF/Mvc/Dispatcher.php(249): XF\Pub\Controller\Account->actionAvatar(Object(XF\Mvc\ParameterBag))
#9 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('XF:Account', 'Avatar', 'json', Object(XF\Mvc\ParameterBag), 'account', Object(AddonFlare\PaidRegistrations\XF\Pub\Controller\Account), NULL)
#10 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#11 src/XF/App.php(1934): XF\Mvc\Dispatcher->run()
#12 src/XF.php(333): XF\App->run()
#13 index.php(13): XF::runApp('XF\\Pub\\App')
#14 {main}

Request state

array(4) {
  ["url"] => string(15) "/account/avatar"
  ["referrer"] => string(48) "/members/black-knight.298/"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(7) {
    ["avatar_crop_x"] => string(1) "0"
    ["avatar_crop_y"] => string(17) "16.72072072072072"
    ["use_custom"] => string(1) "1"
    ["_xfToken"] => string(8) "********"
    ["_xfRequestUri"] => string(26) "/members/black-knight.298/"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}
````

````
ErrorException: Unable to determine file MIME type for status ID 1 src/XF/Error.php:75 

Generated by: Unknown account Jan 16, 2019 at 1:32 AM 

Stack trace

#0 src/XF.php(166): XF\Error->logError('Unable to deter...', false)
#1 src/addons/ThemeHouse/ImageOptimizer/Service/ImageOptimizer/Optimize.php(32): XF::logError('Unable to deter...')
#2 src/addons/ThemeHouse/ImageOptimizer/ContentHandler/AbstractHandler.php(57): ThemeHouse\ImageOptimizer\Service\ImageOptimizer\Optimize->run()
#3 src/addons/ThemeHouse/ImageOptimizer/ContentHandler/AbstractHandler.php(156): ThemeHouse\ImageOptimizer\ContentHandler\AbstractHandler->optimize(Object(ThemeHouse\ImageOptimizer\Entity\Status))
#4 src/addons/ThemeHouse/ImageOptimizer/ImageOptimizer.php(103): ThemeHouse\ImageOptimizer\ContentHandler\AbstractHandler->createStatusAndOptimize(Object(Datio\AllowedEmails\XF\Entity\User))
#5 src/addons/ThemeHouse/ImageOptimizer/ImageOptimizer.php(34): ThemeHouse\ImageOptimizer\ImageOptimizer->optimizeEntity('th_imageoptimiz...', Object(Datio\AllowedEmails\XF\Entity\User))
#6 src/addons/ThemeHouse/ImageOptimizer/XF/Service/User/Avatar.php(21): ThemeHouse\ImageOptimizer\ImageOptimizer::optimize('th_imageoptimiz...', Object(Datio\AllowedEmails\XF\Entity\User))
#7 src/XF/Service/User/Registration.php(394): ThemeHouse\ImageOptimizer\XF\Service\User\Avatar->updateAvatar()
#8 src/XF/Service/User/Registration.php(295): XF\Service\User\Registration->applyAvatarFromUrl('https://ct.yimg...')
#9 src/XF/Service/ValidateAndSavableTrait.php(40): XF\Service\User\Registration->_save()
#10 src/XF/Pub/Controller/Register.php(302): XF\Service\User\Registration->save()
#11 src/XF/Mvc/Dispatcher.php(249): XF\Pub\Controller\Register->actionConnectedAccountRegister(Object(XF\Mvc\ParameterBag))
#12 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('XF:Register', 'ConnectedAccoun...', 'json', Object(XF\Mvc\ParameterBag), '', Object(AddonFlare\PaidRegistrations\XF\Pub\Controller\Register), NULL)
#13 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#14 src/XF/App.php(1934): XF\Mvc\Dispatcher->run()
#15 src/XF.php(333): XF\App->run()
#16 index.php(13): XF::runApp('XF\\Pub\\App')
#17 {main}

Request state

array(4) {
  ["url"] => string(43) "/register/connected-accounts/yahoo/register"
  ["referrer"] => string(57) "/register/connected-accounts/yahoo/"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(15) {
    ["username"] => string(7) "Onlidin"
    ["email"] => string(20) "XXXXX@yahoo.com"
    ["dob_month"] => string(1) "1"
    ["dob_day"] => string(2) "01"
    ["dob_year"] => string(4) "1990"
    ["location"] => string(11) "Bangladesh "
    ["custom_fields"] => array(2) {
      ["gender"] => string(4) "male"
      ["siropu_referrer"] => string(0) ""
    }
    ["accept"] => string(1) "1"
    ["_xfRedirect"] => string(23) "/"
    ["timezone"] => string(10) "Asia/Dhaka"
    ["_xfToken"] => string(8) "********"
    ["bb2_screener_"] => string(25) "1547580642 103.230.105.19"
    ["_xfRequestUri"] => string(35) "/register/connected-accounts/yahoo/"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}
````

**Comment by ichpen** [comment]
Can confirm that I'm receiving the above messaging for pretty much every image upload @JakeBooher
