### ISSUE TITLE
[Image Optimizer] Error received from reSmush for status ID

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1378]
Server error logs

````
ErrorException: [Image Optimizer] Error received from reSmush for status ID 1348: Unauthorized extension. Allowed are : JPG, PNG, GIF, BMP, TIFF src/XF/Error.php:75 

Generated by: Nirjonmela Jan 17, 2019 at 3:04 AM 

Stack trace

#0 src/XF.php(166): XF\Error->logError('[Image Optimize...', false)
#1 src/addons/ThemeHouse/ImageOptimizer/ImageOptimizer/ReSmush.php(92): XF::logError('[Image Optimize...')
#2 src/addons/ThemeHouse/ImageOptimizer/ImageOptimizer/ReSmush.php(77): ThemeHouse\ImageOptimizer\ImageOptimizer\ReSmush->reSmushFailedResponse(Object(ThemeHouse\ImageOptimizer\Service\ImageOptimizer\Optimize), '[Image Optimize...', true)
#3 src/addons/ThemeHouse/ImageOptimizer/Service/ImageOptimizer/Optimize.php(47): ThemeHouse\ImageOptimizer\ImageOptimizer\ReSmush->optimizeImage(Object(ThemeHouse\ImageOptimizer\Service\ImageOptimizer\Optimize))
#4 src/addons/ThemeHouse/ImageOptimizer/ContentHandler/AbstractHandler.php(57): ThemeHouse\ImageOptimizer\Service\ImageOptimizer\Optimize->run()
#5 src/addons/ThemeHouse/ImageOptimizer/ContentHandler/AbstractHandler.php(160): ThemeHouse\ImageOptimizer\ContentHandler\AbstractHandler->optimize(Object(ThemeHouse\ImageOptimizer\Entity\Status))
#6 src/addons/ThemeHouse/ImageOptimizer/ImageOptimizer.php(105): ThemeHouse\ImageOptimizer\ContentHandler\AbstractHandler->createStatusAndOptimize(Object(Datio\AllowedEmails\XF\Entity\User))
#7 src/addons/ThemeHouse/ImageOptimizer/ImageOptimizer.php(98): ThemeHouse\ImageOptimizer\ImageOptimizer->optimizeEntity('th_imageoptimiz...', Object(Datio\AllowedEmails\XF\Entity\User))
#8 src/addons/ThemeHouse/ImageOptimizer/ImageOptimizer.php(88): ThemeHouse\ImageOptimizer\ImageOptimizer->optimizeEntities('th_imageoptimiz...', Object(XF\Mvc\Entity\ArrayCollection))
#9 src/addons/ThemeHouse/ImageOptimizer/Job/ImageOptimizer.php(48): ThemeHouse\ImageOptimizer\ImageOptimizer->optimizeRange('th_imageoptimiz...', 4068, '1')
#10 src/XF/Job/Manager.php(241): ThemeHouse\ImageOptimizer\Job\ImageOptimizer->run(G)
#11 src/XF/Job/Manager.php(187): XF\Job\Manager->runJobInternal(Array, G)
#12 src/XF/Job/Manager.php(76): XF\Job\Manager->runJobEntry(Array, G)
#13 src/XF/Admin/Controller/Tools.php(139): XF\Job\Manager->runQueue(true, 8)
#14 src/XF/Mvc/Dispatcher.php(249): XF\Admin\Controller\Tools->actionRunJob(Object(XF\Mvc\ParameterBag))
#15 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('XF:Tools', 'RunJob', 'html', Object(XF\Mvc\ParameterBag), 'tools', Object(NF\Discord\XF\Admin\Controller\Tools), NULL)
#16 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#17 src/XF/App.php(1934): XF\Mvc\Dispatcher->run()
#18 src/XF.php(333): XF\App->run()
#19 admin.php(13): XF::runApp('XF\\Admin\\App')
#20 {main}

Request state

array(4) {
  ["url"] => string(24) "/admin.php?tools/run-job"
  ["referrer"] => string(46) "/admin.php?tools/run-job"
  ["_GET"] => array(1) {
    ["tools/run-job"] => string(0) ""
  }
  ["_POST"] => array(3) {
    ["_xfRedirect"] => string(32) "/admin.php"
    ["_xfToken"] => string(8) "********"
    ["only_ids"] => string(0) ""
  }
}
````

**Comment by JakeBooher** [comment]
Tried a few things to attempt to replicate this, but will need more information.

Please run the following query and get me the output:

```
select * from xf_th_imageoptimizer_status where status_id=1348;
```

**Comment by Nirjonadda** [comment]
@JakeBooher Missed notification from this post. So see the following query output.

![ScreenShot01013](https://user-images.githubusercontent.com/6899856/55817961-dcd5d780-5af5-11e9-9322-1ed236354982.png)
