### ISSUE TITLE
Reactions Plus (XF 2.1) - TH Reactions Import Failure

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2addon-issues#1465]
Add-on Name: Reactions Plus

Add-on Version: Beta 2

XenForo Version: 2.1

Summary of issue: Had latest proper update for TH Reactions for XF 2.0 installed first. Then updated site to XF 2.1. Flawless. Then disabled TH Reactions, and installed Beta 2 of the Reactions Plus add-on. Went to import 2.0 reactions to my site, and got two error messages (the CLI one was attempted first, the browser-based version was attempted second). Not sure if the screenshots will display in proper order.

I think with imports, you're going to have to give a detailed step by step.. Do you remove the existing ones that are pre-installed with Reactions Plus? What to do if you are bringing over "Like" when there is a "Like" by default, etc.. Was the CLI importer tested? Or just the browser version? Just curious...

My first attempt I routed like to like (since i used to have a like - knowing i can just replace the icon later), and all the others i routed as new... Second time I tried, it gave me the below longer error message  (browser based) after i routed like to like, and all the other ones to the correct ones that were created on the first try (just no linked content apparently)..

Not sure what my next step is.

I also see the importer does not import usergroup restrictions and other criteria from what I can tell...

HELP!

Upload any screenshots related to the issue below
![reactions_2_import_bug](https://user-images.githubusercontent.com/35111972/52384068-eeddc000-2a49-11e9-841a-9e1eedda6d7b.png)
![reactions_2_import_bug_second_try](https://user-images.githubusercontent.com/35111972/52384069-eeddc000-2a49-11e9-84c2-7d58b830e21c.png)

**Comment by lilalien** [comment]
Here's another oddity.. Each time it craps out, if i hit back in the browser it continues a little more and craps out on another number.. Not sure if that means it processed the previous errored entry or what.. lol

**Comment by lilalien** [comment]
This occurs on step 3/4 of the import btw...

**Comment by lilalien** [comment]
![reactions_2_import_bug_location](https://user-images.githubusercontent.com/35111972/52384844-27cb6400-2a4d-11e9-9240-14f8e6b57fcd.png)

**Comment by lilalien** [comment]
Here's some more detail on one example crap out...

Server error log
InvalidArgumentException: No entity found for 'post' with ID 1018035 src/XF/Repository/Reaction.php:232

Generated by: Jason Feb 6, 2019 at 8:24 PM

Stack trace
#0 src/XF/Import/Data/ReactionContent.php(48): XF\Repository\Reaction->rebuildContentReactionCache('post', 1018035, false)
#1 src/XF/Import/Data/AbstractData.php(135): XF\Import\Data\ReactionContent->postSave(17120, 133925)
#2 src/addons/ThemeHouse/ReactPlus/Import/Importer/THReaction.php(258): XF\Import\Data\AbstractData->save(17120)
#3 src/XF/Import/Runner.php(160): ThemeHouse\ReactPlus\Import\Importer\THReaction->stepReactionContent(Object(XF\Import\StepState), Array, 8)
#4 src/XF/Import/Runner.php(74): XF\Import\Runner->runStep('reactionContent', Object(XF\Import\StepState), 8)
#5 src/XF/Admin/Controller/Import.php(232): XF\Import\Runner->run()
#6 src/XF/Mvc/Dispatcher.php(321): XF\Admin\Controller\Import->actionRun(Object(XF\Mvc\ParameterBag))
#7 src/XF/Mvc/Dispatcher.php(248): XF\Mvc\Dispatcher->dispatchClass('XF:Import', 'Run', Object(XF\Mvc\RouteMatch), Object(XF\Admin\Controller\Import), NULL)
#8 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(XF\Admin\Controller\Import), NULL)
#9 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#10 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#11 src/XF.php(390): XF\App->run()
#12 admin.php(13): XF::runApp('XF\\Admin\\App')
#13 {main}

Request state
array(4) {
  ["url"] => string(21) "/admin.php?import/run"
  ["referrer"] => string(40) "https://www.url.com/admin.php?import/run"
  ["_GET"] => array(1) {
    ["import/run"] => string(0) ""
  }
  ["_POST"] => array(1) {
    ["_xfToken"] => string(8) "********"
  }
}

**Comment by lilalien** [comment]
Not sure if it was something similar to this old report involving deleted profile posts (which had a similar error)?

https://xenforo.com/community/threads/th-reactions-paid.134133/post-1198699
