### ISSUE TITLE
React Plus - Display Reactions given page - Error in conversation reactions with verb usage!

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2addon-issues#1471]
Add-on Name: React Plus

Add-on Version: Beta 2

XenForo Version: 2.1

Operating System (and Version): Windows 10 - 64bit (latest stable)

Browser Name (and Version): Chrome 72 - 64bit (latest stable)

Summary of issue: When viewing the following page: /account/reactions (to view your reactions received)...

This doesn't look quite right to me, is it supposed to look like this with no username?

Detailed steps to reproduce the issue: Visit that page, and make sure someone has given you a reaction in one of your private messages to reproduce it.

![reactions_received_conversation_name_bug](https://user-images.githubusercontent.com/35111972/52442638-af6aae80-2af1-11e9-9c26-b6e46c339e2e.png)

**Comment by lilalien** [comment]
Additional issues with this page:

Another bug that is related to this exact page and function...

If you have a verb chosen, it no longer displays the icon on the page.

Also, if a verb is chosen and someone loads "latest activity", it starts to populate the server error log with the following:

`Server error log
ErrorException: Template error: Function th_reaction is unknown src/XF/Template/Templater.php:893
Generated by: Jason Feb 7, 2019 at 9:55 PM

Stack trace
#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Function th_rea...', '/home/site/publi...', 893, Array)
#1 src/XF/Template/Templater.php(893): trigger_error('Function th_rea...', 512)
#2 internal_data/code_cache/templates/l1/s35/public/news_feed_item_post_react.php(17): XF\Template\Templater->fn('th_reaction', Array, true)
#3 src/XF/Template/Templater.php(1294): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array)
#4 src/XF/NewsFeed/AbstractHandler.php(102): XF\Template\Templater->renderTemplate('news_feed_item_...', Array)
#5 src/XF/Entity/NewsFeed.php(79): XF\NewsFeed\AbstractHandler->render(Object(XF\Entity\NewsFeed))
#6 [internal function]: XF\Entity\NewsFeed->render()
#7 src/XF/Template/Templater.php(978): call_user_func_array(Array, Array)
#8 internal_data/code_cache/templates/l1/s35/public/news_feed_macros.php(34): XF\Template\Templater->method(Object(XF\Entity\NewsFeed), 'render', Array)
#9 src/XF/Template/Templater.php(694): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array, Array)
#10 internal_data/code_cache/templates/l1/s35/public/news_feed_macros.php(14): XF\Template\Templater->callMacro('news_feed_macro...', 'feed_item', Array, Array)
#11 src/XF/Template/Templater.php(694): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array, Array)
#12 internal_data/code_cache/templates/l1/s35/public/latest_activity.php(27): XF\Template\Templater->callMacro('news_feed_macro...', 'feed_row', Array, Array)
#13 src/XF/Template/Templater.php(1294): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array)
#14 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('latest_activity', Array)
#15 src/XF/Mvc/Renderer/Json.php(84): XF\Template\Template->render()
#16 src/XF/Mvc/Renderer/Json.php(68): XF\Mvc\Renderer\Json->renderHtmlFallback('XF:WhatsNew\\Lat...', 'public:latest_a...', Array)
#17 src/XF/Mvc/Dispatcher.php(418): XF\Mvc\Renderer\Json->renderView('XF:WhatsNew\\Lat...', 'public:latest_a...', Array)
#18 src/XF/Mvc/Dispatcher.php(400): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Json), Object(XF\Mvc\Reply\View))
#19 src/XF/Mvc/Dispatcher.php(360): XF\Mvc\Dispatcher->renderReply(Object(XF\Mvc\Renderer\Json), Object(XF\Mvc\Reply\View))
#20 src/XF/Mvc/Dispatcher.php(53): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'json')
#21 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#22 src/XF.php(390): XF\App->run()
#23 index.php(20): XF::runApp('XF\\Pub\\App')
#24 {main}

Request state
array(4) {
  ["url"] => string(178) "/whats-new/latest-activity?before_id=613526&_xfRequestUri=%2Fwhats-new%2Flatest-activity&_xfWithData=1&_xfToken=1549594491%2C890c190a1f80f86d2fd57632ad9c644b&_xfResponseType=json"
  ["referrer"] => string(45) "https://www.site.com/whats-new/latest-activity"
  ["_GET"] => array(5) {
    ["before_id"] => string(6) "613526"
    ["_xfRequestUri"] => string(26) "/whats-new/latest-activity"
    ["_xfWithData"] => string(1) "1"
    ["_xfToken"] => string(43) "1549594491,890c190a1f80f86d2fd57632ad9c644b"
    ["_xfResponseType"] => string(4) "json"
  }
  ["_POST"] => array(0) {
  }
}`
