### ISSUE TITLE
[Post Comments] XF 2.1 reactions

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#1585]
> I see the following issue whenever I try to edit a post comment that already has a reply to itself on a deeper layer. I don't have ThemeHouse's reactions installed currently, I'm using the default 2.1 mechanism.

```
An exception occurred: [TypeError] Argument 3 passed to XF\Template\Templater::fnReactions() must be an instance of XF\Mvc\Entity\Entity, null given in src/XF/Template/Templater.php on line 3248
#0 [internal function]: XF\Template\Templater->fnReactions(Object(ThemeHouse\UIX\XF\Template\Templater), true, NULL, 'posts/reactions', Array)
#1 src/XF/Template/Templater.php(915): call_user_func_array(Array, Array)
#2 internal_data/code_cache/templates/l1/s3/public/post_macros.php(255): XF\Template\Templater->fn('reactions', Array)
#3 src/XF/Template/Templater.php(694): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array, Array)
#4 internal_data/code_cache/templates/l1/s3/public/post_macros.php(565): XF\Template\Templater->callMacro('post_macros', 'post', Array, Array)
#5 src/XF/Template/Templater.php(694): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array, Array)
#6 internal_data/code_cache/templates/l1/s3/public/post_edit_new_post.php(39): XF\Template\Templater->callMacro('post_macros', 'post', Array, Array)
#7 src/XF/Template/Templater.php(1294): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array)
#8 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('post_edit_new_p...', Array)
#9 src/XF/Mvc/Renderer/Json.php(84): XF\Template\Template->render()
#10 src/XF/Mvc/Renderer/Json.php(68): XF\Mvc\Renderer\Json->renderHtmlFallback('XF:Post\EditNew...', 'public:post_edi...', Array)
#11 src/XF/Mvc/Dispatcher.php(418): XF\Mvc\Renderer\Json->renderView('XF:Post\EditNew...', 'public:post_edi...', Array)
#12 src/XF/Mvc/Dispatcher.php(400): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Json), Object(XF\Mvc\Reply\View))
#13 src/XF/Mvc/Dispatcher.php(360): XF\Mvc\Dispatcher->renderReply(Object(XF\Mvc\Renderer\Json), Object(XF\Mvc\Reply\View))
#14 src/XF/Mvc/Dispatcher.php(53): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'json')
#15 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#16 src/XF.php(390): XF\App->run()
#17 index.php(20): XF::runApp('XF\Pub\App')
#18 {main}
```

**Comment by jonw316** [comment]
@LukasWieditz Are you able to replicate this?
