### ISSUE TITLE
[Covers] Attempted to convert NULL to integer [content_id]

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1684]
This old issue [here](https://github.com/Audentio/xf2addon-issues/issues/513) still happening.

````
InvalidArgumentException: Attempted to convert NULL to integer [content_id] src/XF/Mvc/Entity/Entity.php:740 

Generated by: Abdur Apr 1, 2019 at 7:19 PM 

Stack trace

#0 src/XF/Mvc/Entity/Entity.php(618): XF\Mvc\Entity\Entity->_castValueToType(NULL, 'content_id', 2, Array)
#1 src/XF/Mvc/Entity/Entity.php(1363): XF\Mvc\Entity\Entity->set('content_id', NULL, Array)
#2 src/XF/Mvc/Entity/Entity.php(1350): XF\Mvc\Entity\Entity->_resolveDeferredValue('content_id', Object(XF\Mvc\Entity\DeferredValue), 'save')
#3 src/XF/Mvc/Entity/Entity.php(1158): XF\Mvc\Entity\Entity->_fillDeferredValues('save')
#4 src/addons/ThemeHouse/Covers/Entity/Cover.php(361): XF\Mvc\Entity\Entity->save()
#5 src/XF/Mvc/Entity/Entity.php(1297): ThemeHouse\Covers\Entity\Cover->_preSave()
#6 src/XF/Mvc/FormAction.php(51): XF\Mvc\Entity\Entity->preSave()
#7 src/XF/Mvc/FormAction.php(168): XF\Mvc\FormAction->XF\Mvc\{closure}(Object(XF\Mvc\FormAction))
#8 src/addons/ThemeHouse/Covers/Pub/Controller/Cover.php(151): XF\Mvc\FormAction->run()
#9 src/XF/Mvc/Dispatcher.php(321): ThemeHouse\Covers\Pub\Controller\Cover->actionStyle(Object(XF\Mvc\ParameterBag))
#10 src/XF/Mvc/Dispatcher.php(244): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Cove...', 'Style', Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Covers\Pub\Controller\Cover), NULL)
#11 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Covers\Pub\Controller\Cover), NULL)
#12 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#13 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#14 src/XF.php(390): XF\App->run()
#15 index.php(20): XF::runApp('XF\\Pub\\App')
#16 {main}

-------------

Previous InvalidArgumentException: Attempted to convert NULL to integer - src/XF/Mvc/Entity/ValueFormatter.php:141
#0 src/XF/Mvc/Entity/Entity.php(736): XF\Mvc\Entity\ValueFormatter->castValueToType(NULL, 2, Array)
#1 src/XF/Mvc/Entity/Entity.php(618): XF\Mvc\Entity\Entity->_castValueToType(NULL, 'content_id', 2, Array)
#2 src/XF/Mvc/Entity/Entity.php(1363): XF\Mvc\Entity\Entity->set('content_id', NULL, Array)
#3 src/XF/Mvc/Entity/Entity.php(1350): XF\Mvc\Entity\Entity->_resolveDeferredValue('content_id', Object(XF\Mvc\Entity\DeferredValue), 'save')
#4 src/XF/Mvc/Entity/Entity.php(1158): XF\Mvc\Entity\Entity->_fillDeferredValues('save')
#5 src/addons/ThemeHouse/Covers/Entity/Cover.php(361): XF\Mvc\Entity\Entity->save()
#6 src/XF/Mvc/Entity/Entity.php(1297): ThemeHouse\Covers\Entity\Cover->_preSave()
#7 src/XF/Mvc/FormAction.php(51): XF\Mvc\Entity\Entity->preSave()
#8 src/XF/Mvc/FormAction.php(168): XF\Mvc\FormAction->XF\Mvc\{closure}(Object(XF\Mvc\FormAction))
#9 src/addons/ThemeHouse/Covers/Pub/Controller/Cover.php(151): XF\Mvc\FormAction->run()
#10 src/XF/Mvc/Dispatcher.php(321): ThemeHouse\Covers\Pub\Controller\Cover->actionStyle(Object(XF\Mvc\ParameterBag))
#11 src/XF/Mvc/Dispatcher.php(244): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Cove...', 'Style', Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Covers\Pub\Controller\Cover), NULL)
#12 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Covers\Pub\Controller\Cover), NULL)
#13 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#14 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#15 src/XF.php(390): XF\App->run()
#16 index.php(20): XF::runApp('XF\\Pub\\App')
#17 {main}

Request state

array(4) {
  ["url"] => string(23) "/covers/user/1322/style"
  ["referrer"] => string(42) "/members/abdur.1322/"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(5) {
    ["background_color"] => string(0) ""
    ["_xfToken"] => string(8) "********"
    ["_xfRequestUri"] => string(20) "/members/abdur.1322/"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}
````

**Comment by jonw316** [comment]
Also ticket 13820:

```InvalidArgumentException: Attempted to convert NULL to integer [content_id] src/XF/Mvc/Entity/Entity.php:740Generated by: nishi Apr 11, 2019 at 10:33 PM
Stack trace

#0 src/XF/Mvc/Entity/Entity.php(618): XF\Mvc\Entity\Entity->_castValueToType(NULL, 'content_id', 2, Array)
#1 src/XF/Mvc/Entity/Entity.php(1363): XF\Mvc\Entity\Entity->set('content_id', NULL, Array)
#2 src/XF/Mvc/Entity/Entity.php(1350): XF\Mvc\Entity\Entity->_resolveDeferredValue('content_id', Object(XF\Mvc\Entity\DeferredValue), 'save')
#3 src/XF/Mvc/Entity/Entity.php(1158): XF\Mvc\Entity\Entity->_fillDeferredValues('save')
#4 src/addons/ThemeHouse/Covers/Entity/Cover.php(361): XF\Mvc\Entity\Entity->save()
#5 src/XF/Mvc/Entity/Entity.php(1297): ThemeHouse\Covers\Entity\Cover->_preSave()
#6 src/XF/Mvc/FormAction.php(51): XF\Mvc\Entity\Entity->preSave()
#7 src/XF/Mvc/FormAction.php(168): XF\Mvc\FormAction->XF\Mvc{closure}(Object(XF\Mvc\FormAction))
#8 src/addons/ThemeHouse/Covers/Pub/Controller/Cover.php(151): XF\Mvc\FormAction->run()
#9 src/XF/Mvc/Dispatcher.php(321): ThemeHouse\Covers\Pub\Controller\Cover->actionStyle(Object(XF\Mvc\ParameterBag))
#10 src/XF/Mvc/Dispatcher.php(248): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\Cove...', 'Style', Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Covers\Pub\Controller\Cover), NULL)
#11 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Covers\Pub\Controller\Cover), NULL)
#12 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#13 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#14 src/XF.php(390): XF\App->run()
#15 index.php(20): XF::runApp('XF\Pub\App')
#16 {main}```
