### ISSUE TITLE
[Notifier] Template admin:th_notifier_send error: Client error: `GET https://discordapp.com/api/users/@me/guilds` resulted in a 401

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2addon-issues#1731]
```GuzzleHttp\Exception\ClientException: Template admin:th_notifier_send error: Client error: `GET https://discordapp.com/api/users/@me/guilds` resulted in a `401 UNAUTHORIZED` response: {"code": 0, "message": "401: Unauthorized"}```

Stack trace:
```
#0 src/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 src/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 src/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 src/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 src/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#5 src/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 src/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#7 src/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 src/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 src/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Promise\Promise->wait()
#10 src/addons/ThemeHouse/Notifier/NotifierProvider/DiscordProvider.php(91): GuzzleHttp\Client->request('GET', 'users/@me/guild...')
#11 src/addons/ThemeHouse/Notifier/NotifierProvider/DiscordProvider.php(54): ThemeHouse\Notifier\NotifierProvider\DiscordProvider->apiGet('users/@me/guild...')
#12 [internal function]: ThemeHouse\Notifier\NotifierProvider\DiscordProvider->renderActionOptions(NULL)
#13 src/XF/Template/Templater.php(985): call_user_func_array(Array, Array)
#14 internal_data/code_cache/templates/l1/s0/admin/th_notifier_send.php(29): XF\Template\Templater->method(Object(ThemeHouse\Notifier\NotifierProvider\DiscordProvider), 'renderActionOpt...', Array)
#15 src/XF/Template/Templater.php(1301): XF\Template\Templater->{closure}(Object(SV\ConversationEssentials\XF\Template\Templater), Array)
#16 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('th_notifier_sen...', Array)
#17 src/XF/Mvc/Renderer/Html.php(48): XF\Template\Template->render()
#18 src/XF/Mvc/Dispatcher.php(418): XF\Mvc\Renderer\Html->renderView('ThemeHouse\\Noti...', 'admin:th_notifi...', Array)
#19 src/XF/Mvc/Dispatcher.php(400): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#20 src/XF/Mvc/Dispatcher.php(360): XF\Mvc\Dispatcher->renderReply(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#21 src/XF/Mvc/Dispatcher.php(53): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#22 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#23 src/XF.php(390): XF\App->run()
#24 admin.php(13): XF::runApp('XF\\Admin\\App')
#25 {main}
```

**Comment by LukasWieditz** [comment]
Have you set up a discord notifier?

**Comment by tom-coward** [comment]
Yes, it should be all set. To clarify though, what’s expected in the token field, the whole webhook URL?

**Comment by LukasWieditz** [comment]
The Bot Token
