### ISSUE TITLE
[Image Optimizer] Unable to find a suitable image optimizer provider for status ID 5992

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1735]
Server error log:

````
ErrorException: Unable to find a suitable image optimizer provider for status ID 5992. Note: This is most likely not a bug and this message is only generated to notify you of the issue. Details: File size: 2670, Mime type: image/vnd.microsoft.icon src/XF/Error.php:75 

Generated by: Unknown account Apr 26, 2019 at 11:02 AM 

Stack trace

#0 src/XF.php(187): XF\Error->logError('Unable to find ...', false)
#1 src/addons/ThemeHouse/ImageOptimizer/Service/ImageOptimizer/Optimize.php(60): XF::logError('Unable to find ...')
#2 src/addons/ThemeHouse/ImageOptimizer/ContentHandler/AbstractHandler.php(57): ThemeHouse\ImageOptimizer\Service\ImageOptimizer\Optimize->run()
#3 src/addons/ThemeHouse/ImageOptimizer/ContentHandler/AbstractHandler.php(160): ThemeHouse\ImageOptimizer\ContentHandler\AbstractHandler->optimize(Object(ThemeHouse\ImageOptimizer\Entity\Status))
#4 src/addons/ThemeHouse/ImageOptimizer/ImageOptimizer.php(105): ThemeHouse\ImageOptimizer\ContentHandler\AbstractHandler->createStatusAndOptimize(Object(ThemeHouse\ImageOptimizer\XF\Entity\ImageProxy))
#5 src/addons/ThemeHouse/ImageOptimizer/ImageOptimizer.php(36): ThemeHouse\ImageOptimizer\ImageOptimizer->optimizeEntity('th_imageopt_ima...', Object(ThemeHouse\ImageOptimizer\XF\Entity\ImageProxy))
#6 src/addons/ThemeHouse/ImageOptimizer/XF/Service/ImageProxy.php(13): ThemeHouse\ImageOptimizer\ImageOptimizer::optimize('th_imageopt_ima...', Object(ThemeHouse\ImageOptimizer\XF\Entity\ImageProxy))
#7 src/XF/Service/ImageProxy.php(105): ThemeHouse\ImageOptimizer\XF\Service\ImageProxy->finalizeFromFetchResults(Object(ThemeHouse\ImageOptimizer\XF\Entity\ImageProxy), Array)
#8 src/XF/Service/ImageProxy.php(39): XF\Service\ImageProxy->refetchImage(Object(ThemeHouse\ImageOptimizer\XF\Entity\ImageProxy))
#9 src/XF/Proxy/Controller.php(120): XF\Service\ImageProxy->getImage('https://k2s.cc/...')
#10 proxy.php(34): XF\Proxy\Controller->outputImage('https://k2s.cc/...', '6cec60ad1eff99c...')
#11 {main}

Request state

array(4) {
  ["url"] => string(104) "/proxy.php?image=https%3A%2F%2Fk2s.cc%2Ffavicon.ico&hash=6cec60ad1eff99c30872a868683f1b69&return_error=1"
  ["referrer"] => string(102) "/threads/videos-collection.41849/page-16"
  ["_GET"] => array(3) {
    ["image"] => string(26) "https://k2s.cc/favicon.ico"
    ["hash"] => string(32) "6cec60ad1eff99c30872a868683f1b69"
    ["return_error"] => string(1) "1"
  }
  ["_POST"] => array(0) {
  }
}
````

**Comment by JakeBooher** [comment]
no image optimizers support icon files, as the error message states:

```
Unable to find a suitable image optimizer provider for status ID 5992. Note: This is most likely not a bug and this message is only generated to notify you of the issue. Details: File size: 2670, Mime type: image/vnd.microsoft.icon
```

You can disable these informational logs in the options
