### ISSUE TITLE
[Notifier] Too Many Requests

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1750]
What does this  Server error logs?

````
Http\Client\Common\Exception\ClientErrorException: Too Many Requests src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/Plugin/ErrorPlugin.php:72 

Generated by: prinanad May 1, 2019 at 9:01 PM 

Stack trace

#0 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/Plugin/ErrorPlugin.php(54): Http\Client\Common\Plugin\ErrorPlugin->transformResponseToException(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 src/addons/ThemeHouse/Notifier/vendor/php-http/httplug/src/Promise/HttpFulfilledPromise.php(34): Http\Client\Common\Plugin\ErrorPlugin->Http\Client\Common\Plugin\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/Plugin/ErrorPlugin.php(55): Http\Client\Promise\HttpFulfilledPromise->then(Object(Closure))
#3 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/PluginClient.php(161): Http\Client\Common\Plugin\ErrorPlugin->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure))
#4 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/PluginClient.php(175): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(GuzzleHttp\Psr7\Request))
#5 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/PluginClient.php(88): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(GuzzleHttp\Psr7\Request))
#6 src/addons/ThemeHouse/Notifier/vendor/jane-php/open-api-runtime/Client/Psr7HttplugClient.php(48): Http\Client\Common\PluginClient->sendRequest(Object(GuzzleHttp\Psr7\Request))
#7 src/addons/ThemeHouse/Notifier/vendor/jolicode/slack-php-api/generated/Client.php(617): Jane\OpenApiRuntime\Client\Psr7HttplugClient->executePsr7Endpoint(Object(JoliCode\Slack\Api\Endpoint\ChatPostMessage), 'object')
#8 src/addons/ThemeHouse/Notifier/NotifierProvider/SlackProvider.php(86): JoliCode\Slack\Api\Client->chatPostMessage(Array)
#9 src/addons/ThemeHouse/Notifier/Entity/Action.php(28): ThemeHouse\Notifier\NotifierProvider\SlackProvider->sendMessage('<https://nirjon...', Array)
#10 src/addons/ThemeHouse/Notifier/Action.php(22): ThemeHouse\Notifier\Entity\Action->trigger(Object(SV\ChangePostDate\XF\Entity\Post), 'delete', Object(Datio\AllowedEmails\XF\Entity\User))
#11 src/addons/ThemeHouse/Notifier/XF/Entity/Post.php(35): ThemeHouse\Notifier\Action::trigger(Object(SV\ChangePostDate\XF\Entity\Post), 'delete')
#12 src/XF/Mvc/Entity/Entity.php(1580): ThemeHouse\Notifier\XF\Entity\Post->_postDelete()
#13 src/XF/Service/Post/Deleter.php(95): XF\Mvc\Entity\Entity->delete()
#14 src/XF/InlineMod/Post/Delete.php(55): XF\Service\Post\Deleter->delete('hard', '')
#15 src/XF/InlineMod/Post/Delete.php(34): XF\InlineMod\Post\Delete->applyToEntity(Object(SV\ChangePostDate\XF\Entity\Post), Array)
#16 src/XF/InlineMod/AbstractAction.php(80): XF\InlineMod\Post\Delete->applyInternal(Object(XF\Mvc\Entity\ArrayCollection), Array)
#17 src/XF/Pub/Controller/InlineMod.php(131): XF\InlineMod\AbstractAction->apply(Object(XF\Mvc\Entity\ArrayCollection), Array)
#18 src/addons/Siropu/AdsManager/XF/Pub/Controller/InlineMod.php(54): XF\Pub\Controller\InlineMod->actionPerform()
#19 src/XF/Mvc/Dispatcher.php(321): Siropu\AdsManager\XF\Pub\Controller\InlineMod->actionPerform(Object(XF\Mvc\ParameterBag))
#20 src/XF/Mvc/Dispatcher.php(244): XF\Mvc\Dispatcher->dispatchClass('XF:InlineMod', 'Perform', Object(XF\Mvc\RouteMatch), Object(TickTackk\ChangeContentOwner\XF\Pub\Controller\InlineMod), Object(XF\Mvc\Reply\Reroute))
#21 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(TickTackk\ChangeContentOwner\XF\Pub\Controller\InlineMod), Object(XF\Mvc\Reply\Reroute))
#22 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#23 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#24 src/XF.php(390): XF\App->run()
#25 index.php(20): XF::runApp('XF\\Pub\\App')
#26 {main}

Request state

array(4) {
  ["url"] => string(12) "/inline-mod/"
  ["referrer"] => string(52) "/search/44345/?mod=post&page=6"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(12) {
    ["hard_delete"] => string(1) "1"
    ["author_alert"] => string(1) "1"
    ["author_alert_reason"] => string(29) "Don't spam, we hate spammers."
    ["ids"] => array(100) {
      [0] => string(6) "440649"
      [1] => string(6) "440661"
      [2] => string(6) "440662"
      [3] => string(6) "440664"
      [4] => string(6) "440667"
      [5] => string(6) "690933"
      [6] => string(6) "690934"
      [7] => string(6) "690935"
      [8] => string(6) "690936"
      [9] => string(6) "690937"
      [10] => string(6) "690938"
      [11] => string(6) "690940"
      [12] => string(6) "690943"
      [13] => string(6) "690944"
      [14] => string(6) "690945"
      [15] => string(6) "690949"
      [16] => string(6) "690950"
      [17] => string(6) "690952"
      [18] => string(6) "690953"
      [19] => string(6) "690955"
      [20] => string(6) "690956"
      [21] => string(6) "690958"
      [22] => string(6) "690960"
      [23] => string(6) "690962"
      [24] => string(6) "690965"
      [25] => string(6) "690973"
      [26] => string(6) "690974"
      [27] => string(6) "690975"
      [28] => string(6) "690977"
      [29] => string(6) "690978"
      [30] => string(6) "690979"
      [31] => string(6) "690980"
      [32] => string(6) "690982"
      [33] => string(6) "690983"
      [34] => string(6) "690984"
      [35] => string(6) "690986"
      [36] => string(6) "690987"
      [37] => string(6) "690988"
      [38] => string(6) "690990"
      [39] => string(6) "690991"
      [40] => string(6) "690992"
      [41] => string(6) "690993"
      [42] => string(6) "690994"
      [43] => string(6) "690995"
      [44] => string(6) "690997"
      [45] => string(6) "690998"
      [46] => string(6) "690999"
      [47] => string(6) "691000"
      [48] => string(6) "691002"
      [49] => string(6) "691003"
      [50] => string(6) "691005"
      [51] => string(6) "691006"
      [52] => string(6) "691008"
      [53] => string(6) "691009"
      [54] => string(6) "691010"
      [55] => string(6) "691012"
      [56] => string(6) "691013"
      [57] => string(6) "691014"
      [58] => string(6) "691015"
      [59] => string(6) "691016"
      [60] => string(6) "691017"
      [61] => string(6) "691018"
      [62] => string(6) "691019"
      [63] => string(6) "691020"
      [64] => string(6) "691021"
      [65] => string(6) "691022"
      [66] => string(6) "691024"
      [67] => string(6) "691025"
      [68] => string(6) "691026"
      [69] => string(6) "691028"
      [70] => string(6) "691029"
      [71] => string(6) "691030"
      [72] => string(6) "691031"
      [73] => string(6) "691033"
      [74] => string(6) "691035"
      [75] => string(6) "691036"
      [76] => string(6) "691037"
      [77] => string(6) "691038"
      [78] => string(6) "691040"
      [79] => string(6) "691041"
      [80] => string(6) "691043"
      [81] => string(6) "691044"
      [82] => string(6) "691045"
      [83] => string(6) "691047"
      [84] => string(6) "691048"
      [85] => string(6) "691050"
      [86] => string(6) "691051"
      [87] => string(6) "691052"
      [88] => string(6) "691053"
      [89] => string(6) "691054"
      [90] => string(6) "691058"
      [91] => string(6) "691059"
      [92] => string(6) "691060"
      [93] => string(6) "691062"
      [94] => string(6) "691063"
      [95] => string(6) "691064"
      [96] => string(6) "691065"
      [97] => string(6) "691066"
      [98] => string(6) "691068"
      [99] => string(6) "691069"
    }
    ["type"] => string(4) "post"
    ["action"] => string(6) "delete"
    ["confirmed"] => string(1) "1"
    ["_xfRedirect"] => string(52) "/search/44345/?mod=post&page=6"
    ["_xfToken"] => string(8) "********"
    ["_xfRequestUri"] => string(30) "/search/44345/?mod=post&page=6"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}
````

**Comment by LukasWieditz** [comment]
You're sending too many requests to the spotify API, as seen in #1757. Consider increasing the time between updates
