### ISSUE TITLE
[Topics] MySQL query error [1213]: Deadlock found when trying to get lock

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1764]
Server error log

```
XF\Db\DeadlockException: MySQL query error [1213]: Deadlock found when trying to get lock; try restarting transaction src/XF/Db/AbstractStatement.php:217

Generated by: rezatg May 4, 2019 at 1:19 AM

Stack trace

UPDATE  `xf_forum` SET `message_count` = ?, `last_post_date` = ?, `last_post_id` = ?, `last_thread_id` = ?, `last_thread_title` = ? WHERE `node_id` = 83
------------

#0 src/XF/Db/Mysqli/Statement.php(196): XF\Db\AbstractStatement->getException('MySQL query err...', 1213, '40001')
#1 src/XF/Db/Mysqli/Statement.php(77): XF\Db\Mysqli\Statement->getException('MySQL query err...', 1213, '40001')
#2 src/XF/Db/AbstractAdapter.php(94): XF\Db\Mysqli\Statement->execute()
#3 src/XF/Db/AbstractAdapter.php(322): XF\Db\AbstractAdapter->query('UPDATE  `xf_for...', Array)
#4 src/XF/Mvc/Entity/Entity.php(1457): XF\Db\AbstractAdapter->update('xf_forum', Array, '`node_id` = 83')
#5 src/XF/Mvc/Entity/Entity.php(1184): XF\Mvc\Entity\Entity->_saveToSource()
#6 src/XF/Entity/Thread.php(922): XF\Mvc\Entity\Entity->save()
#7 src/XF/Entity/Thread.php(761): XF\Entity\Thread->updateForumRecord()
#8 src/addons/DBTech/Credits/XF/Entity/Thread.php(98): XF\Entity\Thread->_postSave()
#9 src/addons/DBTech/Shop/XF/Entity/Thread.php(18): DBTech\Credits\XF\Entity\Thread->_postSave()
#10 src/addons/xenMade/STUTC/XF/Entity/Thread.php(31): DBTech\Shop\XF\Entity\Thread->_postSave()
#11 src/addons/ThemeHouse/Topics/XF/Entity/Thread.php(76): xenMade\STUTC\XF\Entity\Thread->_postSave()
#12 src/addons/ThemeHouse/Notifier/XF/Entity/Thread.php(9): ThemeHouse\Topics\XF\Entity\Thread->_postSave()
#13 src/XF/Mvc/Entity/Entity.php(1208): ThemeHouse\Notifier\XF\Entity\Thread->_postSave()
#14 src/XF/Entity/Post.php(542): XF\Mvc\Entity\Entity->save()
#15 src/XF/Entity/Post.php(507): XF\Entity\Post->updateThreadRecord()
#16 src/addons/AddonsLab/LinkChecker/XF/Entity/Post.php(52): XF\Entity\Post->_postSave()
#17 src/addons/DBTech/Credits/XF/Entity/Post.php(228): AddonsLab\LinkChecker\XF\Entity\Post->_postSave()
#18 src/addons/DBTech/Shop/XF/Entity/Post.php(12): DBTech\Credits\XF\Entity\Post->_postSave()
#19 src/addons/ThemeHouse/ReactPlus/XF/Entity/Post.php(25): DBTech\Shop\XF\Entity\Post->_postSave()
#20 src/addons/ThemeHouse/Notifier/XF/Entity/Post.php(9): ThemeHouse\ReactPlus\XF\Entity\Post->_postSave()
#21 src/XF/Mvc/Entity/Entity.php(1208): ThemeHouse\Notifier\XF\Entity\Post->_postSave()
#22 src/XF/Service/Thread/Replier.php(167): XF\Mvc\Entity\Entity->save(true, false)
#23 src/XF/Service/ValidateAndSavableTrait.php(40): XF\Service\Thread\Replier->_save()
#24 src/XF/Pub/Controller/Thread.php(461): XF\Service\Thread\Replier->save()
#25 src/addons/Snog/ForceSecure/XF/Pub/Controller/Thread.php(17): XF\Pub\Controller\Thread->actionAddReply(Object(XF\Mvc\ParameterBag))
#26 src/addons/xenMade/STFRT/XF/Pub/Controller/Thread.php(111): Snog\ForceSecure\XF\Pub\Controller\Thread->actionAddReply(Object(XF\Mvc\ParameterBag))
#27 src/addons/KL/EditorManager/XF/Pub/Controller/Thread.php(23): xenMade\STFRT\XF\Pub\Controller\Thread->actionAddReply(Object(XF\Mvc\ParameterBag))
#28 src/XF/Mvc/Dispatcher.php(321): KL\EditorManager\XF\Pub\Controller\Thread->actionAddReply(Object(XF\Mvc\ParameterBag))
#29 src/XF/Mvc/Dispatcher.php(244): XF\Mvc\Dispatcher->dispatchClass('XF:Thread', 'AddReply', Object(XF\Mvc\RouteMatch), Object(SV\ElasticSearchEssentials\XF\Pub\Controller\Thread), NULL)
#30 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(SV\ElasticSearchEssentials\XF\Pub\Controller\Thread), NULL)
#31 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#32 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#33 src/XF.php(390): XF\App->run()
#34 index.php(20): XF::runApp('XF\\Pub\\App')
#35 {main}

Request state

array(4) {
  ["url"] => string(58) "/threads/indian.2853/add-reply"
  ["referrer"] => string(71) "/threads/indian.2853/"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(8) {
    ["message"] => string(25) "Josh jinish arro chai vai"
    ["last_date"] => string(10) "1522708988"
    ["last_known_date"] => string(10) "1556614950"
    ["klPage"] => string(0) ""
    ["_xfToken"] => string(8) "********"
    ["_xfRequestUri"] => string(49) "/threads/indian.2853/"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}
```

**Comment by LukasWieditz** [comment]
That error goes through so many add-ons that it is impossible to determine what could have caused this. Unless provided with a smaller set, we won't be able to investigate this. Fwiw, I don't think that either topics nor notifiers would be involved in this.

**Comment by JakeBooher** [comment]
This actually won't be caused by any of our add-ons, this is all XenForo updating last post details on a node, it'll just list in the stack trace any add-on with a class extension for \XF\Entity\Thread::_postSave
