### ISSUE TITLE
[ReactPlus] MySQL query error [1205]: Lock wait timeout exceeded; try restarting transaction

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1765]
Server error log

```
XF\Db\Exception: MySQL query error [1205]: Lock wait timeout exceeded; try restarting transaction src/XF/Db/AbstractStatement.php:217

Generated by: Nargish Apr 9, 2019 at 7:23 PM

Stack trace

            UPDATE xf_user
            SET reaction_score = reaction_score + ?
            WHERE user_id = ?
        
------------

#0 src/XF/Db/Mysqli/Statement.php(196): XF\Db\AbstractStatement->getException('MySQL query err...', 1205, 'HY000')
#1 src/XF/Db/Mysqli/Statement.php(77): XF\Db\Mysqli\Statement->getException('MySQL query err...', 1205, 'HY000')
#2 src/XF/Db/AbstractAdapter.php(94): XF\Db\Mysqli\Statement->execute()
#3 src/XF/Entity/ReactionContent.php(192): XF\Db\AbstractAdapter->query('
            UPDATE xf_u...', Array)
#4 src/XF/Entity/ReactionContent.php(149): XF\Entity\ReactionContent->adjustUserReactionScore(298, -1)
#5 src/addons/DBTech/Credits/XF/Entity/ReactionContent.php(164): XF\Entity\ReactionContent->_postDelete()
#6 src/XF/Mvc/Entity/Entity.php(1580): DBTech\Credits\XF\Entity\ReactionContent->_postDelete()
#7 src/XF/Repository/Reaction.php(118): XF\Mvc\Entity\Entity->delete()
#8 src/addons/ThemeHouse/ReactPlus/XF/Repository/Reaction.php(20): XF\Repository\Reaction->reactToContent(1, 'post', 133886, Object(Datio\AllowedEmails\XF\Entity\User), true, false)
#9 src/XF/ControllerPlugin/Reaction.php(65): ThemeHouse\ReactPlus\XF\Repository\Reaction->reactToContent(1, 'post', 133886, Object(Datio\AllowedEmails\XF\Entity\User), true)
#10 src/addons/ThemeHouse/ReactPlus/XF/ControllerPlugin/Reaction.php(17): XF\ControllerPlugin\Reaction->actionToggleReaction(Object(SV\ChangePostDate\XF\Entity\Post), 'posts/reactions', 'posts')
#11 src/XF/ControllerPlugin/Reaction.php(19): ThemeHouse\ReactPlus\XF\ControllerPlugin\Reaction->actionToggleReaction(Object(SV\ChangePostDate\XF\Entity\Post), 'posts/reactions', 'posts')
#12 src/XF/ControllerPlugin/Reaction.php(12): XF\ControllerPlugin\Reaction->actionReact(Object(SV\ChangePostDate\XF\Entity\Post), 'posts', 'posts/react', 'posts/reactions')
#13 src/XF/Pub/Controller/Post.php(368): XF\ControllerPlugin\Reaction->actionReactSimple(Object(SV\ChangePostDate\XF\Entity\Post), 'posts')
#14 src/addons/KL/EditorManager/XF/Pub/Controller/Post.php(23): XF\Pub\Controller\Post->actionReact(Object(XF\Mvc\ParameterBag))
#15 src/XF/Mvc/Dispatcher.php(321): KL\EditorManager\XF\Pub\Controller\Post->actionReact(Object(XF\Mvc\ParameterBag))
#16 src/XF/Mvc/Dispatcher.php(244): XF\Mvc\Dispatcher->dispatchClass('XF:Post', 'React', Object(XF\Mvc\RouteMatch), Object(TickTackk\ContentCopyProtection\XF\Pub\Controller\Post), NULL)
#17 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(TickTackk\ContentCopyProtection\XF\Pub\Controller\Post), NULL)
#18 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#19 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#20 src/XF.php(390): XF\App->run()
#21 index.php(20): XF::runApp('XF\\Pub\\App')
#22 {main}

Request state

array(4) {
  ["url"] => string(33) "/posts/133886/react?reaction_id=1"
  ["referrer"] => string(61) "/threads/rocketman-augustus.8860/page-2"
  ["_GET"] => array(1) {
    ["reaction_id"] => string(1) "1"
  }
  ["_POST"] => array(4) {
    ["_xfRequestUri"] => string(39) "/threads/rocketman-augustus.8860/page-2"
    ["_xfWithData"] => string(1) "1"
    ["_xfToken"] => string(8) "********"
    ["_xfResponseType"] => string(4) "json"
  }
}
```

**Comment by LukasWieditz** [comment]
As #1764.
