### ISSUE TITLE
Covers resource entity error

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2addon-issues#1842]
I've never installed resource add-on in my life so I do not know why I am constantly receiving these errors! I have tried the URL myself: https://www.joyfreak.com/covers/resource/100/position

The /100/ you can change that to ANY value, i.e 1000, 973789, 2384 , whatever number it will still throw an error. So I decided to try that url on another site that does not have resources installed and they also get the same error. This is certainly a BUG. Please resolve and don't discard just like that.

**Comment by joyfreak** [comment]
This is how it looks when you visit the url above and any other value
![resource](https://user-images.githubusercontent.com/43339306/58503787-34e99b80-8181-11e9-9755-2d6c4caf6026.png)

**Comment by joyfreak** [comment]
Glad it's been fixed. Is it going to be released any time soon to stop these errors?

Thanks

**Comment by joyfreak** [comment]
This is now happening in it's place:
Server error log
Error: Cannot use object of type XF\Cache\RedisCache as array src/addons/ThemeHouse/Covers/Repository/CoverHandler.php:75
Generated by: Carbon Jun 25, 2019 at 4:10 PM
Stack trace
#0 src/addons/ThemeHouse/Covers/Pub/Controller/Cover.php(408): ThemeHouse\Covers\Repository\CoverHandler->getCoverHandler('resource', true)
#1 src/addons/ThemeHouse/Covers/Pub/Controller/Cover.php(387): ThemeHouse\Covers\Pub\Controller\Cover->assertCover('resource', '6')
#2 src/XF/Pub/Controller/AbstractController.php(30): ThemeHouse\Covers\Pub\Controller\Cover->preDispatchController('Position', Object(XF\Mvc\ParameterBag))
#3 src/XF/Mvc/Controller.php(123): XF\Pub\Controller\AbstractController->preDispatchType('Position', Object(XF\Mvc\ParameterBag))
#4 src/XF/Mvc/Dispatcher.php(320): XF\Mvc\Controller->preDispatch('Position', Object(XF\Mvc\ParameterBag))
#5 src/XF/Mvc/Dispatcher.php(244): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Cove...', 'Position', Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Covers\Pub\Controller\Cover), NULL)
#6 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Covers\Pub\Controller\Cover), NULL)
#7 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#8 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#9 src/XF.php(390): XF\App->run()
#10 index.php(20): XF::runApp('XF\\Pub\\App')
#11 {main}
Request state
array(4) {
  ["url"] => string(27) "/covers/resource/6/position"
  ["referrer"] => bool(false)
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}
