### ISSUE TITLE
[Covers] Server error log in /admin.php?cover-presets/

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1910]
```
Error: Cannot use object of type SV\RedisCache\Redis as array src/addons/ThemeHouse/Covers/Repository/CoverHandler.php:46 

Generated by: Nirjonmela Jun 25, 2019 at 10:45 PM 

Stack trace

#0 src/addons/ThemeHouse/Covers/Entity/CoverPreset.php(122): ThemeHouse\Covers\Repository\CoverHandler->getCoverHandlers()
#1 src/XF/Mvc/Entity/Entity.php(148): ThemeHouse\Covers\Entity\CoverPreset->getDefaultNames()
#2 src/XF/Mvc/Entity/Entity.php(106): XF\Mvc\Entity\Entity->get('default_names')
#3 internal_data/code_cache/templates/l1/s0/admin/thcovers_cover_preset_list.php(14): XF\Mvc\Entity\Entity->offsetGet('default_names')
#4 src/XF/Template/Templater.php(701): XF\Template\Templater->{closure}(Object(AddonFlare\PaidRegistrations\XF\Template\Templater), Array, Array)
#5 internal_data/code_cache/templates/l1/s0/admin/thcovers_cover_preset_list.php(117): XF\Template\Templater->callMacro('thcovers_cover_...', 'preset', Array, Array)
#6 src/XF/Template/Templater.php(1301): XF\Template\Templater->{closure}(Object(AddonFlare\PaidRegistrations\XF\Template\Templater), Array)
#7 src/addons/AddonsLab/LinkChecker/XF/Template/Templater.php(89): XF\Template\Templater->renderTemplate('thcovers_cover_...', Array, true)
#8 src/XF/Template/Template.php(24): AddonsLab\LinkChecker\XF\Template\Templater->renderTemplate('admin:thcovers_...', Array)
#9 src/XF/Mvc/Renderer/Html.php(48): XF\Template\Template->render()
#10 src/XF/Mvc/Dispatcher.php(418): XF\Mvc\Renderer\Html->renderView('ThemeHouse\\Cove...', 'admin:thcovers_...', Array)
#11 src/XF/Mvc/Dispatcher.php(400): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#12 src/XF/Mvc/Dispatcher.php(360): XF\Mvc\Dispatcher->renderReply(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#13 src/XF/Mvc/Dispatcher.php(53): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#14 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#15 src/XF.php(390): XF\App->run()
#16 admin.php(13): XF::runApp('XF\\Admin\\App')
#17 {main}

Request state

array(4) {
  ["url"] => string(25) "/admin.php?cover-presets/"
  ["referrer"] => string(32) "/admin.php"
  ["_GET"] => array(1) {
    ["cover-presets/"] => string(0) ""
  }
  ["_POST"] => array(0) {
  }
}
```

**Comment by LukasWieditz** [comment]
#1909
