### ISSUE TITLE
[Topics] Logic Exception error 

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1942]
Was reported by [imno007](https://xenforo.com/community/threads/th-topics-paid.157797/post-1362663) on xenforo.com:
```
Server error log
LogicException: Macro public:whats_new_posts :: filter_bar() error: Macro argument threadPrefixes is required and no value was provided
src/XF/Template/Templater.php:809
Stack trace
#0 internal_data/code_cache/templates/l1/s112/public/whats_new_posts.php(42): XF\Template\Templater->mergeMacroArguments(Array, Array, Array)
#1 src/XF/Template/Templater.php(701): XF\Template\Templater->{closure}(Object(ThemeHouse\UserImprovements\XF\Template\Templater), Array, Array)
#2 internal_data/code_cache/templates/l1/s112/public/thtopics_whats_new_threads.php(158): XF\Template\Templater->callMacro('whats_new_posts', 'filter_bar', Array, Array)
#3 src/XF/Template/Templater.php(1301): XF\Template\Templater->{closure}(Object(ThemeHouse\UserImprovements\XF\Template\Templater), Array)
#4 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('thtopics_whats_...', Array)
#5 src/XF/Mvc/Renderer/Html.php(48): XF\Template\Template->render()
#6 src/XF/Mvc/Dispatcher.php(418): XF\Mvc\Renderer\Html->renderView('ThemeHouse\\Topi...', 'public:thtopics...', Array)
#7 src/XF/Mvc/Dispatcher.php(400): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#8 src/XF/Mvc/Dispatcher.php(360): XF\Mvc\Dispatcher->renderReply(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#9 src/XF/Mvc/Dispatcher.php(53): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#10 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#11 src/XF.php(390): XF\App->run()
#12 index.php(20): XF::runApp('XF\\Pub\\App')
#13 {main}


Request state

array(4) {
["url"] => string(25) "/whats-new/threads/32552/"
["referrer"] => string(42) "htt://.../forums/-/all-threads"
["_GET"] => array(0) {
}
["_POST"] => array(0) {
}
}
```

**Comment by LukasWieditz** [comment]
This doesn't appear to be a topics bug.
