### ISSUE TITLE
[ReactionsPlus] Siropu Chat 2 Error

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1952]
```
Error: Call to a member function getProperty() on null src\addons\ThemeHouse\ReactPlus\XF\Template\Templater.php:106
Generated by: SeToY 25 Jul 2019 at 00:26
Stack trace
#0 [internal function]: ThemeHouse\ReactPlus\XF\Template\Templater->fnReactions(Object(SV\ConversationEssentials\XF\Template\Templater), false, Object(Siropu\Chat\Entity\Message), 'chat/message/re...')
#1 src\XF\Template\Templater.php(936): call_user_func_array(Array, Array)
#2 src\XF\Template\Templater.php(906): XF\Template\Templater->func('reactions', Array, false)
#3 src\addons\Siropu\Chat\Service\Room\ActionLogger.php(28): XF\Template\Templater->fn('reactions', Array)
#4 src\addons\Siropu\Chat\Entity\Message.php(562): Siropu\Chat\Service\Room\ActionLogger->logMessageAction(Object(Siropu\Chat\Entity\Message))
#5 src\XF\Mvc\Entity\Entity.php(1208): Siropu\Chat\Entity\Message->_postSave()
#6 src\XF\Reaction\AbstractHandler.php(107): XF\Mvc\Entity\Entity->save()
#7 src\XF\Repository\Reaction.php(274): XF\Reaction\AbstractHandler->updateContentReactions(Object(Siropu\Chat\Entity\Message), Array, Array)
#8 src\XF\Entity\ReactionContent.php(198): XF\Repository\Reaction->rebuildContentReactionCache('siropu_chat_roo...', 3238, false)
#9 src\XF\Entity\ReactionContent.php(140): XF\Entity\ReactionContent->rebuildContentReactionCache()
#10 src\XF\Mvc\Entity\Entity.php(1208): XF\Entity\ReactionContent->_postSave()
#11 src\XF\Repository\Reaction.php(189): XF\Mvc\Entity\Entity->save()
#12 src\XF\Repository\Reaction.php(142): XF\Repository\Reaction->insertReaction(1, 'siropu_chat_roo...', 3238, Object(SV\SignupAbuseBlocking\XF\Entity\User), true, false)
#13 src\addons\ThemeHouse\ReactPlus\XF\Repository\Reaction.php(35): XF\Repository\Reaction->reactToContent(1, 'siropu_chat_roo...', 3238, Object(SV\SignupAbuseBlocking\XF\Entity\User), true, false)
#14 src\XF\ControllerPlugin\Reaction.php(65): ThemeHouse\ReactPlus\XF\Repository\Reaction->reactToContent(1, 'siropu_chat_roo...', 3238, Object(SV\SignupAbuseBlocking\XF\Entity\User), true)
#15 src\addons\ThemeHouse\ReactPlus\XF\ControllerPlugin\Reaction.php(50): XF\ControllerPlugin\Reaction->actionToggleReaction(Object(Siropu\Chat\Entity\Message), 'chat/message/re...', 'chat/message')
#16 src\XF\ControllerPlugin\Reaction.php(19): ThemeHouse\ReactPlus\XF\ControllerPlugin\Reaction->actionToggleReaction(Object(Siropu\Chat\Entity\Message), 'chat/message/re...', 'chat/message')
#17 src\XF\ControllerPlugin\Reaction.php(12): XF\ControllerPlugin\Reaction->actionReact(Object(Siropu\Chat\Entity\Message), 'chat/message', 'chat/message/re...', 'chat/message/re...')
#18 src\addons\Siropu\Chat\Pub\Controller\Message.php(241): XF\ControllerPlugin\Reaction->actionReactSimple(Object(Siropu\Chat\Entity\Message), 'chat/message')
#19 src\XF\Mvc\Dispatcher.php(321): Siropu\Chat\Pub\Controller\Message->actionReact(Object(XF\Mvc\ParameterBag))
#20 src\XF\Mvc\Dispatcher.php(248): XF\Mvc\Dispatcher->dispatchClass('Siropu\\Chat:Mes...', 'React', Object(XF\Mvc\RouteMatch), Object(Siropu\Chat\Pub\Controller\Message), NULL)
#21 src\XF\Mvc\Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(Siropu\Chat\Pub\Controller\Message), NULL)
#22 src\XF\Mvc\Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#23 src\XF\App.php(2178): XF\Mvc\Dispatcher->run()
#24 src\XF.php(390): XF\App->run()
#25 index.php(20): XF::runApp('XF\\Pub\\App')
#26 {main}
```

**Comment by LukasWieditz** [comment]
Looks like the chat add-on doesn't set a style before rendering.
