### ISSUE TITLE
UsernameHistory Error

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1959]
```
> "ErrorException: [E_USER_WARNING] Accessed unknown getter 'UsernameHistory' on XF:User[1] src\XF\Mvc\Entity\Entity.php:190"
> 
> Stack trace:
> #0 [internal function]: XF::handlePhpError(512, '[E_USER_WARNING...', 'D:\XenForo2\...', 190, Array)
> #1 src\XF\Mvc\Entity\Entity.php(190): trigger_error('Accessed unknow...', 512)
> #2 src\XF\Mvc\Entity\Entity.php(101): XF\Mvc\Entity\Entity->get('UsernameHistory')
> #3 src\addons\ThemeHouse\UserImprovements\Listener\CriteriaUser.php(32): XF\Mvc\Entity\Entity->__get('UsernameHistory')
> #4 [internal function]: ThemeHouse\UserImprovements\Listener\CriteriaUser::criteriaUser('kl_ui_min_usern...', Array, Object(SV\ReportImprovements\XF\Entity\User), false)
> #5 src\XF\Extension.php(67): call_user_func_array(Array, Array)
> #6 src\XF\App.php(2648): XF\Extension->fire('criteria_user', Array, NULL)
> #7 src\XF\Criteria\User.php(64): XF\App->fire('criteria_user', Array)
> #8 src\XF\Criteria\AbstractCriteria.php(63): XF\Criteria\User->isUnknownMatched('kl_ui_min_usern...', Array, Object(SV\ReportImprovements\XF\Entity\User))
> #9 src\XF\Repository\Trophy.php(68): XF\Criteria\AbstractCriteria->isMatched(Object(SV\ReportImprovements\XF\Entity\User))
> #10 src\XF\Pub\App.php(249): XF\Repository\Trophy->updateTrophiesForUser(Object(SV\ReportImprovements\XF\Entity\User))
> #11 src\XF\Pub\App.php(189): XF\Pub\App->updateUserCaches()
> #12 src\XF\App.php(2174): XF\Pub\App->start(true)
> #13 src\XF.php(390): XF\App->run()
> #14 index.php(20): XF::runApp('XF\Pub\App')
> #15 {main}
```

**Comment by LukasWieditz** [comment]
That's caused by an outdated version.
