### ISSUE TITLE
[Spotify]  Server error logs from Xenforo 2.1.4

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1995]
Getting lot of  Server error logs after updated to Xenforo 2.1.4

```
GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to accounts.spotify.com port 443: Connection timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) src/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185 

Generated by: Nirjonmela Sep 12, 2019 at 4:42 PM 

Stack trace

#0 src/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 src/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 src/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 src/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 src/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 src/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(66): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 src/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 src/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 src/vendor/guzzlehttp/guzzle/src/Middleware.php(58): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 src/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 src/vendor/guzzlehttp/guzzle/src/Client.php(277): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 src/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 src/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Client->requestAsync('post', Object(GuzzleHttp\Psr7\Uri), Array)
#13 src/vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\Client->request('post', 'https://account...', Array)
#14 src/addons/ThemeHouse/Core/Http/HttpClient/20181220.php(23): GuzzleHttp\Client->__call('post', Array)
#15 src/addons/ThemeHouse/Spotify/Util/Spotify/AbstractSpotify.php(174): ThemeHouse\Core\Http\HttpClient->simplePost('https://account...', Array, Array)
#16 src/addons/ThemeHouse/Spotify/Util/Spotify/AbstractSpotify.php(152): ThemeHouse\Spotify\Util\Spotify\AbstractSpotify->refreshAuthorizationToken()
#17 src/addons/ThemeHouse/Spotify/Util/Spotify/AbstractSpotify.php(105): ThemeHouse\Spotify\Util\Spotify\AbstractSpotify->getAuthorizationToken()
#18 src/addons/ThemeHouse/Spotify/Util/Spotify/Player.php(9): ThemeHouse\Spotify\Util\Spotify\AbstractSpotify->request('me/player')
#19 src/addons/ThemeHouse/Spotify/Service/Player/UpdatePlayback.php(36): ThemeHouse\Spotify\Util\Spotify\Player->getCurrentPlayback()
#20 src/addons/ThemeHouse/Spotify/Pub/Controller/Spotify.php(41): ThemeHouse\Spotify\Service\Player\UpdatePlayback->updateCurrentPlayback()
#21 src/XF/Mvc/Dispatcher.php(321): ThemeHouse\Spotify\Pub\Controller\Spotify->actionUpdateCurrentPlayback(Object(XF\Mvc\ParameterBag))
#22 src/XF/Mvc/Dispatcher.php(244): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Spot...', 'UpdateCurrentPl...', Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Spotify\Pub\Controller\Spotify), NULL)
#23 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Spotify\Pub\Controller\Spotify), NULL)
#24 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#25 src/XF/App.php(2178): XF\Mvc\Dispatcher->run()
#26 src/XF.php(390): XF\App->run()
#27 index.php(20): XF::runApp('XF\\Pub\\App')
#28 {main}

Request state

array(4) {
  ["url"] => string(193) "/index.php?spotify/update-current-playback&_xfRequestUri=%2Fadmin.php%3Foptions%2Fgroups%2Fthspotify%2F&_xfWithData=1&_xfToken=1568284954%2Cc766385affa315417921b6b2a5689fec&_xfResponseType=json"
  ["referrer"] => string(58) "/admin.php?options/groups/thspotify/"
  ["_GET"] => array(5) {
    ["spotify/update-current-playback"] => string(0) ""
    ["_xfRequestUri"] => string(36) "/admin.php?options/groups/thspotify/"
    ["_xfWithData"] => string(1) "1"
    ["_xfToken"] => string(43) "1568284954,c766385affa315417921b6b2a5689fec"
    ["_xfResponseType"] => string(4) "json"
  }
  ["_POST"] => array(0) {
  }
}
```

```
GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 150000 milliseconds with 0 out of 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) src/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185 

Generated by: Nirjonmela Sep 12, 2019 at 3:46 PM 

Stack trace

#0 src/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 src/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 src/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 src/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 src/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 src/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(66): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 src/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 src/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 src/vendor/guzzlehttp/guzzle/src/Middleware.php(58): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 src/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 src/vendor/guzzlehttp/guzzle/src/Client.php(277): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 src/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 src/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Client->requestAsync('post', Object(GuzzleHttp\Psr7\Uri), Array)
#13 src/vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\Client->request('post', 'https://account...', Array)
#14 src/addons/ThemeHouse/Core/Http/HttpClient/20181220.php(23): GuzzleHttp\Client->__call('post', Array)
#15 src/addons/ThemeHouse/Spotify/Util/Spotify/AbstractSpotify.php(174): ThemeHouse\Core\Http\HttpClient->simplePost('https://account...', Array, Array)
#16 src/addons/ThemeHouse/Spotify/Util/Spotify/AbstractSpotify.php(152): ThemeHouse\Spotify\Util\Spotify\AbstractSpotify->refreshAuthorizationToken()
#17 src/addons/ThemeHouse/Spotify/Util/Spotify/AbstractSpotify.php(105): ThemeHouse\Spotify\Util\Spotify\AbstractSpotify->getAuthorizationToken()
#18 src/addons/ThemeHouse/Spotify/Util/Spotify/Player.php(9): ThemeHouse\Spotify\Util\Spotify\AbstractSpotify->request('me/player')
#19 src/addons/ThemeHouse/Spotify/Service/Player/UpdatePlayback.php(36): ThemeHouse\Spotify\Util\Spotify\Player->getCurrentPlayback()
#20 src/addons/ThemeHouse/Spotify/Pub/Controller/Spotify.php(41): ThemeHouse\Spotify\Service\Player\UpdatePlayback->updateCurrentPlayback()
#21 src/XF/Mvc/Dispatcher.php(321): ThemeHouse\Spotify\Pub\Controller\Spotify->actionUpdateCurrentPlayback(Object(XF\Mvc\ParameterBag))
#22 src/XF/Mvc/Dispatcher.php(244): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Spot...', 'UpdateCurrentPl...', Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Spotify\Pub\Controller\Spotify), NULL)
#23 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Spotify\Pub\Controller\Spotify), NULL)
#24 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#25 src/XF/App.php(2178): XF\Mvc\Dispatcher->run()
#26 src/XF.php(390): XF\App->run()
#27 index.php(20): XF::runApp('XF\\Pub\\App')
#28 {main}

Request state

array(4) {
  ["url"] => string(167) "/index.php?spotify/update-current-playback&_xfRequestUri=%2Fsearch%2F69514%2F&_xfWithData=1&_xfToken=1568281419%2Ca8c302c829c5609cdf0432a7a55e162e&_xfResponseType=json"
  ["referrer"] => string(36) "/search/69514/"
  ["_GET"] => array(5) {
    ["spotify/update-current-playback"] => string(0) ""
    ["_xfRequestUri"] => string(14) "/search/69514/"
    ["_xfWithData"] => string(1) "1"
    ["_xfToken"] => string(43) "1568281419,a8c302c829c5609cdf0432a7a55e162e"
    ["_xfResponseType"] => string(4) "json"
  }
  ["_POST"] => array(0) {
  }
}
```

```
GuzzleHttp\Exception\ConnectException: cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to accounts.spotify.com:443 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) src/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185 

Generated by: Nirjonmela Sep 12, 2019 at 8:06 AM 

Stack trace

#0 src/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 src/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 src/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 src/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 src/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 src/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(66): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 src/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 src/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 src/vendor/guzzlehttp/guzzle/src/Middleware.php(58): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 src/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 src/vendor/guzzlehttp/guzzle/src/Client.php(277): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 src/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 src/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Client->requestAsync('post', Object(GuzzleHttp\Psr7\Uri), Array)
#13 src/vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\Client->request('post', 'https://account...', Array)
#14 src/addons/ThemeHouse/Core/Http/HttpClient/20181220.php(23): GuzzleHttp\Client->__call('post', Array)
#15 src/addons/ThemeHouse/Spotify/Util/Spotify/AbstractSpotify.php(174): ThemeHouse\Core\Http\HttpClient->simplePost('https://account...', Array, Array)
#16 src/addons/ThemeHouse/Spotify/Util/Spotify/AbstractSpotify.php(152): ThemeHouse\Spotify\Util\Spotify\AbstractSpotify->refreshAuthorizationToken()
#17 src/addons/ThemeHouse/Spotify/Util/Spotify/AbstractSpotify.php(105): ThemeHouse\Spotify\Util\Spotify\AbstractSpotify->getAuthorizationToken()
#18 src/addons/ThemeHouse/Spotify/Util/Spotify/Player.php(9): ThemeHouse\Spotify\Util\Spotify\AbstractSpotify->request('me/player')
#19 src/addons/ThemeHouse/Spotify/Service/Player/UpdatePlayback.php(36): ThemeHouse\Spotify\Util\Spotify\Player->getCurrentPlayback()
#20 src/addons/ThemeHouse/Spotify/Pub/Controller/Spotify.php(41): ThemeHouse\Spotify\Service\Player\UpdatePlayback->updateCurrentPlayback()
#21 src/XF/Mvc/Dispatcher.php(321): ThemeHouse\Spotify\Pub\Controller\Spotify->actionUpdateCurrentPlayback(Object(XF\Mvc\ParameterBag))
#22 src/XF/Mvc/Dispatcher.php(244): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Spot...', 'UpdateCurrentPl...', Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Spotify\Pub\Controller\Spotify), NULL)
#23 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Spotify\Pub\Controller\Spotify), NULL)
#24 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#25 src/XF/App.php(2178): XF\Mvc\Dispatcher->run()
#26 src/XF.php(390): XF\App->run()
#27 index.php(20): XF::runApp('XF\\Pub\\App')
#28 {main}

Request state

array(4) {
  ["url"] => string(188) "/index.php?spotify/update-current-playback&_xfRequestUri=%2Fadmin.php%3Flogs%2Faccount-deletion%2F&_xfWithData=1&_xfToken=1568253968%2C9d84734c33e52b48c84f76b5168a8690&_xfResponseType=json"
  ["referrer"] => string(55) "/admin.php?logs/account-deletion/"
  ["_GET"] => array(5) {
    ["spotify/update-current-playback"] => string(0) ""
    ["_xfRequestUri"] => string(33) "/admin.php?logs/account-deletion/"
    ["_xfWithData"] => string(1) "1"
    ["_xfToken"] => string(43) "1568253968,9d84734c33e52b48c84f76b5168a8690"
    ["_xfResponseType"] => string(4) "json"
  }
  ["_POST"] => array(0) {
  }
}
```

**Comment by LukasWieditz** [comment]
That's an issue with your server. The underlying OS or hardware is having trouble establishing an SSL connection to spotify.
