### ISSUE TITLE
[Donate] - Template public:alert_user_thdonate_comment_edit is unknown

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2095]
Server error log on Edit Donate comment.

```
ErrorException: Template error: Template public:alert_user_thdonate_comment_edit is unknown src/XF/Template/Templater.php:618 

Generated by: Nirjonmela Mar 23, 2020 at 1:03 AM 

Stack trace

#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Template public...', '/home/nadda/pub...', 618, Array)
#1 src/XF/Template/Templater.php(618): trigger_error('Template public...', 512)
#2 src/XF/Template/Templater.php(566): XF\Template\Templater->getTemplateData('public', 'alert_user_thdo...')
#3 src/XF/Template/Templater.php(1314): XF\Template\Templater->getTemplateCode('public', 'alert_user_thdo...')
#4 src/addons/AddonsLab/LinkChecker/XF/Template/Templater.php(89): XF\Template\Templater->renderTemplate('alert_user_thdo...', Array, true)
#5 src/XF/Service/PusherTrait.php(103): AddonsLab\LinkChecker\XF\Template\Templater->renderTemplate('public:alert_us...', Array)
#6 src/XF/Service/Alert/Pusher.php(60): XF\Service\Alert\Pusher->renderPushTemplate('public:alert_us...', Array)
#7 src/XF/Service/PusherTrait.php(175): XF\Service\Alert\Pusher->getNotificationBody()
#8 src/XF/Repository/UserAlert.php(147): XF\Service\Alert\Pusher->push()
#9 src/XF/Repository/UserAlert.php(111): XF\Repository\UserAlert->insertAlert(2637, 0, '', 'user', 2637, 'thdonate_commen...', Array)
#10 src/addons/ThemeHouse/Donate/Repository/Comment.php(39): XF\Repository\UserAlert->alert(Object(Datio\AllowedEmails\XF\Entity\User), 0, '', 'user', 2637, 'thdonate_commen...', Array)
#11 src/addons/ThemeHouse/Donate/Service/Comment/Editor.php(219): ThemeHouse\Donate\Repository\Comment->sendModeratorActionAlert(Object(ThemeHouse\Donate\Entity\Comment), 'edit', 'Checks your spe...')
#12 src/XF/Service/ValidateAndSavableTrait.php(40): ThemeHouse\Donate\Service\Comment\Editor->_save()
#13 src/addons/ThemeHouse/Donate/Pub/Controller/Comment.php(134): ThemeHouse\Donate\Service\Comment\Editor->save()
#14 src/XF/Mvc/Dispatcher.php(350): ThemeHouse\Donate\Pub\Controller\Comment->actionEdit(Object(XF\Mvc\ParameterBag))
#15 src/XF/Mvc/Dispatcher.php(257): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Dona...', 'Edit', Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Donate\Pub\Controller\Comment), NULL)
#16 src/XF/Mvc/Dispatcher.php(113): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Donate\Pub\Controller\Comment), NULL)
#17 src/XF/Mvc/Dispatcher.php(55): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#18 src/XF/App.php(2184): XF\Mvc\Dispatcher->run()
#19 src/XF.php(391): XF\App->run()
#20 index.php(20): XF::runApp('XF\\Pub\\App')
#21 {main}

Request state

array(4) {
  ["url"] => string(22) "/donate/comment/4/edit"
  ["referrer"] => string(70) "/donate/donate-to-nirjonmela.1/campaign/comments"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(10) {
    ["message_html"] => string(47) "<p>Want to Donate, Please send me bkash no.</p>"
    ["_xfInlineEdit"] => string(1) "1"
    ["silent"] => string(1) "1"
    ["clear_edit"] => string(1) "1"
    ["author_alert"] => string(1) "1"
    ["author_alert_reason"] => string(80) "correct your texts."
    ["_xfToken"] => string(8) "********"
    ["_xfRequestUri"] => string(48) "/donate/donate-to-nirjonmela.1/campaign/comments"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}
```

**Comment by LukasWieditz** [comment]
This should be resolved with XenForo 2.1.8 Patch 2. Otherwise we will need XenForo and Add-on version.

**Comment by Nirjonadda** [comment]
@LukasWieditz Yes this issue happened with PL2 and Donate 1.1.4, This issue happened when edit comment with Notify author of this action. Reason:

![ScreenShot00168](https://user-images.githubusercontent.com/6899856/77744672-3c383a80-701a-11ea-9368-baefe90f0a7b.png)

**Comment by Nirjonadda** [comment]
@LukasWieditz Please can you re-open this issue?

**Comment by LukasWieditz** [comment]
Thanks for the bump, missed your last comment.
