### ISSUE TITLE
Donation campaign comments aren't working and an error is experienced on XenForo 2.2 Beta 2

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2208]
```
ErrorException: Template error: Template public:th_donate_campaign_new_comment is unknown src/XF/Template/Templater.php:663
Generated by: Dalton Prock Aug 7, 2020 at 3:11 PM
Stack trace
#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Template public...', '/home/demo/publ...', 663, Array)
#1 src/XF/Template/Templater.php(663): trigger_error('Template public...', 512)
#2 src/XF/Template/Templater.php(1565): XF\Template\Templater->getTemplateData('public', 'th_donate_campa...')
#3 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('th_donate_campa...', Array)
#4 src/XF/Mvc/Renderer/Json.php(84): XF\Template\Template->render()
#5 src/XF/Mvc/Renderer/Json.php(68): XF\Mvc\Renderer\Json->renderHtmlFallback('ThemeHouse\\Dona...', 'public:th_donat...', Array)
#6 src/XF/Mvc/Dispatcher.php(458): XF\Mvc\Renderer\Json->renderView('ThemeHouse\\Dona...', 'public:th_donat...', Array)
#7 src/XF/Mvc/Dispatcher.php(440): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Json), Object(XF\Mvc\Reply\View))
#8 src/XF/Mvc/Dispatcher.php(400): XF\Mvc\Dispatcher->renderReply(Object(XF\Mvc\Renderer\Json), Object(XF\Mvc\Reply\View))
#9 src/XF/Mvc/Dispatcher.php(58): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'json')
#10 src/XF/App.php(2298): XF\Mvc\Dispatcher->run()
#11 src/XF.php(459): XF\App->run()
#12 index.php(20): XF::runApp('XF\\Pub\\App')
#13 {main}
Request state
array(4) {
  ["url"] => string(82) "/test/test/test/index.php?donate/buy-the-team-a-coffee.1/campaign/comments/add"
  ["referrer"] => string(105) "https://test/test/test/test/index.php?donate/buy-the-team-a-coffee.1/campaign/comments"
  ["_GET"] => array(1) {
    ["donate/buy-the-team-a-coffee_1/campaign/comments/add"] => string(0) ""
  }
  ["_POST"] => array(10) {
    ["message_html"] => string(11) "<p>Test</p>"
    ["last_date"] => string(1) "0"
    ["last_known_date"] => string(1) "0"
    ["load_extra"] => string(1) "1"
    ["style"] => string(0) ""
    ["context"] => string(4) "user"
    ["_xfToken"] => string(8) "********"
    ["_xfRequestUri"] => string(78) "/test/test/test/index.php?donate/buy-the-team-a-coffee.1/campaign/comments"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}```

**Comment by LukasWieditz** [comment]
@daltonp this report is missing the error message. Would it be possible to recover this?

**Comment by daltonp** [comment]
Oops, should show the error message now!

**Comment by LukasWieditz** [comment]
Dupliate of 2215
