### ISSUE TITLE
Cover addon still updating..........

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2247]
@LukasWieditz Automatically migrate profile covers to XF 2.2 profile banners are not completed with only 10 covers and all other only color cover. Also seen this Server error log in admin CP with other user admin Login. Cover addon still updating..........

```
ErrorException: [E_NOTICE] Undefined index: max src/addons/ThemeHouse/Covers/Setup.php:284 

Generated by: Nirjonmela Oct 1, 2020 at 9:17 PM 

Stack trace

#0 src/addons/ThemeHouse/Covers/Setup.php(284): XF::handlePhpError(8, '[E_NOTICE] Unde...', '/home/nadda/pub...', 284, Array)
#1 src/XF/AddOn/StepRunnerUpgradeTrait.php(122): ThemeHouse\Covers\Setup->upgrade1010011Step1(Array)
#2 src/XF/AddOn/StepRunnerUpgradeTrait.php(71): ThemeHouse\Covers\Setup->upgradeStepRunner(1010011, 1, Array, NULL)
#3 src/XF/Job/AddOnInstallBatch.php(297): ThemeHouse\Covers\Setup->upgrade(Array)
#4 src/XF/Job/AddOnInstallBatch.php(89): XF\Job\AddOnInstallBatch->stepAction(Object(XF\Timer))
#5 src/XF/Job/Manager.php(258): XF\Job\AddOnInstallBatch->run(G)
#6 src/XF/Job/Manager.php(200): XF\Job\Manager->runJobInternal(Array, G)
#7 src/XF/Job/Manager.php(116): XF\Job\Manager->runJobEntry(Array, G)
#8 src/XF/Admin/Controller/Tools.php(120): XF\Job\Manager->runByIds(Array, 8)
#9 src/XF/Mvc/Dispatcher.php(350): XF\Admin\Controller\Tools->actionRunJob(Object(XF\Mvc\ParameterBag))
#10 src/XF/Mvc/Dispatcher.php(257): XF\Mvc\Dispatcher->dispatchClass('XF:Tools', 'RunJob', Object(XF\Mvc\RouteMatch), Object(NF\Discord\XF\Admin\Controller\Tools), NULL)
#11 src/XF/Mvc/Dispatcher.php(113): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(NF\Discord\XF\Admin\Controller\Tools), NULL)
#12 src/XF/Mvc/Dispatcher.php(55): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#13 src/XF/App.php(2300): XF\Mvc\Dispatcher->run()
#14 src/XF.php(464): XF\App->run()
#15 admin.php(13): XF::runApp('XF\\Admin\\App')
#16 {main}

Request state

array(4) {
  ["url"] => string(24) "/admin.php?tools/run-job"
  ["referrer"] => string(46) "/admin.php?tools/run-job"
  ["_GET"] => array(1) {
    ["tools/run-job"] => string(0) ""
  }
  ["_POST"] => array(3) {
    ["_xfRedirect"] => string(82) "/admin.php?add-ons/install-from-archive-complete&batch_id=79"
    ["_xfToken"] => string(8) "********"
    ["only_ids"] => string(6) "754921"
  }
}
```

**Comment by Nirjonadda** [comment]
OK make a test in test site but this stopping to install.

![ScreenShot00011](https://user-images.githubusercontent.com/6899856/94830528-f23a7200-040b-11eb-97ef-13264b04b17c.png)

Live site is still updating but never completed and admin CP lot og server error log logged.

![ScreenShot00012](https://user-images.githubusercontent.com/6899856/94830700-201fb680-040c-11eb-9d00-d5d86a5b0012.png)

**Comment by Nirjonadda** [comment]
Any update for this issue? How can stop this update process? Do we need close the tab?

**Comment by Nirjonadda** [comment]
@LukasWieditz Why upgrading take a long time (still not completed) when test have only 2 member with 18 post?

**Comment by Nirjonadda** [comment]
I think this update never completed?

**Comment by LukasWieditz** [comment]
References #2254
