### ISSUE TITLE
[Covers] - ErrorException: [E_WARNING] unserialize(): Maximum depth of 4096 exceeded

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2249]
Update are not completed but this error happened after 3 hours update processing...

![ScreenShot00023](https://user-images.githubusercontent.com/6899856/94921644-fd97a700-04b8-11eb-9412-2ef082944718.png)

```
ErrorException: [E_WARNING] unserialize(): Maximum depth of 4096 exceeded. The depth limit can be changed using the max_depth unserialize() option or the unserialize_max_depth ini setting src/XF/Job/Manager.php:236 

Generated by: Nirjonmela Oct 2, 2020 at 6:01 PM 

Stack trace

#0 [internal function]: XF::handlePhpError(2, '[E_WARNING] uns...', '/home/nadda/pub...', 236, Array)
#1 src/XF/Job/Manager.php(236): unserialize('a:9:{s:8:"batch...')
#2 src/XF/Job/Manager.php(241): XF\Job\Manager->getJobRunner(Array)
#3 src/XF/Job/Manager.php(200): XF\Job\Manager->runJobInternal(Array, G)
#4 src/XF/Job/Manager.php(116): XF\Job\Manager->runJobEntry(Array, G)
#5 src/XF/Admin/Controller/Tools.php(120): XF\Job\Manager->runByIds(Array, 8)
#6 src/XF/Mvc/Dispatcher.php(350): XF\Admin\Controller\Tools->actionRunJob(Object(XF\Mvc\ParameterBag))
#7 src/XF/Mvc/Dispatcher.php(257): XF\Mvc\Dispatcher->dispatchClass('XF:Tools', 'RunJob', Object(XF\Mvc\RouteMatch), Object(NF\Discord\XF\Admin\Controller\Tools), NULL)
#8 src/XF/Mvc/Dispatcher.php(113): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(NF\Discord\XF\Admin\Controller\Tools), NULL)
#9 src/XF/Mvc/Dispatcher.php(55): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#10 src/XF/App.php(2300): XF\Mvc\Dispatcher->run()
#11 src/XF.php(464): XF\App->run()
#12 admin.php(13): XF::runApp('XF\\Admin\\App')
#13 {main}

Request state

array(4) {
  ["url"] => string(24) "/admin.php?tools/run-job"
  ["referrer"] => string(46) "/admin.php?tools/run-job"
  ["_GET"] => array(1) {
    ["tools/run-job"] => string(0) ""
  }
  ["_POST"] => array(3) {
    ["_xfRedirect"] => string(82) "/admin.php?add-ons/install-from-archive-complete&batch_id=83"
    ["_xfToken"] => string(8) "********"
    ["only_ids"] => string(6) "759617"
  }
}
```

**Comment by LukasWieditz** [comment]
Not a bug in our code. You've let the installer run against the error for so long that the job log data overflowed.

**Comment by Nirjonadda** [comment]
So how can update covers add-on? Why upgrading take a long time when test site have only 2 member with 18 post?

**Comment by Nirjonadda** [comment]
@LukasWieditz Please update how can fix this issue?
