### ISSUE TITLE
[Image Optimizer] - Status queue blank page

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2468]
![ScreenShot00125](https://user-images.githubusercontent.com/6899856/102922477-5e1dfb00-448e-11eb-8ec0-c2b8565255b9.png)

**Comment by Nirjonadda** [comment]
Server error log:

```
TypeError: Template admin:th_imageoptimizer_status_list error: Argument 2 passed to XF\Proxy\Linker::isUrlBypassed() must be of the type string, null given, called in /home/nadda/public_html/src/XF/Proxy/Linker.php on line 43 src/XF/Proxy/Linker.php:86 

Generated by: Nirjonmela Dec 23, 2020 at 12:47 AM 

Stack trace

#0 src/XF/Proxy/Linker.php(43): XF\Proxy\Linker->isUrlBypassed('image', NULL)
#1 src/XF/SubContainer/Proxy.php(65): XF\Proxy\Linker->generate('image', NULL)
#2 src/addons/ThemeHouse/ImageOptimizer/ContentHandler/ImageProxy.php(66): XF\SubContainer\Proxy->generate('image', NULL)
#3 src/addons/ThemeHouse/ImageOptimizer/Entity/Status.php(198): ThemeHouse\ImageOptimizer\ContentHandler\ImageProxy->getAdminThumbnailUrl(Object(ThemeHouse\ImageOptimizer\Entity\Status))
#4 src/XF/Mvc/Entity/Entity.php(157): ThemeHouse\ImageOptimizer\Entity\Status->getAdminThumbnailUrl()
#5 src/XF/Mvc/Entity/Entity.php(115): XF\Mvc\Entity\Entity->get('admin_thumbnail...')
#6 internal_data/code_cache/templates/l1/s0/admin/th_imageoptimizer_status_list.php(60): XF\Mvc\Entity\Entity->offsetGet('admin_thumbnail...')
#7 src/XF/Template/Templater.php(1626): XF\Template\Templater->{closure}(Object(SV\LazyImageLoader\XF\Template\Templater), Array, NULL)
#8 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('th_imageoptimiz...', Array)
#9 src/XF/Mvc/Renderer/Html.php(48): XF\Template\Template->render()
#10 src/XF/Mvc/Dispatcher.php(458): XF\Mvc\Renderer\Html->renderView('ThemeHouse\\Imag...', 'admin:th_imageo...', Array)
#11 src/XF/Mvc/Dispatcher.php(440): XF\Mvc\Dispatcher->renderView(Object(ThemeHouse\StyleSwitch\XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#12 src/XF/Mvc/Dispatcher.php(400): XF\Mvc\Dispatcher->renderReply(Object(ThemeHouse\StyleSwitch\XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#13 src/XF/Mvc/Dispatcher.php(58): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#14 src/XF/App.php(2300): XF\Mvc\Dispatcher->run()
#15 src/XF.php(488): XF\App->run()
#16 admin.php(13): XF::runApp('XF\\Admin\\App')
#17 {main}

Request state

array(4) {
  ["url"] => string(30) "/admin.php?th-image-optimizer/"
  ["referrer"] => string(52) "/admin.php?logs/server-errors/"
  ["_GET"] => array(1) {
    ["th-image-optimizer/"] => string(0) ""
  }
  ["_POST"] => array(0) {
  }
}
```
