### ISSUE TITLE
[Notifier] - Empty reply from server

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2470]
Server error log:

```
Http\Client\Exception\RequestException: Empty reply from server src/addons/ThemeHouse/Notifier/vendor/php-http/curl-client/src/Client.php:137 

Generated by: Nirjonmela Jan 4, 2021 at 9:42 PM 

Stack trace

#0 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/PluginClient.php(82): Http\Client\Curl\Client->sendRequest(Object(Nyholm\Psr7\Request))
#1 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/Plugin/HeaderAppendPlugin.php(43): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(Nyholm\Psr7\Request))
#2 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/PluginClient.php(161): Http\Client\Common\Plugin\HeaderAppendPlugin->handleRequest(Object(Nyholm\Psr7\Request), Object(Closure), Object(Closure))
#3 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/Plugin/AddHostPlugin.php(64): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(Nyholm\Psr7\Request))
#4 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/PluginClient.php(161): Http\Client\Common\Plugin\AddHostPlugin->handleRequest(Object(Nyholm\Psr7\Request), Object(Closure), Object(Closure))
#5 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/Plugin/AddPathPlugin.php(58): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(Nyholm\Psr7\Request))
#6 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/PluginClient.php(161): Http\Client\Common\Plugin\AddPathPlugin->handleRequest(Object(Nyholm\Psr7\Request), Object(Closure), Object(Closure))
#7 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/Plugin/ErrorPlugin.php(51): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(Nyholm\Psr7\Request))
#8 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/PluginClient.php(161): Http\Client\Common\Plugin\ErrorPlugin->handleRequest(Object(Nyholm\Psr7\Request), Object(Closure), Object(Closure))
#9 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/PluginClient.php(175): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(Nyholm\Psr7\Request))
#10 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/PluginClient.php(88): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(Nyholm\Psr7\Request))
#11 src/addons/ThemeHouse/Notifier/vendor/jane-php/open-api-runtime/Client/Psr7HttplugClient.php(48): Http\Client\Common\PluginClient->sendRequest(Object(Nyholm\Psr7\Request))
#12 src/addons/ThemeHouse/Notifier/vendor/jolicode/slack-php-api/generated/Client.php(617): Jane\OpenApiRuntime\Client\Psr7HttplugClient->executePsr7Endpoint(Object(JoliCode\Slack\Api\Endpoint\ChatPostMessage), 'object')
#13 src/addons/ThemeHouse/Notifier/NotifierProvider/SlackProvider.php(139): JoliCode\Slack\Api\Client->chatPostMessage(Array)
#14 src/addons/ThemeHouse/Notifier/Entity/Action.php(107): ThemeHouse\Notifier\NotifierProvider\SlackProvider->sendMessage('<https://nirjon...', Array)
#15 src/addons/ThemeHouse/Notifier/Action.php(33): ThemeHouse\Notifier\Entity\Action->trigger(Object(SV\BookmarkEssentials\XF\Entity\Post), 'delete', Object(Datio\AllowedEmails\XF\Entity\User))
#16 src/addons/ThemeHouse/Notifier/XF/Entity/Post.php(51): ThemeHouse\Notifier\Action::trigger(Object(SV\BookmarkEssentials\XF\Entity\Post), 'delete')
#17 src/addons/SV/WordCountSearch/XF/Entity/Post.php(184): ThemeHouse\Notifier\XF\Entity\Post->_postDelete()
#18 src/XF/Mvc/Entity/Entity.php(1648): SV\WordCountSearch\XF\Entity\Post->_postDelete()
#19 src/XF/Service/Post/Merger.php(238): XF\Mvc\Entity\Entity->delete()
#20 src/XF/Service/Post/Merger.php(125): XF\Service\Post\Merger->moveDataToTarget()
#21 src/XF/InlineMod/Post/Merge.php(67): XF\Service\Post\Merger->merge(Array)
#22 src/XF/InlineMod/AbstractAction.php(80): XF\InlineMod\Post\Merge->applyInternal(Object(XF\Mvc\Entity\ArrayCollection), Array)
#23 src/XF/Pub/Controller/InlineMod.php(131): XF\InlineMod\AbstractAction->apply(Object(XF\Mvc\Entity\ArrayCollection), Array)
#24 src/addons/Siropu/AdsManager/XF/Pub/Controller/InlineMod.php(54): XF\Pub\Controller\InlineMod->actionPerform()
#25 src/XF/Mvc/Dispatcher.php(350): Siropu\AdsManager\XF\Pub\Controller\InlineMod->actionPerform(Object(XF\Mvc\ParameterBag))
#26 src/XF/Mvc/Dispatcher.php(257): XF\Mvc\Dispatcher->dispatchClass('XF:InlineMod', 'Perform', Object(XF\Mvc\RouteMatch), Object(Siropu\AdsManager\XF\Pub\Controller\InlineMod), Object(XF\Mvc\Reply\Reroute))
#27 src/XF/Mvc/Dispatcher.php(113): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(Siropu\AdsManager\XF\Pub\Controller\InlineMod), Object(XF\Mvc\Reply\Reroute))
#28 src/XF/Mvc/Dispatcher.php(55): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#29 src/XF/App.php(2300): XF\Mvc\Dispatcher->run()
#30 src/XF.php(488): XF\App->run()
#31 index.php(20): XF::runApp('XF\\Pub\\App')
#32 {main}

Request state

array(4) {
  ["url"] => string(12) "/inline-mod/"
  ["referrer"] => string(62) "/threads/caption.73137/page-8"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(11) {
    ["target_post_id"] => string(7) "1960691"
    ["message"] => string(588) "[QUOTE="rahulavijit, post: 1478488, member: 5425"]
[IMG]/images/2020/05/22/ezgif.com-crop.jpg[/IMG]
[/QUOTE]
Chorom uttejok drisho. Amar thik erokm e pochondo. Ghorve sontan asbe.

[QUOTE="rahulavijit, post: 1484871, member: 5425"]
[IMG]/images/2020/05/24/imgonline-com-ua-twotoone-1DVWzYiIIPs.jpg[/IMG]
[/QUOTE]
Erokm gorvoboti dekhei maal pore gelo. Pete bodhoy 2to ki 3te baccha ache. Erokm Gavin gulo abar onekdin pete baccha rakhe. Puro 10 mass njer oi lodhlodhe pete rekhe dey. Khali vabcchi 10 mass obosthay eke kirokm lagbe? Uff"
    ["ids"] => array(2) {
      [0] => string(7) "1960691"
      [1] => string(7) "1960692"
    }
    ["type"] => string(4) "post"
    ["action"] => string(5) "merge"
    ["confirmed"] => string(1) "1"
    ["_xfRedirect"] => string(62) "/threads/caption.73137/page-8"
    ["_xfToken"] => string(8) "********"
    ["_xfRequestUri"] => string(40) "/threads/caption.73137/page-8"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}
```

**Comment by Nirjonadda** [comment]
```
Http\Client\Common\Exception\ServerErrorException: Gateway Timeout src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/Plugin/ErrorPlugin.php:76 

Generated by: Nirjonmela Jan 4, 2021 at 9:40 PM 

Stack trace

#0 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/Plugin/ErrorPlugin.php(54): Http\Client\Common\Plugin\ErrorPlugin->transformResponseToException(Object(Nyholm\Psr7\Request), Object(Nyholm\Psr7\Response))
#1 src/addons/ThemeHouse/Notifier/vendor/php-http/httplug/src/Promise/HttpFulfilledPromise.php(34): Http\Client\Common\Plugin\ErrorPlugin->Http\Client\Common\Plugin\{closure}(Object(Nyholm\Psr7\Response))
#2 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/Plugin/ErrorPlugin.php(55): Http\Client\Promise\HttpFulfilledPromise->then(Object(Closure))
#3 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/PluginClient.php(161): Http\Client\Common\Plugin\ErrorPlugin->handleRequest(Object(Nyholm\Psr7\Request), Object(Closure), Object(Closure))
#4 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/PluginClient.php(175): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(Nyholm\Psr7\Request))
#5 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/PluginClient.php(88): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(Nyholm\Psr7\Request))
#6 src/addons/ThemeHouse/Notifier/vendor/jane-php/open-api-runtime/Client/Psr7HttplugClient.php(48): Http\Client\Common\PluginClient->sendRequest(Object(Nyholm\Psr7\Request))
#7 src/addons/ThemeHouse/Notifier/vendor/jolicode/slack-php-api/generated/Client.php(617): Jane\OpenApiRuntime\Client\Psr7HttplugClient->executePsr7Endpoint(Object(JoliCode\Slack\Api\Endpoint\ChatPostMessage), 'object')
#8 src/addons/ThemeHouse/Notifier/NotifierProvider/SlackProvider.php(139): JoliCode\Slack\Api\Client->chatPostMessage(Array)
#9 src/addons/ThemeHouse/Notifier/Entity/Action.php(107): ThemeHouse\Notifier\NotifierProvider\SlackProvider->sendMessage('<https://nirjon...', Array)
#10 src/addons/ThemeHouse/Notifier/Action.php(33): ThemeHouse\Notifier\Entity\Action->trigger(Object(SV\BookmarkEssentials\XF\Entity\Post), 'delete', Object(Datio\AllowedEmails\XF\Entity\User))
#11 src/addons/ThemeHouse/Notifier/XF/Entity/Post.php(51): ThemeHouse\Notifier\Action::trigger(Object(SV\BookmarkEssentials\XF\Entity\Post), 'delete')
#12 src/addons/SV/WordCountSearch/XF/Entity/Post.php(184): ThemeHouse\Notifier\XF\Entity\Post->_postDelete()
#13 src/XF/Mvc/Entity/Entity.php(1648): SV\WordCountSearch\XF\Entity\Post->_postDelete()
#14 src/XF/Service/Post/Merger.php(238): XF\Mvc\Entity\Entity->delete()
#15 src/XF/Service/Post/Merger.php(125): XF\Service\Post\Merger->moveDataToTarget()
#16 src/XF/InlineMod/Post/Merge.php(67): XF\Service\Post\Merger->merge(Array)
#17 src/XF/InlineMod/AbstractAction.php(80): XF\InlineMod\Post\Merge->applyInternal(Object(XF\Mvc\Entity\ArrayCollection), Array)
#18 src/XF/Pub/Controller/InlineMod.php(131): XF\InlineMod\AbstractAction->apply(Object(XF\Mvc\Entity\ArrayCollection), Array)
#19 src/addons/Siropu/AdsManager/XF/Pub/Controller/InlineMod.php(54): XF\Pub\Controller\InlineMod->actionPerform()
#20 src/XF/Mvc/Dispatcher.php(350): Siropu\AdsManager\XF\Pub\Controller\InlineMod->actionPerform(Object(XF\Mvc\ParameterBag))
#21 src/XF/Mvc/Dispatcher.php(257): XF\Mvc\Dispatcher->dispatchClass('XF:InlineMod', 'Perform', Object(XF\Mvc\RouteMatch), Object(Siropu\AdsManager\XF\Pub\Controller\InlineMod), Object(XF\Mvc\Reply\Reroute))
#22 src/XF/Mvc/Dispatcher.php(113): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(Siropu\AdsManager\XF\Pub\Controller\InlineMod), Object(XF\Mvc\Reply\Reroute))
#23 src/XF/Mvc/Dispatcher.php(55): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#24 src/XF/App.php(2300): XF\Mvc\Dispatcher->run()
#25 src/XF.php(488): XF\App->run()
#26 index.php(20): XF::runApp('XF\\Pub\\App')
#27 {main}
```

**Comment by Nirjonadda** [comment]
```
Http\Client\Common\Exception\ServerErrorException: Service Unavailable src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/Plugin/ErrorPlugin.php:76 

Generated by: Nirjonmela Jan 4, 2021 at 9:40 PM 

Stack trace

#0 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/Plugin/ErrorPlugin.php(54): Http\Client\Common\Plugin\ErrorPlugin->transformResponseToException(Object(Nyholm\Psr7\Request), Object(Nyholm\Psr7\Response))
#1 src/addons/ThemeHouse/Notifier/vendor/php-http/httplug/src/Promise/HttpFulfilledPromise.php(34): Http\Client\Common\Plugin\ErrorPlugin->Http\Client\Common\Plugin\{closure}(Object(Nyholm\Psr7\Response))
#2 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/Plugin/ErrorPlugin.php(55): Http\Client\Promise\HttpFulfilledPromise->then(Object(Closure))
#3 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/PluginClient.php(161): Http\Client\Common\Plugin\ErrorPlugin->handleRequest(Object(Nyholm\Psr7\Request), Object(Closure), Object(Closure))
#4 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/PluginClient.php(175): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(Nyholm\Psr7\Request))
#5 src/addons/ThemeHouse/Notifier/vendor/php-http/client-common/src/PluginClient.php(88): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(Nyholm\Psr7\Request))
#6 src/addons/ThemeHouse/Notifier/vendor/jane-php/open-api-runtime/Client/Psr7HttplugClient.php(48): Http\Client\Common\PluginClient->sendRequest(Object(Nyholm\Psr7\Request))
#7 src/addons/ThemeHouse/Notifier/vendor/jolicode/slack-php-api/generated/Client.php(617): Jane\OpenApiRuntime\Client\Psr7HttplugClient->executePsr7Endpoint(Object(JoliCode\Slack\Api\Endpoint\ChatPostMessage), 'object')
#8 src/addons/ThemeHouse/Notifier/NotifierProvider/SlackProvider.php(139): JoliCode\Slack\Api\Client->chatPostMessage(Array)
#9 src/addons/ThemeHouse/Notifier/Entity/Action.php(107): ThemeHouse\Notifier\NotifierProvider\SlackProvider->sendMessage('<https://nirjon...', Array)
#10 src/addons/ThemeHouse/Notifier/Action.php(33): ThemeHouse\Notifier\Entity\Action->trigger(Object(SV\BookmarkEssentials\XF\Entity\Post), 'delete', Object(Datio\AllowedEmails\XF\Entity\User))
#11 src/addons/ThemeHouse/Notifier/XF/Entity/Post.php(51): ThemeHouse\Notifier\Action::trigger(Object(SV\BookmarkEssentials\XF\Entity\Post), 'delete')
#12 src/addons/SV/WordCountSearch/XF/Entity/Post.php(184): ThemeHouse\Notifier\XF\Entity\Post->_postDelete()
#13 src/XF/Mvc/Entity/Entity.php(1648): SV\WordCountSearch\XF\Entity\Post->_postDelete()
#14 src/XF/Service/Post/Merger.php(238): XF\Mvc\Entity\Entity->delete()
#15 src/XF/Service/Post/Merger.php(125): XF\Service\Post\Merger->moveDataToTarget()
#16 src/XF/InlineMod/Post/Merge.php(67): XF\Service\Post\Merger->merge(Array)
#17 src/XF/InlineMod/AbstractAction.php(80): XF\InlineMod\Post\Merge->applyInternal(Object(XF\Mvc\Entity\ArrayCollection), Array)
#18 src/XF/Pub/Controller/InlineMod.php(131): XF\InlineMod\AbstractAction->apply(Object(XF\Mvc\Entity\ArrayCollection), Array)
#19 src/addons/Siropu/AdsManager/XF/Pub/Controller/InlineMod.php(54): XF\Pub\Controller\InlineMod->actionPerform()
#20 src/XF/Mvc/Dispatcher.php(350): Siropu\AdsManager\XF\Pub\Controller\InlineMod->actionPerform(Object(XF\Mvc\ParameterBag))
#21 src/XF/Mvc/Dispatcher.php(257): XF\Mvc\Dispatcher->dispatchClass('XF:InlineMod', 'Perform', Object(XF\Mvc\RouteMatch), Object(Siropu\AdsManager\XF\Pub\Controller\InlineMod), Object(XF\Mvc\Reply\Reroute))
#22 src/XF/Mvc/Dispatcher.php(113): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(Siropu\AdsManager\XF\Pub\Controller\InlineMod), Object(XF\Mvc\Reply\Reroute))
#23 src/XF/Mvc/Dispatcher.php(55): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#24 src/XF/App.php(2300): XF\Mvc\Dispatcher->run()
#25 src/XF.php(488): XF\App->run()
#26 index.php(20): XF::runApp('XF\\Pub\\App')
#27 {main}
```
