### ISSUE TITLE
Topics Error Filtering

### ISSUE THREAD

**Issue by kylerc** [Audentio/xf2addon-issues#355]
When filtering from the widget, getting the following:

```
An exception occurred: [TypeError] Argument 3 passed to XF\Mvc\Controller::postDispatch() must be an instance of XF\Mvc\Reply\AbstractReply, object given, called in /Users/kyler/repos/xf2/src/XF/Mvc/Dispatcher.php on line 271 in src/XF/Mvc/Controller.php on line 275
#0 src/XF/Mvc/Dispatcher.php(271): XF\Mvc\Controller->postDispatch('Index', Object(XF\Mvc\ParameterBag), Object(XF\Mvc\Reply\Exception))
#1 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Topi...', 'Index', 'json', Object(XF\Mvc\ParameterBag), 'forums', Object(ThemeHouse\Topics\Pub\Controller\TopicThreadList), NULL)
#2 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#3 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#4 src/XF.php(328): XF\App->run()
#5 index.php(13): XF::runApp('XF\\Pub\\App')
#6 {main}```

**Comment by LukasWieditz** [comment]
I think this error pops up when you have the filter widget on a page that doesn't support filtering and try to filter. I've made some adjustments, so that the error will only appear in the JavaScript console anymore. Currently supported pages are Trending Threads, Forum New Posts, Watched Threads & Topic View. Can you confirm @kylerc ?
