### ISSUE TITLE
Covers - `Attempted to convert NULL to integer [content_id]`

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2addon-issues#376]
`InvalidArgumentException: Attempted to convert NULL to integer [content_id]`

**Stack trace:**
`#0 src/XF/Mvc/Entity/Entity.php(575): XF\Mvc\Entity\Entity->_castValueToType(NULL, 'content_id', 2, Array)
#1 src/XF/Mvc/Entity/Entity.php(1300): XF\Mvc\Entity\Entity->set('content_id', NULL, Array)
#2 src/XF/Mvc/Entity/Entity.php(1287): XF\Mvc\Entity\Entity->_resolveDeferredValue('content_id', Object(XF\Mvc\Entity\DeferredValue), 'save')
#3 src/XF/Mvc/Entity/Entity.php(1095): XF\Mvc\Entity\Entity->_fillDeferredValues('save')
#4 src/addons/ThemeHouse/Covers/Entity/Cover.php(337): XF\Mvc\Entity\Entity->save()
#5 src/XF/Mvc/Entity/Entity.php(1234): ThemeHouse\Covers\Entity\Cover->_preSave()
#6 src/XF/Mvc/FormAction.php(51): XF\Mvc\Entity\Entity->preSave()
#7 src/XF/Mvc/FormAction.php(140): XF\Mvc\FormAction->XF\Mvc\{closure}(Object(XF\Mvc\FormAction))
#8 src/addons/ThemeHouse/Covers/Pub/Controller/Cover.php(151): XF\Mvc\FormAction->run()
#9 src/XF/Mvc/Dispatcher.php(249): ThemeHouse\Covers\Pub\Controller\Cover->actionStyle(Object(XF\Mvc\ParameterBag))
#10 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Cove...', 'Style', 'json', Object(XF\Mvc\ParameterBag), '', Object(ThemeHouse\Covers\Pub\Controller\Cover), NULL)
#11 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#12 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#13 src/XF.php(328): XF\App->run()
#14 index.php(13): XF::runApp('XF\\Pub\\App')
#15 {main}

-------------

Previous InvalidArgumentException: Attempted to convert NULL to integer - src/XF/Mvc/Entity/ValueFormatter.php:115
#0 src/XF/Mvc/Entity/Entity.php(684): XF\Mvc\Entity\ValueFormatter->castValueToType(NULL, 2, Array)
#1 src/XF/Mvc/Entity/Entity.php(575): XF\Mvc\Entity\Entity->_castValueToType(NULL, 'content_id', 2, Array)
#2 src/XF/Mvc/Entity/Entity.php(1300): XF\Mvc\Entity\Entity->set('content_id', NULL, Array)
#3 src/XF/Mvc/Entity/Entity.php(1287): XF\Mvc\Entity\Entity->_resolveDeferredValue('content_id', Object(XF\Mvc\Entity\DeferredValue), 'save')
#4 src/XF/Mvc/Entity/Entity.php(1095): XF\Mvc\Entity\Entity->_fillDeferredValues('save')
#5 src/addons/ThemeHouse/Covers/Entity/Cover.php(337): XF\Mvc\Entity\Entity->save()
#6 src/XF/Mvc/Entity/Entity.php(1234): ThemeHouse\Covers\Entity\Cover->_preSave()
#7 src/XF/Mvc/FormAction.php(51): XF\Mvc\Entity\Entity->preSave()
#8 src/XF/Mvc/FormAction.php(140): XF\Mvc\FormAction->XF\Mvc\{closure}(Object(XF\Mvc\FormAction))
#9 src/addons/ThemeHouse/Covers/Pub/Controller/Cover.php(151): XF\Mvc\FormAction->run()
#10 src/XF/Mvc/Dispatcher.php(249): ThemeHouse\Covers\Pub\Controller\Cover->actionStyle(Object(XF\Mvc\ParameterBag))
#11 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Cove...', 'Style', 'json', Object(XF\Mvc\ParameterBag), '', Object(ThemeHouse\Covers\Pub\Controller\Cover), NULL)
#12 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#13 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#14 src/XF.php(328): XF\App->run()
#15 index.php(13): XF::runApp('XF\\Pub\\App')
#16 {main}`

**Comment by tom-coward** [comment]
Error originated from a user profile. Stack trace is:
`array(4) {
  ["url"] => string(23) "/covers/user/1/style"
  ["referrer"] => string(54) "https://example.com/members/member.1/"
  ["_GET"] => array(1) {
    ["/covers/user/1/style"] => string(0) ""
  }
  ["_POST"] => array(6) {
    ["background_color"] => string(0) ""
    ["_xfToken"] => string(8) "********"
    ["delete"] => string(1) "1"
    ["_xfRequestUri"] => string(29) "/members/member.1/"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}`
