### ISSUE TITLE
[TH] Spotify - duplicate key exception

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#429]
```
XF\Db\DuplicateKeyException: MySQL query error [1062]: Duplicate entry '5DR5ROdgm8iSxhZKLXEIbi' for key 'PRIMARY' src/XF/Db/AbstractStatement.php:212
Generated by: Flagy_ May 22, 2018 at 6:44 PM
Stack trace
INSERT  INTO `xf_thspotify_song` (`song_id`, `song_name`, `duration_ms`, `explicit`, `album_name`, `album_thumbnail`, `artists`, `spotify_url`, `spotify_uri`, `spotify_album_url`, `spotify_album_uri`, `last_play`, `last_play_user_id`, `plays`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
------------

#0 src/XF/Db/Mysqli/Statement.php(196): XF\Db\AbstractStatement->getException('MySQL query err...', 1062, '23000')
#1 src/XF/Db/Mysqli/Statement.php(78): XF\Db\Mysqli\Statement->getException('MySQL query err...', 1062, '23000')
#2 src/XF/Db/AbstractAdapter.php(79): XF\Db\Mysqli\Statement->execute()
#3 src/XF/Db/AbstractAdapter.php(161): XF\Db\AbstractAdapter->query('INSERT  INTO `x...', Array)
#4 src/XF/Mvc/Entity/Entity.php(1389): XF\Db\AbstractAdapter->insert('xf_thspotify_so...', Array, false)
#5 src/XF/Mvc/Entity/Entity.php(1121): XF\Mvc\Entity\Entity->_saveToSource()
#6 src/addons/ThemeHouse/Spotify/Repository/SpotifySong.php(46): XF\Mvc\Entity\Entity->save(false)
#7 src/addons/ThemeHouse/Spotify/Service/Player/UpdatePlayback.php(39): ThemeHouse\Spotify\Repository\SpotifySong->insertOrUpdateSongFromSpotifyAPI(Array, Object(Yugensoft\TimeSpentOnline\XF\Entity\User))
#8 src/addons/ThemeHouse/Spotify/Pub/Controller/Spotify.php(41): ThemeHouse\Spotify\Service\Player\UpdatePlayback->updateCurrentPlayback()
#9 src/XF/Mvc/Dispatcher.php(249): ThemeHouse\Spotify\Pub\Controller\Spotify->actionUpdateCurrentPlayback(Object(XF\Mvc\ParameterBag))
#10 src/XF/Mvc/Dispatcher.php(89): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Spot...', 'update-current-...', 'json', Object(XF\Mvc\ParameterBag), '', Object(ThemeHouse\Spotify\Pub\Controller\Spotify), NULL)
#11 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#12 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#13 src/XF.php(328): XF\App->run()
#14 index.php(13): XF::runApp('XF\\Pub\\App')
#15 {main}
Request state
array(4) {
  ["url"] => string(167) "/index.php?spotify/update-current-playback&_xfRequestUri=%2Faccount%2Fprivacy&_xfWithData=1&_xfToken=<censored>&_xfResponseType=json"
  ["referrer"] => string(41) "https://<censored>/account/privacy"
  ["_GET"] => array(5) {
    ["spotify/update-current-playback"] => string(0) ""
    ["_xfRequestUri"] => string(16) "/account/privacy"
    ["_xfWithData"] => string(1) "1"
    ["_xfToken"] => string(43) "1527013383,1c8903693a552edbe825840a5ac30d62"
    ["_xfResponseType"] => string(4) "json"
  }
  ["_POST"] => array(0) {
  }
}
```

**Comment by LukasWieditz** [comment]
I assume this is fixed, as I haven't heard any negative feedback from the customer.

**Comment by jonw316** [comment]
Need to move the start of the transaction otherwise sometimes the transaction won't be committed.

**Comment by LukasWieditz** [comment]
I think if we move this, we can remove the transaction entirely instead. Don't think it serves any purpose like that.
