### ISSUE TITLE
Nodes - Background images disappeared after upgrade

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2addon-issues#458]
After upgrading to latest beta version (1.0.3 Beta 3), all node background images that were previously saved and working fine have disappeared, as shown:
![image](https://user-images.githubusercontent.com/34864926/40809288-e3afbba4-6521-11e8-96d3-f2a575f6f73b.png)

Not entirely sure if this is in some way intentional or un-avoidable, with some changes that have been made as part of the upgrade.

**Comment by Nirjonadda** [comment]
I have fixed with Rebuild cache.

![screenshot00142](https://user-images.githubusercontent.com/6899856/40809448-d46f4eb2-652a-11e8-8f8c-3e9ad3bca676.png)

**Comment by tom-coward** [comment]
Ahh okay, thanks. Might be an idea to run this as one of the upgrade steps then?

**Comment by tom-coward** [comment]
Worth noting as well that before rebuilding the cache was regularly getting this error in the logs:
`Template error: Illegal string offset 'enable'`

**Stack trace:**
```#0 internal_data/code_cache/templates/l1/s0/public/thnodes_generator_macros.php(81): XF\Template\Templater->handleTemplateError(2, 'Illegal string ...', '/home/afellows/...', 81, Array)
#1 src/XF/Template/Templater.php(662): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array, Array)
#2 src/XF/Template/Templater.php(738): XF\Template\Templater->callMacro('public:thnodes_...', 'generator', Array, Array)
#3 src/addons/ThemeHouse/Nodes/Repository/NodeStyling.php(210): XF\Template\Templater->renderMacro('public:thnodes_...', 'generator', Array)
#4 src/addons/ThemeHouse/Nodes/Repository/NodeStyling.php(155): ThemeHouse\Nodes\Repository\NodeStyling->renderNodeStylingForStyle(Object(XF\Style))
#5 src/addons/ThemeHouse/Nodes/Service/NodeStyling/Cache.php(172): ThemeHouse\Nodes\Repository\NodeStyling->buildNodeStylingTemplate(Array)
#6 src/addons/ThemeHouse/Nodes/Service/NodeStyling/Cache.php(75): ThemeHouse\Nodes\Service\NodeStyling\Cache->updateNodeStylingCache()
#7 src/addons/ThemeHouse/Nodes/Repository/NodeStyling.php(142): ThemeHouse\Nodes\Service\NodeStyling\Cache->rebuildCache()
#8 src/addons/ThemeHouse/Nodes/Admin/Controller/NodeLayout.php(50): ThemeHouse\Nodes\Repository\NodeStyling->rebuildNodeStylingCache()
#9 src/XF/Mvc/Dispatcher.php(249): ThemeHouse\Nodes\Admin\Controller\NodeLayout->actionRebuild(Object(XF\Mvc\ParameterBag))
#10 src/XF/Mvc/Dispatcher.php(89): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Node...', 'rebuild', 'html', Object(XF\Mvc\ParameterBag), 'th_nodeLayout_n...', Object(ThemeHouse\Nodes\Admin\Controller\NodeLayout), NULL)
#11 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#12 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#13 src/XF.php(328): XF\App->run()
#14 admin.php(13): XF::runApp('XF\\Admin\\App')
#15 {main}```

**Comment by LukasWieditz** [comment]
The rebuilt process can't be run on installation, as we've modified the way the CSS is generated, but unfortunately the new template is imported by XenForo **after** our installer is run. So there's nothing we can do about here, unfortunately.

**Comment by LukasWieditz** [comment]
Coppied your second bug report into a new ticket. Closing this one.
