### ISSUE TITLE
Nodes - Illegal String offset

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#461]
`Template error: Illegal string offset 'enable'`
```
#1 src/XF/Template/Templater.php(662): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array, Array)
#2 src/XF/Template/Templater.php(738): XF\Template\Templater->callMacro('public:thnodes_...', 'generator', Array, Array)
#3 src/addons/ThemeHouse/Nodes/Repository/NodeStyling.php(210): XF\Template\Templater->renderMacro('public:thnodes_...', 'generator', Array)
#4 src/addons/ThemeHouse/Nodes/Repository/NodeStyling.php(155): ThemeHouse\Nodes\Repository\NodeStyling->renderNodeStylingForStyle(Object(XF\Style))
#5 src/addons/ThemeHouse/Nodes/Service/NodeStyling/Cache.php(172): ThemeHouse\Nodes\Repository\NodeStyling->buildNodeStylingTemplate(Array)
#6 src/addons/ThemeHouse/Nodes/Service/NodeStyling/Cache.php(75): ThemeHouse\Nodes\Service\NodeStyling\Cache->updateNodeStylingCache()
#7 src/addons/ThemeHouse/Nodes/Repository/NodeStyling.php(142): ThemeHouse\Nodes\Service\NodeStyling\Cache->rebuildCache()
#8 src/addons/ThemeHouse/Nodes/Admin/Controller/NodeLayout.php(50): ThemeHouse\Nodes\Repository\NodeStyling->rebuildNodeStylingCache()
#9 src/XF/Mvc/Dispatcher.php(249): ThemeHouse\Nodes\Admin\Controller\NodeLayout->actionRebuild(Object(XF\Mvc\ParameterBag))
#10 src/XF/Mvc/Dispatcher.php(89): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Node...', 'rebuild', 'html', Object(XF\Mvc\ParameterBag), 'th_nodeLayout_n...', Object(ThemeHouse\Nodes\Admin\Controller\NodeLayout), NULL)
#11 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#12 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#13 src/XF.php(328): XF\App->run()
#14 admin.php(13): XF::runApp('XF\\Admin\\App')
#15 {main}
```

**Comment by LukasWieditz** [comment]
References #458
