### ISSUE TITLE
[TH] Q&A - MySQL query error [1364]: Field 'is_sticked' doesn't have a default value

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#472]
Can not make thread in Question & Answer Forums.

````
XF\Db\Exception: MySQL query error [1364]: Field 'is_sticked' doesn't have a default value src/XF/Db/AbstractStatement.php:212 

Generated by: Nirjonadda Jun 1, 2018 at 6:29 PM 

Stack trace

INSERT  INTO `xf_thread` (`node_id`, `user_id`, `username`, `discussion_state`, `title`, `th_is_qa_qaforum`, `post_date`, `last_post_date`, `last_post_user_id`, `last_post_username`, `topic_id`, `thread_id`, `reply_count`, `view_count`, `sticky`, `discussion_open`, `discussion_type`, `first_post_id`, `last_post_id`, `first_post_likes`, `prefix_id`, `custom_fields`, `tags`, `thtrending_replies_views_per_minute`, `thtrending_replies_per_minute`, `thtrending_views_per_minute`, `first_react_users`, `secondary_topic_ids`, `th_answered_qaforum`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
------------

#0 src/XF/Db/Mysqli/Statement.php(196): XF\Db\AbstractStatement->getException('MySQL query err...', 1364, 'HY000')
#1 src/XF/Db/Mysqli/Statement.php(77): XF\Db\Mysqli\Statement->getException('MySQL query err...', 1364, 'HY000')
#2 src/XF/Db/AbstractAdapter.php(79): XF\Db\Mysqli\Statement->execute()
#3 src/XF/Db/AbstractAdapter.php(160): XF\Db\AbstractAdapter->query('INSERT  INTO `x...', Array)
#4 src/XF/Mvc/Entity/Entity.php(1389): XF\Db\AbstractAdapter->insert('xf_thread', Array, false)
#5 src/XF/Mvc/Entity/Entity.php(1121): XF\Mvc\Entity\Entity->_saveToSource()
#6 src/XF/Service/Thread/Creator.php(285): XF\Mvc\Entity\Entity->save(true, false)
#7 src/XF/Service/ValidateAndSavableTrait.php(40): XF\Service\Thread\Creator->_save()
#8 src/XF/Pub/Controller/Forum.php(734): XF\Service\Thread\Creator->save()
#9 src/addons/ThemeHouse/Topics/XF/Pub/Controller/Forum.php(137): XF\Pub\Controller\Forum->actionPostThread(Object(XF\Mvc\ParameterBag))
#10 src/XF/Mvc/Dispatcher.php(249): ThemeHouse\Topics\XF\Pub\Controller\Forum->actionPostThread(Object(XF\Mvc\ParameterBag))
#11 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('XF:Forum', 'PostThread', 'json', Object(XF\Mvc\ParameterBag), 'forums', Object(ThemeHouse\QAForums\XF\Pub\Controller\Forum), NULL)
#12 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#13 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#14 src/XF.php(328): XF\App->run()
#15 index.php(13): XF::runApp('XF\\Pub\\App')
#16 {main}

Request state

array(4) {
  ["url"] => string(58) "/forums/question-answer-forums.7/post-thread?inline-mode=1"
  ["referrer"] => string(56) "/forums/question-answer-forums.7/"
  ["_GET"] => array(1) {
    ["inline-mode"] => string(1) "1"
  }
  ["_POST"] => array(11) {
    ["title"] => string(23) "Node layout and styling"
    ["message_html"] => string(34) "Node layout and styling<p><br></p>"
    ["watch_thread"] => string(1) "1"
    ["watch_thread_email"] => string(1) "1"
    ["_xfSet"] => array(1) {
      ["watch_thread"] => string(1) "1"
    }
    ["attachment_hash"] => string(32) "e588de485e2410b293c21aeeedf027ef"
    ["attachment_hash_combined"] => string(81) "{"type":"post","context":{"node_id":7},"hash":"e588de485e2410b293c21aeeedf027ef"}"
    ["_xfToken"] => string(8) "********"
    ["_xfRequestUri"] => string(33) "/forums/question-answer-forums.7/"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}
````

**Comment by LukasWieditz** [comment]
I'm pretty sure this is an incompatibility with a different add-on. The add-on (whichever it might be) added a new field to the database table, which doesn't have a default value and is therefor not being set by our controller. The author of said add-on will have to fix that on their end.

**Comment by Nirjonadda** [comment]
Yes this issue from other add-on. Uninstalled incompatibility for now for beta testing stage.

**Comment by LukasWieditz** [comment]
The add-on author needs to set a default value when adding his database column to the table upon installation. I'm closing this issue for now.
