### ISSUE TITLE
Reactions - 'getTemplateCacheForUIX' undefined

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2addon-issues#475]
`Call to undefined method ThemeHouse\Reactions\XF\Template\Templater::getTemplateCacheForUIX()`

```#0 src/addons/ThemeHouse/UIX/Listener/App.php(18): ThemeHouse\UIX\Util\UIX->showWelcomeSection(Object(ThemeHouse\Reactions\XF\Template\Templater), 'like_list')
#1 [internal function]: ThemeHouse\UIX\Listener\App::pubRenderPage(Object(XF\Pub\App), Array, Object(XF\Mvc\Reply\View), Object(XF\Mvc\Renderer\Html))
#2 src/XF/Extension.php(67): call_user_func_array(Array, Array)
#3 src/XF/App.php(2392): XF\Extension->fire('app_pub_render_...', Array, NULL)
#4 src/XF/Pub/App.php(447): XF\App->fire('app_pub_render_...', Array)
#5 src/XF/App.php(1766): XF\Pub\App->renderPageHtml('\n\t\n\n\n\n\n\n\t\n\n\n<di...', Array, Object(XF\Mvc\Reply\View), Object(XF\Mvc\Renderer\Html))
#6 src/XF/Mvc/Dispatcher.php(310): XF\App->renderPage('\n\t\n\n\n\n\n\n\t\n\n\n<di...', Object(XF\Mvc\Reply\View), Object(XF\Mvc\Renderer\Html))
#7 src/XF/Mvc/Dispatcher.php(44): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#8 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#9 src/XF.php(328): XF\App->run()
#10 index.php(13): XF::runApp('XF\\Pub\\App')
#11 {main}```

**Comment by LukasWieditz** [comment]
Which version of the UI.X add-on are you running?

**Comment by tom-coward** [comment]
2.0.7 PL1
