### ISSUE TITLE
[Covers] Attempted to convert NULL to integer [content_id]

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#513]
Getting error from Select preset for cover to None.

````
InvalidArgumentException: Attempted to convert NULL to integer [content_id] src/XF/Mvc/Entity/Entity.php:688 

Generated by: SoundTrack Jun 13, 2018 at 3:24 AM 

Stack trace

#0 src/XF/Mvc/Entity/Entity.php(575): XF\Mvc\Entity\Entity->_castValueToType(NULL, 'content_id', 2, Array)
#1 src/XF/Mvc/Entity/Entity.php(1300): XF\Mvc\Entity\Entity->set('content_id', NULL, Array)
#2 src/XF/Mvc/Entity/Entity.php(1287): XF\Mvc\Entity\Entity->_resolveDeferredValue('content_id', Object(XF\Mvc\Entity\DeferredValue), 'save')
#3 src/XF/Mvc/Entity/Entity.php(1095): XF\Mvc\Entity\Entity->_fillDeferredValues('save')
#4 src/addons/ThemeHouse/Covers/Entity/Cover.php(337): XF\Mvc\Entity\Entity->save()
#5 src/XF/Mvc/Entity/Entity.php(1234): ThemeHouse\Covers\Entity\Cover->_preSave()
#6 src/XF/Mvc/Entity/Entity.php(1087): XF\Mvc\Entity\Entity->preSave()
#7 src/addons/ThemeHouse/Covers/Pub/Controller/Cover.php(322): XF\Mvc\Entity\Entity->save()
#8 src/XF/Mvc/Dispatcher.php(249): ThemeHouse\Covers\Pub\Controller\Cover->actionPreset(Object(XF\Mvc\ParameterBag))
#9 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Cove...', 'Preset', 'html', Object(XF\Mvc\ParameterBag), '', Object(ThemeHouse\Covers\Pub\Controller\Cover), NULL)
#10 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#11 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#12 src/XF.php(328): XF\App->run()
#13 index.php(13): XF::runApp('XF\\Pub\\App')
#14 {main}

-------------

Previous InvalidArgumentException: Attempted to convert NULL to integer - src/XF/Mvc/Entity/ValueFormatter.php:115
#0 src/XF/Mvc/Entity/Entity.php(684): XF\Mvc\Entity\ValueFormatter->castValueToType(NULL, 2, Array)
#1 src/XF/Mvc/Entity/Entity.php(575): XF\Mvc\Entity\Entity->_castValueToType(NULL, 'content_id', 2, Array)
#2 src/XF/Mvc/Entity/Entity.php(1300): XF\Mvc\Entity\Entity->set('content_id', NULL, Array)
#3 src/XF/Mvc/Entity/Entity.php(1287): XF\Mvc\Entity\Entity->_resolveDeferredValue('content_id', Object(XF\Mvc\Entity\DeferredValue), 'save')
#4 src/XF/Mvc/Entity/Entity.php(1095): XF\Mvc\Entity\Entity->_fillDeferredValues('save')
#5 src/addons/ThemeHouse/Covers/Entity/Cover.php(337): XF\Mvc\Entity\Entity->save()
#6 src/XF/Mvc/Entity/Entity.php(1234): ThemeHouse\Covers\Entity\Cover->_preSave()
#7 src/XF/Mvc/Entity/Entity.php(1087): XF\Mvc\Entity\Entity->preSave()
#8 src/addons/ThemeHouse/Covers/Pub/Controller/Cover.php(322): XF\Mvc\Entity\Entity->save()
#9 src/XF/Mvc/Dispatcher.php(249): ThemeHouse\Covers\Pub\Controller\Cover->actionPreset(Object(XF\Mvc\ParameterBag))
#10 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Cove...', 'Preset', 'html', Object(XF\Mvc\ParameterBag), '', Object(ThemeHouse\Covers\Pub\Controller\Cover), NULL)
#11 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#12 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#13 src/XF.php(328): XF\App->run()
#14 index.php(13): XF::runApp('XF\\Pub\\App')
#15 {main}

Request state

array(4) {
  ["url"] => string(87) "/covers/user/5/preset?cover_preset_id=0&t=1528838675%2Ce6dfda5f710c887b56b12054a3f5460d"
  ["referrer"] => string(44) "/members/soundtrack.5/"
  ["_GET"] => array(2) {
    ["cover_preset_id"] => string(1) "0"
    ["t"] => string(43) "1528838675,e6dfda5f710c887b56b12054a3f5460d"
  }
  ["_POST"] => array(0) {
  }
}
````

**Comment by Nirjonadda** [comment]
@LukasWieditz Do you have any fix update for this? getting lot of Server error log. Please five bug fix update 1st.

**Comment by LukasWieditz** [comment]
You'd see it here if we had an update on the situation.

**Comment by LukasWieditz** [comment]
I still fail to see the point of failure for this. The pre-dispatch in the controller is explicitly handling all cases of an entity id being null, and I haven't been able to reproduce this once either.
