### ISSUE TITLE
Reactions album like error (missing react handler)

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#540]
```
ErrorException: [E_NOTICE] Undefined index: xfmg_album
src/addons/ThemeHouse/Reactions/Repository/ReactHandler.php:101
Generated by: Nik
Jun 12, 2018 at 9:02 PM
Stack trace
#0 src/addons/ThemeHouse/Reactions/Repository/ReactHandler.php(101): XF::handlePhpError(8, '[E_NOTICE] Unde...', '/home/nginx/dom...', 101, Array)
#1 src/addons/ThemeHouse/Reactions/Repository/ReactedContent.php(591): ThemeHouse\Reactions\Repository\ReactHandler->getReactHandlerByType('xfmg_album', false)
#2 src/addons/ThemeHouse/Reactions/XF/Repository/LikedContent.php(12): ThemeHouse\Reactions\Repository\ReactedContent->getReactHandlerByType('xfmg_album')
#3 src/XF/ControllerPlugin/Like.php(28): ThemeHouse\Reactions\XF\Repository\LikedContent->toggleLike('xfmg_album', 121, Object(ForumApps\API\XF\Entity\User))
#4 src/addons/XFMG/Pub/Controller/Album.php(654): XF\ControllerPlugin\Like->actionToggleLike(Object(XFMG\Entity\Album), '/media/albums/n...', '/media/albums/n...', '/media/albums/n...')
#5 src/XF/Mvc/Dispatcher.php(249): XFMG\Pub\Controller\Album->actionLike(Object(XF\Mvc\ParameterBag))
#6 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('XFMG:Album', 'Like', 'json', Object(XF\Mvc\ParameterBag), 'xfmg', Object(XFMG\Pub\Controller\Album), NULL)
#7 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#8 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#9 src/XF.php(328): XF\App->run()
#10 index.php(13): XF::runApp('XF\Pub\App')
#11 {main}
Request state
array(4) {
["url"] => string(38) "/media/albums/new-c8-corvette.121/like"
["referrer"] => string(68) "https://mysite.com/media/albums/new-c8-corvette.121/"
["_GET"] => array(1) {
["/media/albums/new-c8-corvette_121/like"] => string(0) ""
}
["_POST"] => array(4) {
["_xfRequestUri"] => string(34) "/media/albums/new-c8-corvette.121/"
["_xfWithData"] => string(1) "1"
["_xfToken"] => string(8) "********"
["_xfResponseType"] => string(4) "json"
}
}
```

**Comment by LukasWieditz** [comment]
Fixed the error, so normal likes should work again for now. Will create an actual reaction handler later.
