### ISSUE TITLE
Unknown getter: Bookmarks

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#544]
```
InvalidArgumentException: Accessed unknown getter 'Bookmarks' on XF:User[0] src\XF\Mvc\Entity\Entity.php:182
Generated by: Unknown account Jun 13, 2018 at 1:08 PM
Stack trace
#0 src\XF\Mvc\Entity\Entity.php(100): XF\Mvc\Entity\Entity->get('Bookmarks')
#1 internal_data\code_cache\templates\l1\s50\public\PAGE_CONTAINER.php(1375): XF\Mvc\Entity\Entity->offsetGet('Bookmarks')
#2 src\XF\Template\Templater.php(1249): XF\Template\Templater->{closure}(Object(XF\Template\Templater), Array)
#3 src\XF\Pub\App.php(449): XF\Template\Templater->renderTemplate('PAGE_CONTAINER', Array)
#4 src\XF\App.php(1766): XF\Pub\App->renderPageHtml('<div class="blo...', Array, Object(XF\Mvc\Reply\Message), Object(XF\Mvc\Renderer\Html))
#5 src\XF\Mvc\Dispatcher.php(310): XF\App->renderPage('<div class="blo...', Object(XF\Mvc\Reply\Message), Object(XF\Mvc\Renderer\Html))
#6 src\XF\Mvc\Dispatcher.php(44): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\Message), 'html')
#7 src\XF\App.php(1931): XF\Mvc\Dispatcher->run()
#8 src\XF.php(328): XF\App->run()
#9 index.php(13): XF::runApp('XF\\Pub\\App')
#10 {main}
Request state
array(4) {
  ["url"] => string(31) "/whats-new/profile-posts/97179/"
  ["referrer"] => bool(false)
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}
```

**Comment by LukasWieditz** [comment]
I'm pretty sure the function is used somewhere in UI.X without being wrapped into a conditional check to see if bookmarks is even installed. Assigned this to Ian, as he knows the places he used the function in.

**Comment by Ian-Hitt** [comment]
This should be resolved now, but can you try and replicate just in case?

**Comment by Ian-Hitt** [comment]
Re-assign to me if not fixed, close if it is.
