### ISSUE TITLE
ErrorException: Template error: Template public:news_feed_item_xfmg_comment_react is unknown

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#545]
```
Stack trace
#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Template public...', '/home/theaocdu/...', 583, Array)
#1 src/XF/Template/Templater.php(583): trigger_error('Template public...', 512)
#2 src/XF/Template/Templater.php(538): XF\Template\Templater->getTemplateData('public', 'news_feed_item_...')
#3 src/XF/Template/Templater.php(1248): XF\Template\Templater->getTemplateCode('public', 'news_feed_item_...')
#4 src/XF/NewsFeed/AbstractHandler.php(67): XF\Template\Templater->renderTemplate('news_feed_item_...', Array)
#5 src/XF/Entity/NewsFeed.php(64): XF\NewsFeed\AbstractHandler->render(Object(XF\Entity\NewsFeed))
#6 [internal function]: XF\Entity\NewsFeed->render()
#7 src/XF/Template/Templater.php(939): call_user_func_array(Array, Array)
#8 internal_data/code_cache/templates/l1/s3/public/news_feed_macros.php(34): XF\Template\Templater->method(Object(XF\Entity\NewsFeed), 'render', Array)
#9 src/XF/Template/Templater.php(662): XF\Template\Templater->{closure}(Object(ThemeHouse\Reactions\XF\Template\Templater), Array, Array)
#10 internal_data/code_cache/templates/l1/s3/public/news_feed_macros.php(14): XF\Template\Templater->callMacro('news_feed_macro...', 'feed_item', Array, Array)
#11 src/XF/Template/Templater.php(662): XF\Template\Templater->{closure}(Object(ThemeHouse\Reactions\XF\Template\Templater), Array, Array)
#12 internal_data/code_cache/templates/l1/s3/public/latest_activity.php(27): XF\Template\Templater->callMacro('news_feed_macro...', 'feed_row', Array, Array)
#13 src/XF/Template/Templater.php(1249): XF\Template\Templater->{closure}(Object(ThemeHouse\Reactions\XF\Template\Templater), Array)
#14 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('latest_activity', Array)
#15 src/XF/Mvc/Renderer/Html.php(48): XF\Template\Template->render()
#16 src/XF/Mvc/Dispatcher.php(332): XF\Mvc\Renderer\Html->renderView('XF:WhatsNew\\Lat...', 'public:latest_a...', Array)
#17 src/XF/Mvc/Dispatcher.php(303): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#18 src/XF/Mvc/Dispatcher.php(44): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#19 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#20 src/XF.php(328): XF\App->run()
#21 index.php(13): XF::runApp('XF\\Pub\\App')
#22 {main}
Request state
array(4) {
  ["url"] => string(26) "/whats-new/latest-activity"
  ["referrer"] => string(55) "https://www.theaocdungeon.com/whats-new/latest-activity"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}
```

**Comment by LukasWieditz** [comment]
Template has been created.
