### ISSUE TITLE
XPress - Path to WordPress

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#568]
server error log from Path to WordPress.

````
ErrorException: [E_WARNING] include(/wordpress/wp-load.php): failed to open stream: No such file or directory src/addons/ThemeHouse/XPress/XF/Admin/Controller/Option.php:87 

Generated by: Nirjonadda Jun 22, 2018 at 11:29 PM 

Stack trace

#0 src/addons/ThemeHouse/XPress/XF/Admin/Controller/Option.php(87): XF::handlePhpError(2, '[E_WARNING] inc...', '/home/nminfo/pu...', 87, Array)
#1 src/addons/ThemeHouse/XPress/XF/Admin/Controller/Option.php(87): include()
#2 src/addons/ThemeHouse/XPress/XF/Admin/Controller/Option.php(73): ThemeHouse\XPress\XF\Admin\Controller\Option->updateWPSettings('/wordpress', Array)
#3 src/XF/Mvc/Dispatcher.php(249): ThemeHouse\XPress\XF\Admin\Controller\Option->actionUpdate(Object(XF\Mvc\ParameterBag))
#4 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('XF:Option', 'Update', 'json', Object(XF\Mvc\ParameterBag), 'options', Object(ThemeHouse\XPress\XF\Admin\Controller\Option), NULL)
#5 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#6 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#7 src/XF.php(328): XF\App->run()
#8 admin.php(13): XF::runApp('XF\\Admin\\App')
#9 {main}

Request state

array(4) {
  ["url"] => string(25) "/admin.php?options/update"
  ["referrer"] => string(58) "/admin.php?options/groups/thxpress/"
  ["_GET"] => array(1) {
    ["options/update"] => string(0) ""
  }
  ["_POST"] => array(6) {
    ["options"] => array(6) {
      ["thxpress_wordpress_path"] => string(10) "/wordpress"
      ["thxpress_wordpress_url"] => string(33) "/wordpress"
      ["thxpress_default_node_id"] => string(1) "0"
      ["thxpress_default_user"] => string(0) ""
      ["thxpress_sso_level"] => string(1) "3"
      ["thxpress_admin_user_groups"] => array(1) {
        [0] => string(1) "0"
      }
    }
    ["options_listed"] => array(6) {
      [0] => string(23) "thxpress_wordpress_path"
      [1] => string(22) "thxpress_wordpress_url"
      [2] => string(24) "thxpress_default_node_id"
      [3] => string(21) "thxpress_default_user"
      [4] => string(18) "thxpress_sso_level"
      [5] => string(26) "thxpress_admin_user_groups"
    }
    ["_xfToken"] => string(8) "********"
    ["_xfRequestUri"] => string(35) "/admin.php?options/groups/thxpress/"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}
````

**Comment by mikecreuzer** [comment]
@LukasWieditz looks like he used relative path? Maybe there needs to be a slightly more graceful error message.

**Comment by LukasWieditz** [comment]
There's nothing we can do about the error message, that's bottom level PHP, and `No such file or directory` is pretty descriptive in my opinion. Both sides list the directory you're supposed to copy into the other place though, so it should be manageable.
