### ISSUE TITLE
Reaction cache columns should be mediumblob instead of blob

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#606]
```
XF\Db\Exception: MySQL query error [1406]: Data too long for column 'react_users' at row 1 src/XF/Db/AbstractStatement.php:212
Generated by: ---------- Jul 1, 2018 at 10:37 PM
Stack trace
UPDATE xf_post SET react_users = ? WHERE post_id = 1888053

#0 src/XF/Db/Mysqli/Statement.php(196): XF\Db\AbstractStatement->getException('MySQL query err...', 1406, '22001')
#1 src/XF/Db/Mysqli/Statement.php(77): XF\Db\Mysqli\Statement->getException('MySQL query err...', 1406, '22001')
#2 src/XF/Db/AbstractAdapter.php(79): XF\Db\Mysqli\Statement->execute()
#3 src/XF/Db/AbstractAdapter.php(244): XF\Db\AbstractAdapter->query('UPDATE xf_pos...', Array) #4 src/XF/Mvc/Entity/Entity.php(1394): XF\Db\AbstractAdapter->update('xf_post', Array, 'post_id` = 188...')
#5 src/XF/Mvc/Entity/Entity.php(1121): XF\Mvc\Entity\Entity->_saveToSource()
#6 src/addons/ThemeHouse/Reactions/React/AbstractHandler.php(298): XF\Mvc\Entity\Entity->save()
#7 src/addons/ThemeHouse/Reactions/Repository/ReactedContent.php(268): ThemeHouse\Reactions\React\AbstractHandler->updateContentReacts(Object(ThemeHouse\Reactions\XF\Entity\Post), Array)
#8 src/addons/ThemeHouse/Reactions/Entity/ReactedContent.php(292): ThemeHouse\Reactions\Repository\ReactedContent->rebuildContentReactCache('post', 1888053, 2)
#9 src/addons/ThemeHouse/Reactions/Entity/ReactedContent.php(165): ThemeHouse\Reactions\Entity\ReactedContent->rebuildContentReactCache()
#10 src/XF/Mvc/Entity/Entity.php(1145): ThemeHouse\Reactions\Entity\ReactedContent->_postSave()
#11 src/addons/ThemeHouse/Reactions/Repository/ReactedContent.php(104): XF\Mvc\Entity\Entity->save()
#12 src/addons/ThemeHouse/Reactions/ControllerPlugin/React.php(29): ThemeHouse\Reactions\Repository\ReactedContent->insertReact(Object(ThemeHouse\Reactions\XF\Entity\Post), Object(ThemeHouse\Reactions\Entity\ReactedContent))
#13 src/addons/ThemeHouse/Reactions/Pub/Controller/React.php(61): ThemeHouse\Reactions\ControllerPlugin\React->actionToggleReact(Object(ThemeHouse\Reactions\XF\Entity\Post), Object(ThemeHouse\Reactions\Entity\ReactedContent), 'insert')
#14 src/XF/Mvc/Dispatcher.php(249): ThemeHouse\Reactions\Pub\Controller\React->actionReact(Object(XF\Mvc\ParameterBag))
#15 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\Reac...', 'React', 'json', Object(XF\Mvc\ParameterBag), 'reactions', Object(ThemeHouse\Reactions\Pub\Controller\React), NULL)
#16 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#17 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#18 src/XF.php(328): XF\App->run()
#19 index.php(13): XF::runApp('XF\Pub\App')
#20 {main}
```

**Comment by LukasWieditz** [comment]
Reaction cache database columns have been converted to mediumblob to prevent data truncation.
