### ISSUE TITLE
[TH] Q&A - Server error log

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#701]
Server error log when reply to Q&A forum.

````
Error: Call to a member function last() on array src/addons/ThemeHouse/QAForums/XF/Pub/Controller/Thread.php:156 

Generated by: Nirjonadda Sep 11, 2018 at 12:54 PM 

Stack trace

#0 src/XF/Pub/Controller/Thread.php(439): ThemeHouse\QAForums\XF\Pub\Controller\Thread->getNewPostsReply(Object(DBTech\UserTagging\XF\Entity\Thread), 0)
#1 src/addons/xenMade/SEO/XF/Pub/Controller/Thread.php(219): XF\Pub\Controller\Thread->actionAddReply(Object(XF\Mvc\ParameterBag))
#2 src/addons/KL/EditorManager/XF/Pub/Controller/Thread.php(17): xenMade\SEO\XF\Pub\Controller\Thread->actionAddReply(Object(XF\Mvc\ParameterBag))
#3 src/XF/Mvc/Dispatcher.php(249): KL\EditorManager\XF\Pub\Controller\Thread->actionAddReply(Object(XF\Mvc\ParameterBag))
#4 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('XF:Thread', 'AddReply', 'json', Object(XF\Mvc\ParameterBag), 'forums', Object(KL\EditorManager\XF\Pub\Controller\Thread), NULL)
#5 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#6 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#7 src/XF.php(328): XF\App->run()
#8 index.php(13): XF::runApp('XF\\Pub\\App')
#9 {main}

Request state

array(4) {
  ["url"] => string(35) "/threads/post-comments.50/add-reply"
  ["referrer"] => string(49) "/threads/post-comments.50/"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(10) {
    ["message_html"] => string(9) "<p>ho</p>"
    ["attachment_hash"] => string(32) "348ae206caf8e46fc1939fed155f44fb"
    ["attachment_hash_combined"] => string(84) "{"type":"post","context":{"thread_id":50},"hash":"348ae206caf8e46fc1939fed155f44fb"}"
    ["last_date"] => string(0) ""
    ["last_known_date"] => string(10) "1536666830"
    ["klPage"] => string(0) ""
    ["_xfToken"] => string(8) "********"
    ["_xfRequestUri"] => string(26) "/threads/post-comments.50/"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}
````

**Comment by LukasWieditz** [comment]
Can you try to reproduce that without any 3rd party add-ons?

**Comment by Nirjonadda** [comment]
all 3rd party add-ons disabled without [TH] add-on

````
Error: Call to a member function last() on array src/addons/ThemeHouse/QAForums/XF/Pub/Controller/Thread.php:156 

Generated by: Nirjonadda Sep 11, 2018 at 1:00 PM 

Stack trace

#0 src/XF/Pub/Controller/Thread.php(439): ThemeHouse\QAForums\XF\Pub\Controller\Thread->getNewPostsReply(Object(ThemeHouse\QAForums\XF\Entity\Thread), 1536667183)
#1 src/XF/Mvc/Dispatcher.php(249): XF\Pub\Controller\Thread->actionAddReply(Object(XF\Mvc\ParameterBag))
#2 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('XF:Thread', 'AddReply', 'json', Object(XF\Mvc\ParameterBag), 'forums', Object(ThemeHouse\QAForums\XF\Pub\Controller\Thread), NULL)
#3 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#4 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#5 src/XF.php(328): XF\App->run()
#6 index.php(13): XF::runApp('XF\\Pub\\App')
#7 {main}

Request state

array(4) {
  ["url"] => string(35) "/threads/post-comments.50/add-reply"
  ["referrer"] => string(49) "/threads/post-comments.50/"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(9) {
    ["message_html"] => string(20) "<p>&nbsp;Add-ons</p>"
    ["attachment_hash"] => string(32) "69f692cdf92c0893590fccc2aed8c994"
    ["attachment_hash_combined"] => string(84) "{"type":"post","context":{"thread_id":50},"hash":"69f692cdf92c0893590fccc2aed8c994"}"
    ["last_date"] => string(10) "1536667183"
    ["last_known_date"] => string(10) "1536667197"
    ["_xfToken"] => string(8) "********"
    ["_xfRequestUri"] => string(26) "/threads/post-comments.50/"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}
````

**Comment by LukasWieditz** [comment]
Any steps on how to reproduce this error? I see the state the system had to be in for it to trigger, but I don't see how it would get there.

**Comment by Nirjonadda** [comment]
Try reply to Q&A forum thread.
