### ISSUE TITLE
 [TH] Install & Upgrade -  Available add-ons 

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#821]
Install Available add-ons will be error,  th_iau_addon_id_not_found_in_package. Available add-ons are installed but this should be show update to new version when available or show up to date.

![screenshot00365](https://user-images.githubusercontent.com/6899856/46098169-0bc4d580-c1c4-11e8-9edd-11d3ba8ac040.png)

 Server error logs

````
ErrorException: [E_WARNING] count(): Parameter must be an array or an object that implements Countable src/addons/ThemeHouse/InstallAndUpgrade/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Selector.php:171 

Generated by: Unknown account Sep 26, 2018 at 6:35 PM 

Stack trace

#0 [internal function]: XF::handlePhpError(2, '[E_WARNING] cou...', '/home/nminfo/pu...', 171, Array)
#1 src/addons/ThemeHouse/InstallAndUpgrade/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Selector.php(171): count('meta')
#2 src/addons/ThemeHouse/InstallAndUpgrade/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Selector.php(69): PHPHtmlParser\Selector->seek(Array, Array, Array)
#3 src/addons/ThemeHouse/InstallAndUpgrade/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Dom/AbstractNode.php(367): PHPHtmlParser\Selector->find(Object(PHPHtmlParser\Dom\HtmlNode))
#4 src/addons/ThemeHouse/InstallAndUpgrade/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Dom.php(621): PHPHtmlParser\Dom\AbstractNode->find(Object(PHPHtmlParser\Selector), 0)
#5 src/addons/ThemeHouse/InstallAndUpgrade/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Dom.php(190): PHPHtmlParser\Dom->detectCharset()
#6 src/addons/ThemeHouse/InstallAndUpgrade/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Dom.php(132): PHPHtmlParser\Dom->loadStr('<!DOCTYPE html>...', Array)
#7 src/addons/ThemeHouse/InstallAndUpgrade/InstallAndUpgrade/XenForo.php(183): PHPHtmlParser\Dom->load('<!DOCTYPE html>...')
#8 src/addons/ThemeHouse/InstallAndUpgrade/InstallAndUpgrade/XenForo.php(325): ThemeHouse\InstallAndUpgrade\InstallAndUpgrade\XenForo->getLicenseId()
#9 src/addons/ThemeHouse/InstallAndUpgrade/InstallAndUpgrade/XenForo.php(239): ThemeHouse\InstallAndUpgrade\InstallAndUpgrade\XenForo->checkAddOnForUpdates(Object(ThemeHouse\InstallAndUpgrade\Entity\InstallUpgradeAddOn))
#10 src/addons/ThemeHouse/InstallAndUpgrade/Cron/CheckXenForoForUpdates.php(19): ThemeHouse\InstallAndUpgrade\InstallAndUpgrade\XenForo->checkForUpdates()
#11 [internal function]: ThemeHouse\InstallAndUpgrade\Cron\CheckXenForoForUpdates::run(Object(XF\Entity\CronEntry))
#12 src/XF/Job/Cron.php(35): call_user_func(Array, Object(XF\Entity\CronEntry))
#13 src/XF/Job/Manager.php(241): XF\Job\Cron->run(7.9999969005585)
#14 src/XF/Job/Manager.php(187): XF\Job\Manager->runJobInternal(Array, 7.9999969005585)
#15 src/XF/Job/Manager.php(76): XF\Job\Manager->runJobEntry(Array, 7.9999969005585)
#16 job.php(15): XF\Job\Manager->runQueue(false, 8)
#17 {main}

Request state

array(4) {
  ["url"] => string(8) "/job.php"
  ["referrer"] => string(24) "/"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}
````

**Comment by LukasWieditz** [comment]
Server error log is not from that action. You also created two different issues for the same error...

Either way, XPress is not supported by Install & Upgrade, but the phrase is missing indeed.
