### ISSUE TITLE
Function reaction is unknown

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#835]
```#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Function reacti...', '/home/clientdem...', 860, Array)
#1 src/XF/Template/Templater.php(860): trigger_error('Function reacti...', 512)
#2 internal_data/code_cache/templates/l1/s5/public/news_feed_item_post_react.php(17): XF\Template\Templater->fn('reaction', Array, true)
#3 src/XF/Template/Templater.php(1250): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array)
#4 src/XF/NewsFeed/AbstractHandler.php(67): XF\Template\Templater->renderTemplate('public:news_fee...', Array)
#5 src/XF/Entity/NewsFeed.php(64): XF\NewsFeed\AbstractHandler->render(Object(XF\Entity\NewsFeed))
#6 [internal function]: XF\Entity\NewsFeed->render()
#7 src/XF/Template/Templater.php(940): call_user_func_array(Array, Array)
#8 internal_data/code_cache/templates/l1/s5/public/news_feed_macros.php(34): XF\Template\Templater->method(Object(XF\Entity\NewsFeed), 'render', Array)
#9 src/XF/Template/Templater.php(663): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array, Array)
#10 internal_data/code_cache/templates/l1/s5/public/news_feed_macros.php(14): XF\Template\Templater->callMacro(NULL, 'feed_item', Array, Array)
#11 src/XF/Template/Templater.php(663): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array, Array)
#12 internal_data/code_cache/templates/l1/s5/public/member_latest_activity.php(34): XF\Template\Templater->callMacro('news_feed_macro...', 'feed_row', Array, Array)
#13 src/XF/Template/Templater.php(1250): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array)
#14 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('public:member_l...', Array)
#15 src/XF/Mvc/Renderer/Json.php(81): XF\Template\Template->render()
#16 src/XF/Mvc/Renderer/Json.php(65): XF\Mvc\Renderer\Json->renderHtmlFallback('XF:Member\\Lates...', 'public:member_l...', Array)
#17 src/XF/Mvc/Dispatcher.php(332): XF\Mvc\Renderer\Json->renderView('XF:Member\\Lates...', 'public:member_l...', Array)
#18 src/XF/Mvc/Dispatcher.php(303): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Json), Object(XF\Mvc\Reply\View))
#19 src/XF/Mvc/Dispatcher.php(44): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'json')
#20 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#21 src/XF.php(329): XF\App->run()
#22 index.php(13): XF::runApp('XF\\Pub\\App')
#23 {main}```

Just shows in server log but I dont see any issue otherwise

**Comment by LukasWieditz** [comment]
We talked about this in the past already. You have reactions disabled, but have a reaction alert in your alerts. XF is trying to render the alert, even though the related add-on is disabled, hence the function is not available. It's a bug in XF.

**Comment by Nirjonadda** [comment]
@LukasWieditz Do you reported this bug to Xenforo?

**Comment by LukasWieditz** [comment]
They are aware of it.
