### ISSUE TITLE
 [TH] Reactions - Table 'xf_mg_media_item' does not exist so cannot be altered

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#892]
Get Server error log from installation but Its installed after this error. now its are not show up in  Installed products

![screenshot00492](https://user-images.githubusercontent.com/6899856/46697787-b9e56c00-cc15-11e8-85b1-779bfca086a7.png)

![screenshot00491](https://user-images.githubusercontent.com/6899856/46697725-928e9f00-cc15-11e8-9cc9-673067e19257.png)

````
InvalidArgumentException: Table 'xf_mg_media_item' does not exist so cannot be altered src/XF/Db/Schema/Alter.php:38 

Generated by: Nirjonadda Oct 9, 2018 at 9:42 PM 

Stack trace

#0 src/XF/Db/SchemaManager.php(188): XF\Db\Schema\Alter->__construct(Object(XF\Db\Mysqli\Adapter), Object(XF\Db\SchemaManager), 'xf_mg_media_ite...')
#1 src/XF/Db/SchemaManager.php(141): XF\Db\SchemaManager->newAlter('xf_mg_media_ite...')
#2 src/addons/ThemeHouse/Reactions/Repository/Setup.php(23): XF\Db\SchemaManager->alterTable('xf_mg_media_ite...', Object(Closure))
#3 src/addons/ThemeHouse/Reactions/XF/Entity/AddOn.php(15): ThemeHouse\Reactions\Repository\Setup->setupColumnsForAddOn('XFMG')
#4 src/XF.php(244): ThemeHouse\Reactions\XF\Entity\AddOn->ThemeHouse\Reactions\XF\Entity\{closure}()
#5 src/XF/Mvc/Dispatcher.php(137): XF::triggerRunOnce(true)
#6 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#7 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#8 src/XF.php(328): XF\App->run()
#9 admin.php(13): XF::runApp('XF\\Admin\\App')
#10 {main}

Request state

array(4) {
  ["url"] => string(31) "/admin.php?add-ons/XFMG/install"
  ["referrer"] => string(67) "/admin.php?install-upgrade-products/add-ons/"
  ["_GET"] => array(1) {
    ["add-ons/XFMG/install"] => string(0) ""
  }
  ["_POST"] => array(2) {
    ["_xfRedirect"] => string(67) "/admin.php?install-upgrade-products/add-ons/"
    ["_xfToken"] => string(8) "********"
  }
}
````

**Comment by JakeBooher** [comment]
Looks like this is coming from Reactions @LukasWieditz

**Comment by Nirjonadda** [comment]
@JakeBooher Yes, Disable reactions will working installation.
