### ISSUE TITLE
[TH] Install & Upgrade - Template public:alert_user_th_iau_addOn_updateAvailable is unknown

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#926]
````
ErrorException: Template error: Template public:alert_user_th_iau_addOn_updateAvailable is unknown src/XF/Template/Templater.php:583 

Generated by: Nirjonadda Oct 13, 2018 at 11:00 PM 

Stack trace

#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Template public...', '/home/nminfo/pu...', 583, Array)
#1 src/XF/Template/Templater.php(583): trigger_error('Template public...', 512)
#2 src/XF/Template/Templater.php(538): XF\Template\Templater->getTemplateData('public', 'alert_user_th_i...')
#3 src/XF/Template/Templater.php(1248): XF\Template\Templater->getTemplateCode('public', 'alert_user_th_i...')
#4 src/XF/Alert/AbstractHandler.php(67): XF\Template\Templater->renderTemplate('alert_user_th_i...', Array)
#5 src/XF/Entity/UserAlert.php(69): XF\Alert\AbstractHandler->render(Object(XF\Entity\UserAlert))
#6 [internal function]: XF\Entity\UserAlert->render()
#7 src/XF/Template/Templater.php(939): call_user_func_array(Array, Array)
#8 internal_data/code_cache/templates/l1/s1/public/alert_macros.php(18): XF\Template\Templater->method(Object(XF\Entity\UserAlert), 'render', Array)
#9 src/XF/Template/Templater.php(662): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array, Array)
#10 internal_data/code_cache/templates/l1/s1/public/account_alerts_popup.php(21): XF\Template\Templater->callMacro('alert_macros', 'row', Array, Array)
#11 src/XF/Template/Templater.php(1249): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array)
#12 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('account_alerts_...', Array)
#13 src/XF/Mvc/Renderer/Json.php(81): XF\Template\Template->render()
#14 src/XF/Mvc/Renderer/Json.php(65): XF\Mvc\Renderer\Json->renderHtmlFallback('XF:Account\\Aler...', 'public:account_...', Array)
#15 src/XF/Mvc/Dispatcher.php(332): XF\Mvc\Renderer\Json->renderView('XF:Account\\Aler...', 'public:account_...', Array)
#16 src/XF/Mvc/Dispatcher.php(303): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Json), Object(XF\Mvc\Reply\View))
#17 src/XF/Mvc/Dispatcher.php(44): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'json')
#18 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#19 src/XF.php(328): XF\App->run()
#20 index.php(13): XF::runApp('XF\\Pub\\App')
#21 {main}

Request state

array(4) {
  ["url"] => string(168) "/account/alerts-popup?_xfRequestUri=%2Fconversations%2Fso.6%2F&_xfWithData=1&_xfToken=1539468005%2Cdb8325cd926d313ded2e59fadd601677&_xfResponseType=json&_=1539468009615"
  ["referrer"] => string(43) "/so.6/"
  ["_GET"] => array(5) {
    ["_xfRequestUri"] => string(20) "/conversations/so.6/"
    ["_xfWithData"] => string(1) "1"
    ["_xfToken"] => string(43) "1539468005,db8325cd926d313ded2e59fadd601677"
    ["_xfResponseType"] => string(4) "json"
    ["_"] => string(13) "1539468009615"
  }
  ["_POST"] => array(0) {
  }
}
````

**Comment by LukasWieditz** [comment]
Already said that is fixed for the next update.
